// Generated by scripts/generate-pokemon-de.mjs
export const LOCATION_SUGGESTIONS: Record<string, { name: string; slug: string; region: string }[]> = {
  "en": [
    {
      "name": "???",
      "slug": "inside-of-truck",
      "region": "hoenn"
    },
    {
      "name": "Abandoned Ship",
      "slug": "abandoned-ship",
      "region": "hoenn"
    },
    {
      "name": "Abundant Shrine",
      "slug": "abundant-shrine",
      "region": "unova"
    },
    {
      "name": "Abyssal Ruins",
      "slug": "abyssal-ruins",
      "region": "unova"
    },
    {
      "name": "Accumula Gate",
      "slug": "accumula-gate",
      "region": "unova"
    },
    {
      "name": "Accumula Town",
      "slug": "accumula-town",
      "region": "unova"
    },
    {
      "name": "Acuity Cavern",
      "slug": "acuity-cavern",
      "region": "sinnoh"
    },
    {
      "name": "Acuity Lakefront",
      "slug": "acuity-lakefront",
      "region": "sinnoh"
    },
    {
      "name": "Altering Cave",
      "slug": "hoenn-altering-cave",
      "region": "hoenn"
    },
    {
      "name": "Altering Cave",
      "slug": "kanto-altering-cave",
      "region": "kanto"
    },
    {
      "name": "Ambrette Aquarium",
      "slug": "ambrette-aquarium",
      "region": "kalos"
    },
    {
      "name": "Ambrette Gate",
      "slug": "ambrette-gate",
      "region": "kalos"
    },
    {
      "name": "Ambrette Town",
      "slug": "ambrette-town",
      "region": "kalos"
    },
    {
      "name": "Amity Square",
      "slug": "amity-square",
      "region": "sinnoh"
    },
    {
      "name": "Ancient Tomb",
      "slug": "ancient-tomb",
      "region": "hoenn"
    },
    {
      "name": "Anistar City",
      "slug": "anistar-city",
      "region": "kalos"
    },
    {
      "name": "Anistar Gate",
      "slug": "anistar-gate",
      "region": "kalos"
    },
    {
      "name": "Anville Town",
      "slug": "anville-town",
      "region": "unova"
    },
    {
      "name": "Aquacorde Town",
      "slug": "aquacorde-town",
      "region": "kalos"
    },
    {
      "name": "Artisan Cave",
      "slug": "artisan-cave",
      "region": "hoenn"
    },
    {
      "name": "Aspertia City",
      "slug": "aspertia-city",
      "region": "unova"
    },
    {
      "name": "Aspertia Gate",
      "slug": "aspertia-gate",
      "region": "unova"
    },
    {
      "name": "Avance Trail",
      "slug": "avance-trail",
      "region": "kalos"
    },
    {
      "name": "Azalea Town",
      "slug": "azalea-town",
      "region": "johto"
    },
    {
      "name": "Azure Bay",
      "slug": "azure-bay",
      "region": "kalos"
    },
    {
      "name": "Battle Arcade",
      "slug": "battle-arcade",
      "region": "sinnoh"
    },
    {
      "name": "Battle Castle",
      "slug": "battle-castle",
      "region": "sinnoh"
    },
    {
      "name": "Battle Chateau",
      "slug": "battle-chateau",
      "region": "kalos"
    },
    {
      "name": "Battle Factory",
      "slug": "battle-factory",
      "region": "sinnoh"
    },
    {
      "name": "Battle Frontier",
      "slug": "battle-frontier",
      "region": "sinnoh"
    },
    {
      "name": "Battle Hall",
      "slug": "battle-hall",
      "region": "sinnoh"
    },
    {
      "name": "Battle Maison",
      "slug": "battle-maison",
      "region": "kalos"
    },
    {
      "name": "Battle Park",
      "slug": "battle-park",
      "region": "sinnoh"
    },
    {
      "name": "Battle Resort",
      "slug": "battle-resort",
      "region": "hoenn"
    },
    {
      "name": "Battle Subway",
      "slug": "battle-subway",
      "region": "unova"
    },
    {
      "name": "Battle Tower",
      "slug": "sinnoh-battle-tower",
      "region": "sinnoh"
    },
    {
      "name": "Battle Tower",
      "slug": "hoenn-battle-tower",
      "region": "hoenn"
    },
    {
      "name": "Battleground",
      "slug": "battleground",
      "region": "sinnoh"
    },
    {
      "name": "Bell Tower",
      "slug": "bell-tower",
      "region": "johto"
    },
    {
      "name": "Bellchime Trail",
      "slug": "bellchime-trail",
      "region": "johto"
    },
    {
      "name": "Berry Forest",
      "slug": "berry-forest",
      "region": "kanto"
    },
    {
      "name": "Birth Island",
      "slug": "birth-island",
      "region": "kanto"
    },
    {
      "name": "Black City",
      "slug": "black-city",
      "region": "unova"
    },
    {
      "name": "Black Gate",
      "slug": "black-gate",
      "region": "unova"
    },
    {
      "name": "Black Tower",
      "slug": "black-tower",
      "region": "unova"
    },
    {
      "name": "Blackthorn City",
      "slug": "blackthorn-city",
      "region": "johto"
    },
    {
      "name": "Blazing Chamber",
      "slug": "blazing-chamber",
      "region": "kalos"
    },
    {
      "name": "Bond Bridge",
      "slug": "bond-bridge",
      "region": "kanto"
    },
    {
      "name": "Bridge Gate",
      "slug": "bridge-gate",
      "region": "unova"
    },
    {
      "name": "Brun Way",
      "slug": "brun-way",
      "region": "kalos"
    },
    {
      "name": "Burned Tower",
      "slug": "burned-tower",
      "region": "johto"
    },
    {
      "name": "Café",
      "slug": "sinnoh-cafe",
      "region": "sinnoh"
    },
    {
      "name": "Camphrier Town",
      "slug": "camphrier-town",
      "region": "kalos"
    },
    {
      "name": "Canalave City",
      "slug": "canalave-city",
      "region": "sinnoh"
    },
    {
      "name": "Canalave Library",
      "slug": "canalave-library",
      "region": "sinnoh"
    },
    {
      "name": "Canyon Entrance",
      "slug": "canyon-entrance",
      "region": "kanto"
    },
    {
      "name": "Cape Brink",
      "slug": "cape-brink",
      "region": "kanto"
    },
    {
      "name": "Castelia City",
      "slug": "castelia-city",
      "region": "unova"
    },
    {
      "name": "Castelia Gate",
      "slug": "castelia-gate",
      "region": "unova"
    },
    {
      "name": "Castelia Sewers",
      "slug": "castelia-sewers",
      "region": "unova"
    },
    {
      "name": "Cave of Being",
      "slug": "cave-of-being",
      "region": "unova"
    },
    {
      "name": "Cave of Origin",
      "slug": "cave-of-origin",
      "region": "hoenn"
    },
    {
      "name": "Celadon City",
      "slug": "celadon-city",
      "region": "kanto"
    },
    {
      "name": "Celestial Tower",
      "slug": "celestial-tower",
      "region": "unova"
    },
    {
      "name": "Celestic Town",
      "slug": "celestic-town",
      "region": "sinnoh"
    },
    {
      "name": "Cerulean Cave",
      "slug": "cerulean-cave",
      "region": "kanto"
    },
    {
      "name": "Cerulean City",
      "slug": "cerulean-city",
      "region": "kanto"
    },
    {
      "name": "Challenger's Cave",
      "slug": "challengers-cave",
      "region": "unova"
    },
    {
      "name": "Chamber of Emptiness",
      "slug": "chamber-of-emptiness",
      "region": "kalos"
    },
    {
      "name": "Chargestone Cave",
      "slug": "chargestone-cave",
      "region": "unova"
    },
    {
      "name": "Cherrygrove City",
      "slug": "cherrygrove-city",
      "region": "johto"
    },
    {
      "name": "Cianwood City",
      "slug": "cianwood-city",
      "region": "johto"
    },
    {
      "name": "Cinnabar Island",
      "slug": "cinnabar-island",
      "region": "kanto"
    },
    {
      "name": "Clay Tunnel",
      "slug": "clay-tunnel",
      "region": "unova"
    },
    {
      "name": "Cliff Cave",
      "slug": "cliff-cave",
      "region": "johto"
    },
    {
      "name": "Cliff Edge Gate",
      "slug": "cliff-edge-gate",
      "region": "johto"
    },
    {
      "name": "Cold Storage",
      "slug": "cold-storage",
      "region": "unova"
    },
    {
      "name": "Connecting Cave",
      "slug": "connecting-cave",
      "region": "kalos"
    },
    {
      "name": "Contest Hall",
      "slug": "contest-hall",
      "region": "sinnoh"
    },
    {
      "name": "Coumarine City",
      "slug": "coumarine-city",
      "region": "kalos"
    },
    {
      "name": "Coumarine Gate",
      "slug": "coumarine-gate",
      "region": "kalos"
    },
    {
      "name": "Couriway Gate",
      "slug": "couriway-gate",
      "region": "kalos"
    },
    {
      "name": "Couriway Town",
      "slug": "couriway-town",
      "region": "kalos"
    },
    {
      "name": "Crescent Isle",
      "slug": "crescent-isle",
      "region": "hoenn"
    },
    {
      "name": "Cycle Shop",
      "slug": "sinnoh-cycle-shop",
      "region": "sinnoh"
    },
    {
      "name": "Cyllage City",
      "slug": "cyllage-city",
      "region": "kalos"
    },
    {
      "name": "Dark Cave",
      "slug": "dark-cave",
      "region": "johto"
    },
    {
      "name": "Dendemille Gate",
      "slug": "dendemille-gate",
      "region": "kalos"
    },
    {
      "name": "Dendemille Town",
      "slug": "dendemille-town",
      "region": "kalos"
    },
    {
      "name": "Desert Resort",
      "slug": "desert-resort",
      "region": "unova"
    },
    {
      "name": "Desert Ruins",
      "slug": "desert-ruins",
      "region": "hoenn"
    },
    {
      "name": "Desert Underpass",
      "slug": "desert-underpass",
      "region": "hoenn"
    },
    {
      "name": "Détourner Way",
      "slug": "detourner-way",
      "region": "kalos"
    },
    {
      "name": "Dewford Town",
      "slug": "dewford-town",
      "region": "hoenn"
    },
    {
      "name": "Diglett's Cave",
      "slug": "digletts-cave",
      "region": "kanto"
    },
    {
      "name": "Dilford Chamber",
      "slug": "dilford-chamber",
      "region": "kanto"
    },
    {
      "name": "Distortion World",
      "slug": "distortion-world",
      "region": "sinnoh"
    },
    {
      "name": "Dragon's Den",
      "slug": "dragons-den",
      "region": "johto"
    },
    {
      "name": "Dragonmark Chamber",
      "slug": "dragonmark-chamber",
      "region": "kalos"
    },
    {
      "name": "Dragonspiral Tower",
      "slug": "dragonspiral-tower",
      "region": "unova"
    },
    {
      "name": "Dreamyard",
      "slug": "dreamyard",
      "region": "unova"
    },
    {
      "name": "Driftveil City",
      "slug": "driftveil-city",
      "region": "unova"
    },
    {
      "name": "Driftveil Drawbridge",
      "slug": "driftveil-drawbridge",
      "region": "unova"
    },
    {
      "name": "Ecruteak City",
      "slug": "ecruteak-city",
      "region": "johto"
    },
    {
      "name": "Embedded Tower",
      "slug": "embedded-tower",
      "region": "johto"
    },
    {
      "name": "Entralink",
      "slug": "entralink",
      "region": "unova"
    },
    {
      "name": "Entree Forest",
      "slug": "entree-forest",
      "region": "unova"
    },
    {
      "name": "Eterna City",
      "slug": "eterna-city",
      "region": "sinnoh"
    },
    {
      "name": "Eterna Forest",
      "slug": "eterna-forest",
      "region": "sinnoh"
    },
    {
      "name": "Ever Grande City",
      "slug": "ever-grande-city",
      "region": "hoenn"
    },
    {
      "name": "Fabled Cave",
      "slug": "fabled-cave",
      "region": "hoenn"
    },
    {
      "name": "Fallarbor Town",
      "slug": "fallarbor-town",
      "region": "hoenn"
    },
    {
      "name": "Faraway Island",
      "slug": "faraway-island",
      "region": "hoenn"
    },
    {
      "name": "Faraway place",
      "slug": "unova-faraway-place",
      "region": "unova"
    },
    {
      "name": "Fiery Path",
      "slug": "fiery-path",
      "region": "hoenn"
    },
    {
      "name": "Fight Area",
      "slug": "fight-area",
      "region": "sinnoh"
    },
    {
      "name": "Five Island",
      "slug": "five-island",
      "region": "kanto"
    },
    {
      "name": "Five Isle Meadow",
      "slug": "five-isle-meadow",
      "region": "kanto"
    },
    {
      "name": "Floaroma Meadow",
      "slug": "floaroma-meadow",
      "region": "sinnoh"
    },
    {
      "name": "Floaroma Town",
      "slug": "floaroma-town",
      "region": "sinnoh"
    },
    {
      "name": "Floccesy Ranch",
      "slug": "floccesy-ranch",
      "region": "unova"
    },
    {
      "name": "Floccesy Town",
      "slug": "floccesy-town",
      "region": "unova"
    },
    {
      "name": "Flood Chamber",
      "slug": "flood-chamber",
      "region": "kalos"
    },
    {
      "name": "Flower Paradise",
      "slug": "flower-paradise",
      "region": "sinnoh"
    },
    {
      "name": "Flower Shop",
      "slug": "sinnoh-flower-shop",
      "region": "sinnoh"
    },
    {
      "name": "Footstep House",
      "slug": "footstep-house",
      "region": "sinnoh"
    },
    {
      "name": "Foreign Building",
      "slug": "sinnoh-foreign-building",
      "region": "sinnoh"
    },
    {
      "name": "Fortree City",
      "slug": "fortree-city",
      "region": "hoenn"
    },
    {
      "name": "Four Island",
      "slug": "four-island",
      "region": "kanto"
    },
    {
      "name": "Fourrage Road",
      "slug": "fourrage-road",
      "region": "kalos"
    },
    {
      "name": "Friend Safari",
      "slug": "friend-safari",
      "region": "kalos"
    },
    {
      "name": "Frontier Access",
      "slug": "frontier-access",
      "region": "johto"
    },
    {
      "name": "Frost Cavern",
      "slug": "frost-cavern",
      "region": "kalos"
    },
    {
      "name": "Fuchsia City",
      "slug": "fuchsia-city",
      "region": "kanto"
    },
    {
      "name": "Fuego Ironworks",
      "slug": "fuego-ironworks",
      "region": "sinnoh"
    },
    {
      "name": "Fullmoon Island",
      "slug": "fullmoon-island",
      "region": "sinnoh"
    },
    {
      "name": "Galactic HQ",
      "slug": "galactic-hq",
      "region": "sinnoh"
    },
    {
      "name": "Game Corner",
      "slug": "sinnoh-game-corner",
      "region": "sinnoh"
    },
    {
      "name": "Gear Station",
      "slug": "gear-station",
      "region": "unova"
    },
    {
      "name": "Geosenge Town",
      "slug": "geosenge-town",
      "region": "kalos"
    },
    {
      "name": "Giant Chasm",
      "slug": "giant-chasm",
      "region": "unova"
    },
    {
      "name": "Glacier Room",
      "slug": "glacier-room",
      "region": "unova"
    },
    {
      "name": "Glittering Cave",
      "slug": "glittering-cave",
      "region": "kalos"
    },
    {
      "name": "Global Terminal",
      "slug": "sinnoh-global-terminal",
      "region": "sinnoh"
    },
    {
      "name": "Gnarled Den",
      "slug": "gnarled-den",
      "region": "hoenn"
    },
    {
      "name": "Goldenrod City",
      "slug": "goldenrod-city",
      "region": "johto"
    },
    {
      "name": "Goldenrod Tunnel",
      "slug": "goldenrod-tunnel",
      "region": "johto"
    },
    {
      "name": "Grand Lake",
      "slug": "grand-lake",
      "region": "sinnoh"
    },
    {
      "name": "Grande Vallée Way",
      "slug": "grande-vallee-way",
      "region": "kalos"
    },
    {
      "name": "Granite Cave",
      "slug": "granite-cave",
      "region": "hoenn"
    },
    {
      "name": "Great Marsh",
      "slug": "great-marsh",
      "region": "sinnoh"
    },
    {
      "name": "Green Path",
      "slug": "green-path",
      "region": "kanto"
    },
    {
      "name": "GTS",
      "slug": "gts",
      "region": "sinnoh"
    },
    {
      "name": "Guidance Chamber",
      "slug": "guidance-chamber",
      "region": "unova"
    },
    {
      "name": "Hall of Origin",
      "slug": "sinnoh-hall-of-origin-1",
      "region": "sinnoh"
    },
    {
      "name": "Hall of Origin",
      "slug": "sinnoh-hall-of-origin-2",
      "region": "sinnoh"
    },
    {
      "name": "Hearthome City",
      "slug": "hearthome-city",
      "region": "sinnoh"
    },
    {
      "name": "Hidden Grotto",
      "slug": "hidden-grotto",
      "region": "unova"
    },
    {
      "name": "Hoenn Battle Frontier",
      "slug": "hoenn-battle-frontier",
      "region": "hoenn"
    },
    {
      "name": "Humilau City",
      "slug": "humilau-city",
      "region": "unova"
    },
    {
      "name": "Ice Path",
      "slug": "ice-path",
      "region": "johto"
    },
    {
      "name": "Iceberg Ruins",
      "slug": "iceberg-ruins",
      "region": "sinnoh"
    },
    {
      "name": "Icefall Cave",
      "slug": "icefall-cave",
      "region": "kanto"
    },
    {
      "name": "Icirrus City",
      "slug": "icirrus-city",
      "region": "unova"
    },
    {
      "name": "Ilex Forest",
      "slug": "ilex-forest",
      "region": "johto"
    },
    {
      "name": "Indigo Plateau",
      "slug": "indigo-plateau",
      "region": "kanto"
    },
    {
      "name": "Iron Island",
      "slug": "iron-island",
      "region": "sinnoh"
    },
    {
      "name": "Iron Room",
      "slug": "iron-room",
      "region": "unova"
    },
    {
      "name": "Iron Ruins",
      "slug": "iron-ruins",
      "region": "sinnoh"
    },
    {
      "name": "Ironworks Chamber",
      "slug": "ironworks-chamber",
      "region": "kalos"
    },
    {
      "name": "Island Cave",
      "slug": "island-cave",
      "region": "hoenn"
    },
    {
      "name": "Jagged Pass",
      "slug": "jagged-pass",
      "region": "hoenn"
    },
    {
      "name": "Johto Safari Zone",
      "slug": "johto-safari-zone",
      "region": "johto"
    },
    {
      "name": "Join Avenue",
      "slug": "join-avenue",
      "region": "unova"
    },
    {
      "name": "Jubilife City",
      "slug": "jubilife-city",
      "region": "sinnoh"
    },
    {
      "name": "Jubilife TV",
      "slug": "jubilife-tv",
      "region": "sinnoh"
    },
    {
      "name": "Kalos (Roaming)",
      "slug": "roaming-kalos",
      "region": "kalos"
    },
    {
      "name": "Kalos Power Plant",
      "slug": "kalos-power-plant",
      "region": "kalos"
    },
    {
      "name": "Kiloude City",
      "slug": "kiloude-city",
      "region": "kalos"
    },
    {
      "name": "Kiloude Station",
      "slug": "kiloude-station",
      "region": "kalos"
    },
    {
      "name": "Kindle Road",
      "slug": "kindle-road",
      "region": "kanto"
    },
    {
      "name": "Lacunosa Town",
      "slug": "lacunosa-town",
      "region": "unova"
    },
    {
      "name": "Lake Acuity",
      "slug": "lake-acuity",
      "region": "sinnoh"
    },
    {
      "name": "Lake of Rage",
      "slug": "lake-of-rage",
      "region": "johto"
    },
    {
      "name": "Lake Valor",
      "slug": "lake-valor",
      "region": "sinnoh"
    },
    {
      "name": "Lake Verity",
      "slug": "lake-verity",
      "region": "sinnoh"
    },
    {
      "name": "Lavaridge Town",
      "slug": "lavaridge-town",
      "region": "hoenn"
    },
    {
      "name": "Lavender Town",
      "slug": "lavender-town",
      "region": "kanto"
    },
    {
      "name": "Laverre City",
      "slug": "laverre-city",
      "region": "kalos"
    },
    {
      "name": "Laverre Gate",
      "slug": "laverre-gate",
      "region": "kalos"
    },
    {
      "name": "Laverre Nature Trail",
      "slug": "laverre-nature-trail",
      "region": "kalos"
    },
    {
      "name": "Lentimas Town",
      "slug": "lentimas-town",
      "region": "unova"
    },
    {
      "name": "Liberty Garden",
      "slug": "liberty-garden",
      "region": "unova"
    },
    {
      "name": "Lighthouse",
      "slug": "johto-lighthouse",
      "region": "johto"
    },
    {
      "name": "Lilycove City",
      "slug": "lilycove-city",
      "region": "hoenn"
    },
    {
      "name": "Liptoo Chamber",
      "slug": "liptoo-chamber",
      "region": "kanto"
    },
    {
      "name": "Littleroot Town",
      "slug": "littleroot-town",
      "region": "hoenn"
    },
    {
      "name": "Lost Cave",
      "slug": "lost-cave",
      "region": "kanto"
    },
    {
      "name": "Lost Hotel",
      "slug": "lost-hotel",
      "region": "kalos"
    },
    {
      "name": "Lost Tower",
      "slug": "lost-tower",
      "region": "sinnoh"
    },
    {
      "name": "Lostlorn Forest",
      "slug": "lostlorn-forest",
      "region": "unova"
    },
    {
      "name": "Lumiose Badlands",
      "slug": "lumiose-badlands",
      "region": "kalos"
    },
    {
      "name": "Lumiose City",
      "slug": "lumiose-city",
      "region": "kalos"
    },
    {
      "name": "Lumiose Gate",
      "slug": "lumiose-gate",
      "region": "kalos"
    },
    {
      "name": "Lumiose Station",
      "slug": "lumiose-station",
      "region": "kalos"
    },
    {
      "name": "Lysandre Labs",
      "slug": "lysandre-labs",
      "region": "kalos"
    },
    {
      "name": "Magma Hideout",
      "slug": "magma-hideout",
      "region": "hoenn"
    },
    {
      "name": "Mahogany Town",
      "slug": "mahogany-town",
      "region": "johto"
    },
    {
      "name": "Mamoswine Road",
      "slug": "mamoswine-road",
      "region": "kalos"
    },
    {
      "name": "Maniac Tunnel",
      "slug": "maniac-tunnel",
      "region": "sinnoh"
    },
    {
      "name": "Marine Cave",
      "slug": "marine-cave",
      "region": "hoenn"
    },
    {
      "name": "Marine Tube",
      "slug": "marine-tube",
      "region": "unova"
    },
    {
      "name": "Marvelous Bridge",
      "slug": "marvelous-bridge",
      "region": "unova"
    },
    {
      "name": "Mauville City",
      "slug": "mauville-city",
      "region": "hoenn"
    },
    {
      "name": "Medal Secretariat",
      "slug": "medal-secretariat",
      "region": "unova"
    },
    {
      "name": "Mélancolie Path",
      "slug": "melancolie-path",
      "region": "kalos"
    },
    {
      "name": "Memorial Pillar",
      "slug": "memorial-pillar",
      "region": "kanto"
    },
    {
      "name": "Menhir Trail",
      "slug": "menhir-trail",
      "region": "kalos"
    },
    {
      "name": "Meteor Falls",
      "slug": "meteor-falls",
      "region": "hoenn"
    },
    {
      "name": "Mining Museum",
      "slug": "mining-museum",
      "region": "sinnoh"
    },
    {
      "name": "Mirage Cave",
      "slug": "mirage-cave",
      "region": "hoenn"
    },
    {
      "name": "Mirage Forest",
      "slug": "mirage-forest",
      "region": "hoenn"
    },
    {
      "name": "Mirage Island",
      "slug": "mirage-island",
      "region": "hoenn"
    },
    {
      "name": "Mirage Mountain",
      "slug": "mirage-mountain",
      "region": "hoenn"
    },
    {
      "name": "Mirage Tower",
      "slug": "mirage-tower",
      "region": "hoenn"
    },
    {
      "name": "Miroir Way",
      "slug": "miroir-way",
      "region": "kalos"
    },
    {
      "name": "Mistralton Cave",
      "slug": "mistralton-cave",
      "region": "unova"
    },
    {
      "name": "Mistralton City",
      "slug": "mistralton-city",
      "region": "unova"
    },
    {
      "name": "Monean Chamber",
      "slug": "monean-chamber",
      "region": "kanto"
    },
    {
      "name": "Moor of Icirrus",
      "slug": "moor-of-icirrus",
      "region": "unova"
    },
    {
      "name": "Mossdeep City",
      "slug": "mossdeep-city",
      "region": "hoenn"
    },
    {
      "name": "Mossdeep Space Center",
      "slug": "mossdeep-space-center",
      "region": "hoenn"
    },
    {
      "name": "Mt. Chimney",
      "slug": "mt-chimney",
      "region": "hoenn"
    },
    {
      "name": "Mt. Coronet",
      "slug": "mt-coronet",
      "region": "sinnoh"
    },
    {
      "name": "Mt. Ember",
      "slug": "mt-ember",
      "region": "kanto"
    },
    {
      "name": "Mt. Moon",
      "slug": "mt-moon",
      "region": "kanto"
    },
    {
      "name": "Mt. Mortar",
      "slug": "mt-mortar",
      "region": "johto"
    },
    {
      "name": "Mt. Pyre",
      "slug": "mt-pyre",
      "region": "hoenn"
    },
    {
      "name": "Mt. Silver",
      "slug": "mt-silver",
      "region": "johto"
    },
    {
      "name": "Mt. Silver Cave",
      "slug": "mt-silver-cave",
      "region": "johto"
    },
    {
      "name": "Muraille Coast",
      "slug": "muraille-coast",
      "region": "kalos"
    },
    {
      "name": "Musical Theater",
      "slug": "musical-theater",
      "region": "unova"
    },
    {
      "name": "Mystery Zone",
      "slug": "unova-mystery-zone",
      "region": "unova"
    },
    {
      "name": "N's Castle",
      "slug": "ns-castle",
      "region": "unova"
    },
    {
      "name": "Nacrene City",
      "slug": "nacrene-city",
      "region": "unova"
    },
    {
      "name": "Nacrene Gate",
      "slug": "nacrene-gate",
      "region": "unova"
    },
    {
      "name": "Nameless Cavern",
      "slug": "nameless-cavern",
      "region": "hoenn"
    },
    {
      "name": "National Park",
      "slug": "national-park",
      "region": "johto"
    },
    {
      "name": "Nature Sanctuary",
      "slug": "nature-sanctuary",
      "region": "unova"
    },
    {
      "name": "Navel Rock",
      "slug": "navel-rock",
      "region": "kanto"
    },
    {
      "name": "New Bark Town",
      "slug": "new-bark-town",
      "region": "johto"
    },
    {
      "name": "New Mauville",
      "slug": "new-mauville",
      "region": "hoenn"
    },
    {
      "name": "Newmoon Island",
      "slug": "newmoon-island",
      "region": "sinnoh"
    },
    {
      "name": "Nimbasa City",
      "slug": "nimbasa-city",
      "region": "unova"
    },
    {
      "name": "Nimbasa Gate",
      "slug": "nimbasa-gate",
      "region": "unova"
    },
    {
      "name": "Nuvema Town",
      "slug": "nuvema-town",
      "region": "unova"
    },
    {
      "name": "Old Chateau",
      "slug": "old-chateau",
      "region": "sinnoh"
    },
    {
      "name": "Oldale Town",
      "slug": "oldale-town",
      "region": "hoenn"
    },
    {
      "name": "Olivine City",
      "slug": "olivine-city",
      "region": "johto"
    },
    {
      "name": "One Island",
      "slug": "one-island",
      "region": "kanto"
    },
    {
      "name": "Opelucid City",
      "slug": "opelucid-city",
      "region": "unova"
    },
    {
      "name": "Opelucid Gate",
      "slug": "opelucid-gate",
      "region": "unova"
    },
    {
      "name": "Oreburgh City",
      "slug": "oreburgh-city",
      "region": "sinnoh"
    },
    {
      "name": "Oreburgh Gate",
      "slug": "oreburgh-gate",
      "region": "sinnoh"
    },
    {
      "name": "Oreburgh Mine",
      "slug": "oreburgh-mine",
      "region": "sinnoh"
    },
    {
      "name": "Outcast Island",
      "slug": "outcast-island",
      "region": "kanto"
    },
    {
      "name": "Ouvert Way",
      "slug": "ouvert-way",
      "region": "kalos"
    },
    {
      "name": "P2 Laboratory",
      "slug": "p2-laboratory",
      "region": "unova"
    },
    {
      "name": "Pacifidlog Town",
      "slug": "pacifidlog-town",
      "region": "hoenn"
    },
    {
      "name": "Pal Park",
      "slug": "pal-park",
      "region": "sinnoh"
    },
    {
      "name": "Palais Lane",
      "slug": "palais-lane",
      "region": "kalos"
    },
    {
      "name": "Pallet Town",
      "slug": "pallet-town",
      "region": "kanto"
    },
    {
      "name": "Parfum Palace",
      "slug": "parfum-palace",
      "region": "kalos"
    },
    {
      "name": "Parterre Way",
      "slug": "parterre-way",
      "region": "kalos"
    },
    {
      "name": "Pastoria City",
      "slug": "pastoria-city",
      "region": "sinnoh"
    },
    {
      "name": "Pathless Plain",
      "slug": "pathless-plain",
      "region": "hoenn"
    },
    {
      "name": "Pattern Bush",
      "slug": "pattern-bush",
      "region": "kanto"
    },
    {
      "name": "Petalburg City",
      "slug": "petalburg-city",
      "region": "hoenn"
    },
    {
      "name": "Petalburg Woods",
      "slug": "petalburg-woods",
      "region": "hoenn"
    },
    {
      "name": "Pewter City",
      "slug": "pewter-city",
      "region": "kanto"
    },
    {
      "name": "Pinwheel Forest",
      "slug": "pinwheel-forest",
      "region": "unova"
    },
    {
      "name": "Plasma Frigate",
      "slug": "plasma-frigate",
      "region": "unova"
    },
    {
      "name": "Pledge Grove",
      "slug": "pledge-grove",
      "region": "unova"
    },
    {
      "name": "Poffin House",
      "slug": "poffin-house",
      "region": "sinnoh"
    },
    {
      "name": "Poké Ball Factory",
      "slug": "poke-ball-factory",
      "region": "kalos"
    },
    {
      "name": "Poké Transfer Lab",
      "slug": "poke-transfer-lab",
      "region": "unova"
    },
    {
      "name": "Pokéathlon Dome",
      "slug": "pokeathlon-dome",
      "region": "johto"
    },
    {
      "name": "Pokémon Day Care",
      "slug": "pokemon-day-care",
      "region": "sinnoh"
    },
    {
      "name": "Pokémon League",
      "slug": "sinnoh-pokemon-league",
      "region": "sinnoh"
    },
    {
      "name": "Pokémon League",
      "slug": "unova-pokemon-league",
      "region": "unova"
    },
    {
      "name": "Pokémon League",
      "slug": "kalos-pokemon-league",
      "region": "kalos"
    },
    {
      "name": "Pokémon League",
      "slug": "hoenn-pokemon-league",
      "region": "hoenn"
    },
    {
      "name": "Pokémon League Gate",
      "slug": "pokemon-league-gate",
      "region": "kalos"
    },
    {
      "name": "Pokémon Mansion",
      "slug": "pokemon-mansion",
      "region": "kanto"
    },
    {
      "name": "Pokémon Tower",
      "slug": "pokemon-tower",
      "region": "kanto"
    },
    {
      "name": "Pokémon Village",
      "slug": "pokemon-village",
      "region": "kalos"
    },
    {
      "name": "PokéStar Studios",
      "slug": "pokestar-studios",
      "region": "unova"
    },
    {
      "name": "Pokétch Co.",
      "slug": "poketch-co",
      "region": "sinnoh"
    },
    {
      "name": "Pokéwalker",
      "slug": "pokewalker",
      "region": "johto"
    },
    {
      "name": "Power Plant",
      "slug": "power-plant",
      "region": "kanto"
    },
    {
      "name": "Prism Tower",
      "slug": "prism-tower",
      "region": "kalos"
    },
    {
      "name": "Radiant Chamber",
      "slug": "radiant-chamber",
      "region": "kalos"
    },
    {
      "name": "Radio Tower",
      "slug": "radio-tower",
      "region": "johto"
    },
    {
      "name": "Ravaged Path",
      "slug": "ravaged-path",
      "region": "sinnoh"
    },
    {
      "name": "Reflection Cave",
      "slug": "reflection-cave",
      "region": "kalos"
    },
    {
      "name": "Relic Castle",
      "slug": "relic-castle",
      "region": "unova"
    },
    {
      "name": "Relic Passage",
      "slug": "relic-passage",
      "region": "unova"
    },
    {
      "name": "Resort Area",
      "slug": "resort-area",
      "region": "sinnoh"
    },
    {
      "name": "Resort Gorgeous",
      "slug": "resort-gorgeous",
      "region": "kanto"
    },
    {
      "name": "Restaurant",
      "slug": "sinnoh-restaurant",
      "region": "sinnoh"
    },
    {
      "name": "Reversal Mountain",
      "slug": "reversal-mountain",
      "region": "unova"
    },
    {
      "name": "Rixy Chamber",
      "slug": "rixy-chamber",
      "region": "kanto"
    },
    {
      "name": "Roaming Hoenn",
      "slug": "roaming-hoenn",
      "region": "hoenn"
    },
    {
      "name": "Roaming Johto",
      "slug": "roaming-johto",
      "region": "johto"
    },
    {
      "name": "Roaming Kanto",
      "slug": "roaming-kanto",
      "region": "kanto"
    },
    {
      "name": "Roaming Sinnoh",
      "slug": "roaming-sinnoh",
      "region": "sinnoh"
    },
    {
      "name": "Rock Peak Ruins",
      "slug": "rock-peak-ruins",
      "region": "sinnoh"
    },
    {
      "name": "Rock Tunnel",
      "slug": "rock-tunnel",
      "region": "kanto"
    },
    {
      "name": "Rocky Mountain Room",
      "slug": "rocky-mountain-room",
      "region": "unova"
    },
    {
      "name": "ROTOM's Room",
      "slug": "rotoms-room",
      "region": "sinnoh"
    },
    {
      "name": "Route 1",
      "slug": "kanto-route-1",
      "region": "kanto"
    },
    {
      "name": "Route 1",
      "slug": "unova-route-1",
      "region": "unova"
    },
    {
      "name": "Route 1",
      "slug": "kalos-route-1",
      "region": "kalos"
    },
    {
      "name": "Route 10",
      "slug": "kanto-route-10",
      "region": "kanto"
    },
    {
      "name": "Route 10",
      "slug": "unova-route-10",
      "region": "unova"
    },
    {
      "name": "Route 10",
      "slug": "kalos-route-10",
      "region": "kalos"
    },
    {
      "name": "Route 101",
      "slug": "hoenn-route-101",
      "region": "hoenn"
    },
    {
      "name": "Route 102",
      "slug": "hoenn-route-102",
      "region": "hoenn"
    },
    {
      "name": "Route 103",
      "slug": "hoenn-route-103",
      "region": "hoenn"
    },
    {
      "name": "Route 104",
      "slug": "hoenn-route-104",
      "region": "hoenn"
    },
    {
      "name": "Route 105",
      "slug": "hoenn-route-105",
      "region": "hoenn"
    },
    {
      "name": "Route 106",
      "slug": "hoenn-route-106",
      "region": "hoenn"
    },
    {
      "name": "Route 107",
      "slug": "hoenn-route-107",
      "region": "hoenn"
    },
    {
      "name": "Route 108",
      "slug": "hoenn-route-108",
      "region": "hoenn"
    },
    {
      "name": "Route 109",
      "slug": "hoenn-route-109",
      "region": "hoenn"
    },
    {
      "name": "Route 11",
      "slug": "kanto-route-11",
      "region": "kanto"
    },
    {
      "name": "Route 11",
      "slug": "unova-route-11",
      "region": "unova"
    },
    {
      "name": "Route 11",
      "slug": "kalos-route-11",
      "region": "kalos"
    },
    {
      "name": "Route 110",
      "slug": "hoenn-route-110",
      "region": "hoenn"
    },
    {
      "name": "Route 111",
      "slug": "hoenn-route-111",
      "region": "hoenn"
    },
    {
      "name": "Route 112",
      "slug": "hoenn-route-112",
      "region": "hoenn"
    },
    {
      "name": "Route 113",
      "slug": "hoenn-route-113",
      "region": "hoenn"
    },
    {
      "name": "Route 114",
      "slug": "hoenn-route-114",
      "region": "hoenn"
    },
    {
      "name": "Route 115",
      "slug": "hoenn-route-115",
      "region": "hoenn"
    },
    {
      "name": "Route 116",
      "slug": "hoenn-route-116",
      "region": "hoenn"
    },
    {
      "name": "Route 117",
      "slug": "hoenn-route-117",
      "region": "hoenn"
    },
    {
      "name": "Route 118",
      "slug": "hoenn-route-118",
      "region": "hoenn"
    },
    {
      "name": "Route 119",
      "slug": "hoenn-route-119",
      "region": "hoenn"
    },
    {
      "name": "Route 12",
      "slug": "kanto-route-12",
      "region": "kanto"
    },
    {
      "name": "Route 12",
      "slug": "unova-route-12",
      "region": "unova"
    },
    {
      "name": "Route 12",
      "slug": "kalos-route-12",
      "region": "kalos"
    },
    {
      "name": "Route 120",
      "slug": "hoenn-route-120",
      "region": "hoenn"
    },
    {
      "name": "Route 121",
      "slug": "hoenn-route-121",
      "region": "hoenn"
    },
    {
      "name": "Route 122",
      "slug": "hoenn-route-122",
      "region": "hoenn"
    },
    {
      "name": "Route 123",
      "slug": "hoenn-route-123",
      "region": "hoenn"
    },
    {
      "name": "Route 124",
      "slug": "hoenn-route-124",
      "region": "hoenn"
    },
    {
      "name": "Route 125",
      "slug": "hoenn-route-125",
      "region": "hoenn"
    },
    {
      "name": "Route 126",
      "slug": "hoenn-route-126",
      "region": "hoenn"
    },
    {
      "name": "Route 127",
      "slug": "hoenn-route-127",
      "region": "hoenn"
    },
    {
      "name": "Route 128",
      "slug": "hoenn-route-128",
      "region": "hoenn"
    },
    {
      "name": "Route 129",
      "slug": "hoenn-route-129",
      "region": "hoenn"
    },
    {
      "name": "Route 13",
      "slug": "kanto-route-13",
      "region": "kanto"
    },
    {
      "name": "Route 13",
      "slug": "unova-route-13",
      "region": "unova"
    },
    {
      "name": "Route 13",
      "slug": "kalos-route-13",
      "region": "kalos"
    },
    {
      "name": "Route 130",
      "slug": "hoenn-route-130",
      "region": "hoenn"
    },
    {
      "name": "Route 131",
      "slug": "hoenn-route-131",
      "region": "hoenn"
    },
    {
      "name": "Route 132",
      "slug": "hoenn-route-132",
      "region": "hoenn"
    },
    {
      "name": "Route 133",
      "slug": "hoenn-route-133",
      "region": "hoenn"
    },
    {
      "name": "Route 134",
      "slug": "hoenn-route-134",
      "region": "hoenn"
    },
    {
      "name": "Route 14",
      "slug": "kanto-route-14",
      "region": "kanto"
    },
    {
      "name": "Route 14",
      "slug": "unova-route-14",
      "region": "unova"
    },
    {
      "name": "Route 14",
      "slug": "kalos-route-14",
      "region": "kalos"
    },
    {
      "name": "Route 15",
      "slug": "kanto-route-15",
      "region": "kanto"
    },
    {
      "name": "Route 15",
      "slug": "unova-route-15",
      "region": "unova"
    },
    {
      "name": "Route 15",
      "slug": "kalos-route-15",
      "region": "kalos"
    },
    {
      "name": "Route 16",
      "slug": "kanto-route-16",
      "region": "kanto"
    },
    {
      "name": "Route 16",
      "slug": "unova-route-16",
      "region": "unova"
    },
    {
      "name": "Route 16",
      "slug": "kalos-route-16",
      "region": "kalos"
    },
    {
      "name": "Route 17",
      "slug": "kanto-route-17",
      "region": "kanto"
    },
    {
      "name": "Route 17",
      "slug": "unova-route-17",
      "region": "unova"
    },
    {
      "name": "Route 17",
      "slug": "kalos-route-17",
      "region": "kalos"
    },
    {
      "name": "Route 18",
      "slug": "kanto-route-18",
      "region": "kanto"
    },
    {
      "name": "Route 18",
      "slug": "unova-route-18",
      "region": "unova"
    },
    {
      "name": "Route 18",
      "slug": "kalos-route-18",
      "region": "kalos"
    },
    {
      "name": "Route 19",
      "slug": "unova-route-19",
      "region": "unova"
    },
    {
      "name": "Route 19",
      "slug": "kalos-route-19",
      "region": "kalos"
    },
    {
      "name": "Route 2",
      "slug": "kanto-route-2",
      "region": "kanto"
    },
    {
      "name": "Route 2",
      "slug": "unova-route-2",
      "region": "unova"
    },
    {
      "name": "Route 2",
      "slug": "kalos-route-2",
      "region": "kalos"
    },
    {
      "name": "Route 20",
      "slug": "unova-route-20",
      "region": "unova"
    },
    {
      "name": "Route 20",
      "slug": "kalos-route-20",
      "region": "kalos"
    },
    {
      "name": "Route 201",
      "slug": "sinnoh-route-201",
      "region": "sinnoh"
    },
    {
      "name": "Route 202",
      "slug": "sinnoh-route-202",
      "region": "sinnoh"
    },
    {
      "name": "Route 203",
      "slug": "sinnoh-route-203",
      "region": "sinnoh"
    },
    {
      "name": "Route 204",
      "slug": "sinnoh-route-204",
      "region": "sinnoh"
    },
    {
      "name": "Route 205",
      "slug": "sinnoh-route-205",
      "region": "sinnoh"
    },
    {
      "name": "Route 206",
      "slug": "sinnoh-route-206",
      "region": "sinnoh"
    },
    {
      "name": "Route 207",
      "slug": "sinnoh-route-207",
      "region": "sinnoh"
    },
    {
      "name": "Route 208",
      "slug": "sinnoh-route-208",
      "region": "sinnoh"
    },
    {
      "name": "Route 209",
      "slug": "sinnoh-route-209",
      "region": "sinnoh"
    },
    {
      "name": "Route 21",
      "slug": "unova-route-21",
      "region": "unova"
    },
    {
      "name": "Route 21",
      "slug": "kalos-route-21",
      "region": "kalos"
    },
    {
      "name": "Route 210",
      "slug": "sinnoh-route-210",
      "region": "sinnoh"
    },
    {
      "name": "Route 211",
      "slug": "sinnoh-route-211",
      "region": "sinnoh"
    },
    {
      "name": "Route 212",
      "slug": "sinnoh-route-212",
      "region": "sinnoh"
    },
    {
      "name": "Route 213",
      "slug": "sinnoh-route-213",
      "region": "sinnoh"
    },
    {
      "name": "Route 214",
      "slug": "sinnoh-route-214",
      "region": "sinnoh"
    },
    {
      "name": "Route 215",
      "slug": "sinnoh-route-215",
      "region": "sinnoh"
    },
    {
      "name": "Route 216",
      "slug": "sinnoh-route-216",
      "region": "sinnoh"
    },
    {
      "name": "Route 217",
      "slug": "sinnoh-route-217",
      "region": "sinnoh"
    },
    {
      "name": "Route 218",
      "slug": "sinnoh-route-218",
      "region": "sinnoh"
    },
    {
      "name": "Route 219",
      "slug": "sinnoh-route-219",
      "region": "sinnoh"
    },
    {
      "name": "Route 22",
      "slug": "kanto-route-22",
      "region": "kanto"
    },
    {
      "name": "Route 22",
      "slug": "unova-route-22",
      "region": "unova"
    },
    {
      "name": "Route 22",
      "slug": "kalos-route-22",
      "region": "kalos"
    },
    {
      "name": "Route 221",
      "slug": "sinnoh-route-221",
      "region": "sinnoh"
    },
    {
      "name": "Route 222",
      "slug": "sinnoh-route-222",
      "region": "sinnoh"
    },
    {
      "name": "Route 224",
      "slug": "sinnoh-route-224",
      "region": "sinnoh"
    },
    {
      "name": "Route 225",
      "slug": "sinnoh-route-225",
      "region": "sinnoh"
    },
    {
      "name": "Route 227",
      "slug": "sinnoh-route-227",
      "region": "sinnoh"
    },
    {
      "name": "Route 228",
      "slug": "sinnoh-route-228",
      "region": "sinnoh"
    },
    {
      "name": "Route 229",
      "slug": "sinnoh-route-229",
      "region": "sinnoh"
    },
    {
      "name": "Route 23",
      "slug": "kanto-route-23",
      "region": "kanto"
    },
    {
      "name": "Route 23",
      "slug": "unova-route-23",
      "region": "unova"
    },
    {
      "name": "Route 24",
      "slug": "kanto-route-24",
      "region": "kanto"
    },
    {
      "name": "Route 25",
      "slug": "kanto-route-25",
      "region": "kanto"
    },
    {
      "name": "Route 26",
      "slug": "kanto-route-26",
      "region": "kanto"
    },
    {
      "name": "Route 27",
      "slug": "kanto-route-27",
      "region": "kanto"
    },
    {
      "name": "Route 28",
      "slug": "kanto-route-28",
      "region": "kanto"
    },
    {
      "name": "Route 29",
      "slug": "johto-route-29",
      "region": "johto"
    },
    {
      "name": "Route 3",
      "slug": "kanto-route-3",
      "region": "kanto"
    },
    {
      "name": "Route 3",
      "slug": "unova-route-3",
      "region": "unova"
    },
    {
      "name": "Route 3",
      "slug": "kalos-route-3",
      "region": "kalos"
    },
    {
      "name": "Route 30",
      "slug": "johto-route-30",
      "region": "johto"
    },
    {
      "name": "Route 31",
      "slug": "johto-route-31",
      "region": "johto"
    },
    {
      "name": "Route 32",
      "slug": "johto-route-32",
      "region": "johto"
    },
    {
      "name": "Route 33",
      "slug": "johto-route-33",
      "region": "johto"
    },
    {
      "name": "Route 34",
      "slug": "johto-route-34",
      "region": "johto"
    },
    {
      "name": "Route 35",
      "slug": "johto-route-35",
      "region": "johto"
    },
    {
      "name": "Route 36",
      "slug": "johto-route-36",
      "region": "johto"
    },
    {
      "name": "Route 37",
      "slug": "johto-route-37",
      "region": "johto"
    },
    {
      "name": "Route 38",
      "slug": "johto-route-38",
      "region": "johto"
    },
    {
      "name": "Route 39",
      "slug": "johto-route-39",
      "region": "johto"
    },
    {
      "name": "Route 4",
      "slug": "kanto-route-4",
      "region": "kanto"
    },
    {
      "name": "Route 4",
      "slug": "unova-route-4",
      "region": "unova"
    },
    {
      "name": "Route 4",
      "slug": "kalos-route-4",
      "region": "kalos"
    },
    {
      "name": "Route 42",
      "slug": "johto-route-42",
      "region": "johto"
    },
    {
      "name": "Route 43",
      "slug": "johto-route-43",
      "region": "johto"
    },
    {
      "name": "Route 44",
      "slug": "johto-route-44",
      "region": "johto"
    },
    {
      "name": "Route 45",
      "slug": "johto-route-45",
      "region": "johto"
    },
    {
      "name": "Route 46",
      "slug": "johto-route-46",
      "region": "johto"
    },
    {
      "name": "Route 47",
      "slug": "johto-route-47",
      "region": "johto"
    },
    {
      "name": "Route 48",
      "slug": "johto-route-48",
      "region": "johto"
    },
    {
      "name": "Route 5",
      "slug": "kanto-route-5",
      "region": "kanto"
    },
    {
      "name": "Route 5",
      "slug": "unova-route-5",
      "region": "unova"
    },
    {
      "name": "Route 5",
      "slug": "kalos-route-5",
      "region": "kalos"
    },
    {
      "name": "Route 6",
      "slug": "kanto-route-6",
      "region": "kanto"
    },
    {
      "name": "Route 6",
      "slug": "unova-route-6",
      "region": "unova"
    },
    {
      "name": "Route 6",
      "slug": "kalos-route-6",
      "region": "kalos"
    },
    {
      "name": "Route 7",
      "slug": "kanto-route-7",
      "region": "kanto"
    },
    {
      "name": "Route 7",
      "slug": "unova-route-7",
      "region": "unova"
    },
    {
      "name": "Route 7",
      "slug": "kalos-route-7",
      "region": "kalos"
    },
    {
      "name": "Route 8",
      "slug": "kanto-route-8",
      "region": "kanto"
    },
    {
      "name": "Route 8",
      "slug": "unova-route-8",
      "region": "unova"
    },
    {
      "name": "Route 8",
      "slug": "kalos-route-8",
      "region": "kalos"
    },
    {
      "name": "Route 9",
      "slug": "kanto-route-9",
      "region": "kanto"
    },
    {
      "name": "Route 9",
      "slug": "unova-route-9",
      "region": "unova"
    },
    {
      "name": "Route 9",
      "slug": "kalos-route-9",
      "region": "kalos"
    },
    {
      "name": "Route Gate",
      "slug": "route-gate",
      "region": "unova"
    },
    {
      "name": "Royal Unova",
      "slug": "royal-unova",
      "region": "unova"
    },
    {
      "name": "Ruin Maniac Cave",
      "slug": "ruin-maniac-cave",
      "region": "sinnoh"
    },
    {
      "name": "Ruin Valley",
      "slug": "ruin-valley",
      "region": "kanto"
    },
    {
      "name": "Ruins of Alph",
      "slug": "ruins-of-alph",
      "region": "johto"
    },
    {
      "name": "Rumination Field",
      "slug": "rumination-field",
      "region": "unova"
    },
    {
      "name": "Rustboro City",
      "slug": "rustboro-city",
      "region": "hoenn"
    },
    {
      "name": "Rusturf Tunnel",
      "slug": "rusturf-tunnel",
      "region": "hoenn"
    },
    {
      "name": "S.S. Anne",
      "slug": "ss-anne",
      "region": "kanto"
    },
    {
      "name": "S.S. Aqua",
      "slug": "ss-aqua",
      "region": "johto"
    },
    {
      "name": "S.S. Tidal",
      "slug": "ss-tidal",
      "region": "hoenn"
    },
    {
      "name": "Safari Zone",
      "slug": "kanto-safari-zone",
      "region": "kanto"
    },
    {
      "name": "Safari Zone",
      "slug": "hoenn-safari-zone",
      "region": "hoenn"
    },
    {
      "name": "Safari Zone Gate",
      "slug": "safari-zone-gate",
      "region": "johto"
    },
    {
      "name": "Saffron City",
      "slug": "saffron-city",
      "region": "kanto"
    },
    {
      "name": "Sandgem Town",
      "slug": "sandgem-town",
      "region": "sinnoh"
    },
    {
      "name": "Santalune City",
      "slug": "santalune-city",
      "region": "kalos"
    },
    {
      "name": "Santalune Forest",
      "slug": "santalune-forest",
      "region": "kalos"
    },
    {
      "name": "Scorched Slab",
      "slug": "scorched-slab",
      "region": "hoenn"
    },
    {
      "name": "Scufib Chamber",
      "slug": "scufib-chamber",
      "region": "kanto"
    },
    {
      "name": "Sea Mauville",
      "slug": "sea-mauville",
      "region": "hoenn"
    },
    {
      "name": "Sea Route 19",
      "slug": "kanto-sea-route-19",
      "region": "kanto"
    },
    {
      "name": "Sea Route 20",
      "slug": "kanto-sea-route-20",
      "region": "kanto"
    },
    {
      "name": "Sea Route 21",
      "slug": "kanto-sea-route-21",
      "region": "kanto"
    },
    {
      "name": "Sea Route 220",
      "slug": "sinnoh-sea-route-220",
      "region": "sinnoh"
    },
    {
      "name": "Sea Route 223",
      "slug": "sinnoh-sea-route-223",
      "region": "sinnoh"
    },
    {
      "name": "Sea Route 226",
      "slug": "sinnoh-sea-route-226",
      "region": "sinnoh"
    },
    {
      "name": "Sea Route 230",
      "slug": "sinnoh-sea-route-230",
      "region": "sinnoh"
    },
    {
      "name": "Sea Route 40",
      "slug": "johto-sea-route-40",
      "region": "johto"
    },
    {
      "name": "Sea Route 41",
      "slug": "johto-sea-route-41",
      "region": "johto"
    },
    {
      "name": "Sea Spirit’s Den",
      "slug": "sea-spirits-den",
      "region": "kalos"
    },
    {
      "name": "Seabreak Path",
      "slug": "seabreak-path",
      "region": "sinnoh"
    },
    {
      "name": "Seafloor Cavern",
      "slug": "seafloor-cavern",
      "region": "hoenn"
    },
    {
      "name": "Seafoam Islands",
      "slug": "seafoam-islands",
      "region": "kanto"
    },
    {
      "name": "Sealed Chamber",
      "slug": "sealed-chamber",
      "region": "hoenn"
    },
    {
      "name": "Seaside Cave",
      "slug": "seaside-cave",
      "region": "unova"
    },
    {
      "name": "Secret Base",
      "slug": "secret-base",
      "region": "hoenn"
    },
    {
      "name": "Secret Islet",
      "slug": "secret-islet",
      "region": "hoenn"
    },
    {
      "name": "Secret Meadow",
      "slug": "secret-meadow",
      "region": "hoenn"
    },
    {
      "name": "Secret Shore",
      "slug": "secret-shore",
      "region": "hoenn"
    },
    {
      "name": "Sendoff Spring",
      "slug": "sendoff-spring",
      "region": "sinnoh"
    },
    {
      "name": "Sevault Canyon",
      "slug": "sevault-canyon",
      "region": "kanto"
    },
    {
      "name": "Seven Island",
      "slug": "seven-island",
      "region": "kanto"
    },
    {
      "name": "Shabboneau Castle",
      "slug": "shabboneau-castle",
      "region": "kalos"
    },
    {
      "name": "Shalour City",
      "slug": "shalour-city",
      "region": "kalos"
    },
    {
      "name": "Shalour Gate",
      "slug": "shalour-gate",
      "region": "kalos"
    },
    {
      "name": "Shoal Cave",
      "slug": "shoal-cave",
      "region": "hoenn"
    },
    {
      "name": "Shopping Mall",
      "slug": "unova-shopping-mall",
      "region": "unova"
    },
    {
      "name": "Sinjoh Ruins",
      "slug": "sinjoh-ruins",
      "region": "johto"
    },
    {
      "name": "Six Island",
      "slug": "six-island",
      "region": "kanto"
    },
    {
      "name": "Sky Pillar",
      "slug": "sky-pillar",
      "region": "hoenn"
    },
    {
      "name": "Skyarrow Bridge",
      "slug": "skyarrow-bridge",
      "region": "unova"
    },
    {
      "name": "Slateport City",
      "slug": "slateport-city",
      "region": "hoenn"
    },
    {
      "name": "Slowpoke Well",
      "slug": "slowpoke-well",
      "region": "johto"
    },
    {
      "name": "Snowbelle City",
      "slug": "snowbelle-city",
      "region": "kalos"
    },
    {
      "name": "Snowbelle Gate",
      "slug": "snowbelle-gate",
      "region": "kalos"
    },
    {
      "name": "Snowpoint City",
      "slug": "snowpoint-city",
      "region": "sinnoh"
    },
    {
      "name": "Snowpoint Temple",
      "slug": "snowpoint-temple",
      "region": "sinnoh"
    },
    {
      "name": "Soaring in the sky",
      "slug": "soaring-in-the-sky",
      "region": "hoenn"
    },
    {
      "name": "Solaceon Ruins",
      "slug": "solaceon-ruins",
      "region": "sinnoh"
    },
    {
      "name": "Solaceon Town",
      "slug": "solaceon-town",
      "region": "sinnoh"
    },
    {
      "name": "Sootopolis City",
      "slug": "sootopolis-city",
      "region": "hoenn"
    },
    {
      "name": "Southern Island",
      "slug": "southern-island",
      "region": "hoenn"
    },
    {
      "name": "Spear Pillar",
      "slug": "spear-pillar",
      "region": "sinnoh"
    },
    {
      "name": "Spikes Passage",
      "slug": "spikes-passage",
      "region": "kalos"
    },
    {
      "name": "Spring Path",
      "slug": "spring-path",
      "region": "sinnoh"
    },
    {
      "name": "Sprout Tower",
      "slug": "sprout-tower",
      "region": "johto"
    },
    {
      "name": "Stark Mountain",
      "slug": "stark-mountain",
      "region": "sinnoh"
    },
    {
      "name": "Strange House",
      "slug": "strange-house",
      "region": "unova"
    },
    {
      "name": "Striaton City",
      "slug": "striaton-city",
      "region": "unova"
    },
    {
      "name": "Sunyshore City",
      "slug": "sunyshore-city",
      "region": "sinnoh"
    },
    {
      "name": "Sunyshore Market",
      "slug": "sunyshore-market",
      "region": "sinnoh"
    },
    {
      "name": "Survival Area",
      "slug": "survival-area",
      "region": "sinnoh"
    },
    {
      "name": "T.G. Eterna Bldg",
      "slug": "tg-eterna-bldg",
      "region": "sinnoh"
    },
    {
      "name": "Tanoby Ruins",
      "slug": "tanoby-ruins",
      "region": "kanto"
    },
    {
      "name": "Team Aqua Hideout",
      "slug": "team-aqua-hideout",
      "region": "hoenn"
    },
    {
      "name": "Team Flare Secret HQ",
      "slug": "team-flare-secret-hq",
      "region": "kalos"
    },
    {
      "name": "Team Magma Hideout",
      "slug": "team-magma-hideout",
      "region": "hoenn"
    },
    {
      "name": "Team Rocket HQ",
      "slug": "team-rocket-hq",
      "region": "johto"
    },
    {
      "name": "Terminus Cave",
      "slug": "terminus-cave",
      "region": "kalos"
    },
    {
      "name": "Terra Cave",
      "slug": "terra-cave",
      "region": "hoenn"
    },
    {
      "name": "Three Island",
      "slug": "three-island",
      "region": "kanto"
    },
    {
      "name": "Three Isle Path",
      "slug": "three-isle-path",
      "region": "kanto"
    },
    {
      "name": "Three Isle Port",
      "slug": "three-isle-port",
      "region": "kanto"
    },
    {
      "name": "Tohjo Falls",
      "slug": "tohjo-falls",
      "region": "johto"
    },
    {
      "name": "Tower of Mastery",
      "slug": "tower-of-mastery",
      "region": "kalos"
    },
    {
      "name": "Trackless Forest",
      "slug": "trackless-forest",
      "region": "hoenn"
    },
    {
      "name": "Trainer Tower",
      "slug": "trainer-tower",
      "region": "kanto"
    },
    {
      "name": "Trainers’ School",
      "slug": "trainers-school",
      "region": "sinnoh"
    },
    {
      "name": "Treasure Beach",
      "slug": "treasure-beach",
      "region": "kanto"
    },
    {
      "name": "Trial Chamber",
      "slug": "trial-chamber",
      "region": "unova"
    },
    {
      "name": "Trophy Garden",
      "slug": "trophy-garden",
      "region": "sinnoh"
    },
    {
      "name": "Tubeline Bridge",
      "slug": "tubeline-bridge",
      "region": "unova"
    },
    {
      "name": "Turnback Cave",
      "slug": "turnback-cave",
      "region": "sinnoh"
    },
    {
      "name": "Twinleaf Town",
      "slug": "twinleaf-town",
      "region": "sinnoh"
    },
    {
      "name": "Twist Mountain",
      "slug": "twist-mountain",
      "region": "unova"
    },
    {
      "name": "Two Island",
      "slug": "two-island",
      "region": "kanto"
    },
    {
      "name": "Undella Bay",
      "slug": "undella-bay",
      "region": "unova"
    },
    {
      "name": "Undella Gate",
      "slug": "undella-gate",
      "region": "unova"
    },
    {
      "name": "Undella Town",
      "slug": "undella-town",
      "region": "unova"
    },
    {
      "name": "Underground Ruins",
      "slug": "underground-ruins",
      "region": "unova"
    },
    {
      "name": "Underwater",
      "slug": "underwater",
      "region": "hoenn"
    },
    {
      "name": "Union Cave",
      "slug": "union-cave",
      "region": "johto"
    },
    {
      "name": "Unity Tower",
      "slug": "unity-tower",
      "region": "unova"
    },
    {
      "name": "Unknown Dungeon",
      "slug": "unknown-dungeon",
      "region": "kalos"
    },
    {
      "name": "Unknown; all bugs",
      "slug": "unknown-all-bugs",
      "region": "johto"
    },
    {
      "name": "Unknown; all Poliwag",
      "slug": "unknown-all-poliwag",
      "region": "johto"
    },
    {
      "name": "Unknown; all Rattata",
      "slug": "unknown-all-rattata",
      "region": "johto"
    },
    {
      "name": "Unova (Romaing)",
      "slug": "roaming-unova",
      "region": "unova"
    },
    {
      "name": "Vallée Étroite Way",
      "slug": "vallee-etroite-way",
      "region": "kalos"
    },
    {
      "name": "Valley Windworks",
      "slug": "valley-windworks",
      "region": "sinnoh"
    },
    {
      "name": "Valor Cavern",
      "slug": "valor-cavern",
      "region": "sinnoh"
    },
    {
      "name": "Valor Lakefront",
      "slug": "valor-lakefront",
      "region": "sinnoh"
    },
    {
      "name": "Vaniville Pathway",
      "slug": "vaniville-pathway",
      "region": "kalos"
    },
    {
      "name": "Vaniville Town",
      "slug": "vaniville-town",
      "region": "kalos"
    },
    {
      "name": "Veilstone City",
      "slug": "veilstone-city",
      "region": "sinnoh"
    },
    {
      "name": "Veilstone Store",
      "slug": "veilstone-store",
      "region": "sinnoh"
    },
    {
      "name": "Verdanturf Town",
      "slug": "verdanturf-town",
      "region": "hoenn"
    },
    {
      "name": "Verity Cavern",
      "slug": "verity-cavern",
      "region": "sinnoh"
    },
    {
      "name": "Verity Lakefront",
      "slug": "verity-lakefront",
      "region": "sinnoh"
    },
    {
      "name": "Vermilion City",
      "slug": "vermilion-city",
      "region": "kanto"
    },
    {
      "name": "Versant Road",
      "slug": "versant-road",
      "region": "kalos"
    },
    {
      "name": "Viapos Chamber",
      "slug": "viapos-chamber",
      "region": "kanto"
    },
    {
      "name": "Victory Road",
      "slug": "sinnoh-victory-road",
      "region": "sinnoh"
    },
    {
      "name": "Victory Road",
      "slug": "kanto-victory-road-1",
      "region": "kanto"
    },
    {
      "name": "Victory Road",
      "slug": "kanto-victory-road-2",
      "region": "kanto"
    },
    {
      "name": "Victory Road",
      "slug": "unova-victory-road",
      "region": "unova"
    },
    {
      "name": "Victory Road",
      "slug": "hoenn-victory-road",
      "region": "hoenn"
    },
    {
      "name": "Victory Road",
      "slug": "unova-victory-road-2",
      "region": "unova"
    },
    {
      "name": "Victory Road",
      "slug": "kalos-victory-road",
      "region": "kalos"
    },
    {
      "name": "Villa",
      "slug": "sinnoh-villa",
      "region": "sinnoh"
    },
    {
      "name": "Village Bridge",
      "slug": "village-bridge",
      "region": "unova"
    },
    {
      "name": "Violet City",
      "slug": "violet-city",
      "region": "johto"
    },
    {
      "name": "Virbank City",
      "slug": "virbank-city",
      "region": "unova"
    },
    {
      "name": "Virbank Complex",
      "slug": "virbank-complex",
      "region": "unova"
    },
    {
      "name": "Virbank Gate",
      "slug": "virbank-gate",
      "region": "unova"
    },
    {
      "name": "Viridian City",
      "slug": "viridian-city",
      "region": "kanto"
    },
    {
      "name": "Viridian Forest",
      "slug": "viridian-forest",
      "region": "kanto"
    },
    {
      "name": "Vista Lighthouse",
      "slug": "vista-lighthouse",
      "region": "sinnoh"
    },
    {
      "name": "Water Labyrinth",
      "slug": "water-labyrinth",
      "region": "kanto"
    },
    {
      "name": "Water Path",
      "slug": "water-path",
      "region": "kanto"
    },
    {
      "name": "Wayward Cave",
      "slug": "wayward-cave",
      "region": "sinnoh"
    },
    {
      "name": "Weepth Chamber",
      "slug": "weepth-chamber",
      "region": "kanto"
    },
    {
      "name": "Wellspring Cave",
      "slug": "wellspring-cave",
      "region": "unova"
    },
    {
      "name": "Whirl Islands",
      "slug": "whirl-islands",
      "region": "johto"
    },
    {
      "name": "White Forest",
      "slug": "white-forest",
      "region": "unova"
    },
    {
      "name": "White Gate",
      "slug": "white-gate",
      "region": "unova"
    },
    {
      "name": "White Treehollow",
      "slug": "white-treehollow",
      "region": "unova"
    },
    {
      "name": "Winding Woods",
      "slug": "winding-woods",
      "region": "kalos"
    },
    {
      "name": "Zubat Roost",
      "slug": "zubat-roost",
      "region": "kalos"
    }
  ]
};
