// Generated by scripts/generate-pokemon-de.mjs
export const GERMAN_POKEMON_NAMES: { name: string; id: number; generation: number }[] = [
  {
    "name": "Aalabyss",
    "id": 367,
    "generation": 3
  },
  {
    "name": "Abra",
    "id": 63,
    "generation": 1
  },
  {
    "name": "Absol",
    "id": 359,
    "generation": 3
  },
  {
    "name": "Admurai",
    "id": 503,
    "generation": 5
  },
  {
    "name": "Aerodactyl",
    "id": 142,
    "generation": 1
  },
  {
    "name": "Aeropteryx",
    "id": 567,
    "generation": 5
  },
  {
    "name": "Algitt",
    "id": 690,
    "generation": 6
  },
  {
    "name": "Alpollo",
    "id": 93,
    "generation": 1
  },
  {
    "name": "Altaria",
    "id": 334,
    "generation": 3
  },
  {
    "name": "Amagarga",
    "id": 699,
    "generation": 6
  },
  {
    "name": "Amarino",
    "id": 698,
    "generation": 6
  },
  {
    "name": "Ambidiffel",
    "id": 424,
    "generation": 4
  },
  {
    "name": "Amonitas",
    "id": 138,
    "generation": 1
  },
  {
    "name": "Amoroso",
    "id": 139,
    "generation": 1
  },
  {
    "name": "Ampharos",
    "id": 181,
    "generation": 2
  },
  {
    "name": "Amphizel",
    "id": 657,
    "generation": 6
  },
  {
    "name": "Anorith",
    "id": 347,
    "generation": 3
  },
  {
    "name": "Apoquallyp",
    "id": 593,
    "generation": 5
  },
  {
    "name": "Aquana",
    "id": 134,
    "generation": 1
  },
  {
    "name": "Arbok",
    "id": 24,
    "generation": 1
  },
  {
    "name": "Arceus",
    "id": 493,
    "generation": 4
  },
  {
    "name": "Ariados",
    "id": 168,
    "generation": 2
  },
  {
    "name": "Arkani",
    "id": 59,
    "generation": 1
  },
  {
    "name": "Arktilas",
    "id": 713,
    "generation": 6
  },
  {
    "name": "Arktip",
    "id": 712,
    "generation": 6
  },
  {
    "name": "Arktos",
    "id": 144,
    "generation": 1
  },
  {
    "name": "Armaldo",
    "id": 348,
    "generation": 3
  },
  {
    "name": "Austos",
    "id": 91,
    "generation": 1
  },
  {
    "name": "Azumarill",
    "id": 184,
    "generation": 2
  },
  {
    "name": "Azurill",
    "id": 298,
    "generation": 3
  },
  {
    "name": "Baldorfish",
    "id": 211,
    "generation": 2
  },
  {
    "name": "Balgoras",
    "id": 696,
    "generation": 6
  },
  {
    "name": "Bamelin",
    "id": 418,
    "generation": 4
  },
  {
    "name": "Banette",
    "id": 354,
    "generation": 3
  },
  {
    "name": "Barschuft",
    "id": 550,
    "generation": 5
  },
  {
    "name": "Barschwa",
    "id": 349,
    "generation": 3
  },
  {
    "name": "Bibor",
    "id": 15,
    "generation": 1
  },
  {
    "name": "Bidifas",
    "id": 400,
    "generation": 4
  },
  {
    "name": "Bidiza",
    "id": 399,
    "generation": 4
  },
  {
    "name": "Bisaflor",
    "id": 3,
    "generation": 1
  },
  {
    "name": "Bisaknosp",
    "id": 2,
    "generation": 1
  },
  {
    "name": "Bisasam",
    "id": 1,
    "generation": 1
  },
  {
    "name": "Bisofank",
    "id": 626,
    "generation": 5
  },
  {
    "name": "Bissbark",
    "id": 508,
    "generation": 5
  },
  {
    "name": "Bithora",
    "id": 688,
    "generation": 6
  },
  {
    "name": "Blanas",
    "id": 274,
    "generation": 3
  },
  {
    "name": "Blitza",
    "id": 135,
    "generation": 1
  },
  {
    "name": "Blubella",
    "id": 182,
    "generation": 2
  },
  {
    "name": "Bluzuk",
    "id": 48,
    "generation": 1
  },
  {
    "name": "Bojelin",
    "id": 419,
    "generation": 4
  },
  {
    "name": "Bollterus",
    "id": 411,
    "generation": 4
  },
  {
    "name": "Boreos",
    "id": 641,
    "generation": 5
  },
  {
    "name": "Botogel",
    "id": 225,
    "generation": 2
  },
  {
    "name": "Branawarz",
    "id": 537,
    "generation": 5
  },
  {
    "name": "Brigaron",
    "id": 652,
    "generation": 6
  },
  {
    "name": "Brockoloss",
    "id": 526,
    "generation": 5
  },
  {
    "name": "Bronzel",
    "id": 436,
    "generation": 4
  },
  {
    "name": "Bronzong",
    "id": 437,
    "generation": 4
  },
  {
    "name": "Brutalanda",
    "id": 373,
    "generation": 3
  },
  {
    "name": "Bummelz",
    "id": 287,
    "generation": 3
  },
  {
    "name": "Burmadame",
    "id": 413,
    "generation": 4
  },
  {
    "name": "Burmy",
    "id": 412,
    "generation": 4
  },
  {
    "name": "Caesurio",
    "id": 625,
    "generation": 5
  },
  {
    "name": "Calamanero",
    "id": 687,
    "generation": 6
  },
  {
    "name": "Camaub",
    "id": 322,
    "generation": 3
  },
  {
    "name": "Camerupt",
    "id": 323,
    "generation": 3
  },
  {
    "name": "Castellith",
    "id": 558,
    "generation": 5
  },
  {
    "name": "Cavalanzas",
    "id": 589,
    "generation": 5
  },
  {
    "name": "Celebi",
    "id": 251,
    "generation": 2
  },
  {
    "name": "Cerapendra",
    "id": 545,
    "generation": 5
  },
  {
    "name": "Chaneira",
    "id": 113,
    "generation": 1
  },
  {
    "name": "Charmian",
    "id": 431,
    "generation": 4
  },
  {
    "name": "Chelast",
    "id": 387,
    "generation": 4
  },
  {
    "name": "Chelcarain",
    "id": 388,
    "generation": 4
  },
  {
    "name": "Chelterrar",
    "id": 389,
    "generation": 4
  },
  {
    "name": "Chevrumm",
    "id": 673,
    "generation": 6
  },
  {
    "name": "Chillabell",
    "id": 573,
    "generation": 5
  },
  {
    "name": "Clavion",
    "id": 707,
    "generation": 6
  },
  {
    "name": "Coiffwaff",
    "id": 676,
    "generation": 6
  },
  {
    "name": "Corasonn",
    "id": 222,
    "generation": 2
  },
  {
    "name": "Cresselia",
    "id": 488,
    "generation": 4
  },
  {
    "name": "Damhirplex",
    "id": 234,
    "generation": 2
  },
  {
    "name": "Darkrai",
    "id": 491,
    "generation": 4
  },
  {
    "name": "Dartignis",
    "id": 662,
    "generation": 6
  },
  {
    "name": "Dartiri",
    "id": 661,
    "generation": 6
  },
  {
    "name": "Dedenne",
    "id": 702,
    "generation": 6
  },
  {
    "name": "Demeteros",
    "id": 645,
    "generation": 5
  },
  {
    "name": "Deoxys",
    "id": 386,
    "generation": 3
  },
  {
    "name": "Deponitox",
    "id": 569,
    "generation": 5
  },
  {
    "name": "Despotar",
    "id": 248,
    "generation": 2
  },
  {
    "name": "Dialga",
    "id": 483,
    "generation": 4
  },
  {
    "name": "Diancie",
    "id": 719,
    "generation": 6
  },
  {
    "name": "Digda",
    "id": 50,
    "generation": 1
  },
  {
    "name": "Digdri",
    "id": 51,
    "generation": 1
  },
  {
    "name": "Ditto",
    "id": 132,
    "generation": 1
  },
  {
    "name": "Dodri",
    "id": 85,
    "generation": 1
  },
  {
    "name": "Dodu",
    "id": 84,
    "generation": 1
  },
  {
    "name": "Donphan",
    "id": 232,
    "generation": 2
  },
  {
    "name": "Dragonir",
    "id": 148,
    "generation": 1
  },
  {
    "name": "Dragoran",
    "id": 149,
    "generation": 1
  },
  {
    "name": "Draschel",
    "id": 372,
    "generation": 3
  },
  {
    "name": "Dratini",
    "id": 147,
    "generation": 1
  },
  {
    "name": "Dressella",
    "id": 549,
    "generation": 5
  },
  {
    "name": "Driftlon",
    "id": 425,
    "generation": 4
  },
  {
    "name": "Drifzepeli",
    "id": 426,
    "generation": 4
  },
  {
    "name": "Duflor",
    "id": 44,
    "generation": 1
  },
  {
    "name": "Dummisel",
    "id": 206,
    "generation": 2
  },
  {
    "name": "Duodino",
    "id": 634,
    "generation": 5
  },
  {
    "name": "Duokles",
    "id": 680,
    "generation": 6
  },
  {
    "name": "Durengard",
    "id": 681,
    "generation": 6
  },
  {
    "name": "Dusselgurr",
    "id": 519,
    "generation": 5
  },
  {
    "name": "Echnatoll",
    "id": 563,
    "generation": 5
  },
  {
    "name": "eF-eM",
    "id": 714,
    "generation": 6
  },
  {
    "name": "Efoserp",
    "id": 496,
    "generation": 5
  },
  {
    "name": "Eguana",
    "id": 694,
    "generation": 6
  },
  {
    "name": "Elekid",
    "id": 239,
    "generation": 2
  },
  {
    "name": "Elektek",
    "id": 125,
    "generation": 1
  },
  {
    "name": "Elevoltek",
    "id": 466,
    "generation": 4
  },
  {
    "name": "Elezard",
    "id": 695,
    "generation": 6
  },
  {
    "name": "Elezeba",
    "id": 522,
    "generation": 5
  },
  {
    "name": "Elfun",
    "id": 547,
    "generation": 5
  },
  {
    "name": "Emolga",
    "id": 587,
    "generation": 5
  },
  {
    "name": "Endivie",
    "id": 152,
    "generation": 2
  },
  {
    "name": "Eneco",
    "id": 300,
    "generation": 3
  },
  {
    "name": "Enekoro",
    "id": 301,
    "generation": 3
  },
  {
    "name": "Entei",
    "id": 244,
    "generation": 2
  },
  {
    "name": "Enton",
    "id": 54,
    "generation": 1
  },
  {
    "name": "Entoron",
    "id": 55,
    "generation": 1
  },
  {
    "name": "Evoli",
    "id": 133,
    "generation": 1
  },
  {
    "name": "Farbeagle",
    "id": 235,
    "generation": 2
  },
  {
    "name": "Fasasnob",
    "id": 521,
    "generation": 5
  },
  {
    "name": "Feelinara",
    "id": 700,
    "generation": 6
  },
  {
    "name": "Felilou",
    "id": 509,
    "generation": 5
  },
  {
    "name": "Felino",
    "id": 194,
    "generation": 2
  },
  {
    "name": "Fennexis",
    "id": 655,
    "generation": 6
  },
  {
    "name": "Ferkokel",
    "id": 499,
    "generation": 5
  },
  {
    "name": "Fermicula",
    "id": 632,
    "generation": 5
  },
  {
    "name": "Feurigel",
    "id": 155,
    "generation": 2
  },
  {
    "name": "Fiaro",
    "id": 663,
    "generation": 6
  },
  {
    "name": "Fiffyen",
    "id": 261,
    "generation": 3
  },
  {
    "name": "Finneon",
    "id": 456,
    "generation": 4
  },
  {
    "name": "Firnontor",
    "id": 362,
    "generation": 3
  },
  {
    "name": "Flabébé",
    "id": 669,
    "generation": 6
  },
  {
    "name": "Flamara",
    "id": 136,
    "generation": 1
  },
  {
    "name": "Flambirex",
    "id": 500,
    "generation": 5
  },
  {
    "name": "Flampion",
    "id": 554,
    "generation": 5
  },
  {
    "name": "Flampivian",
    "id": 555,
    "generation": 5
  },
  {
    "name": "Flapteryx",
    "id": 566,
    "generation": 5
  },
  {
    "name": "Flauschling",
    "id": 684,
    "generation": 6
  },
  {
    "name": "Flegmon",
    "id": 79,
    "generation": 1
  },
  {
    "name": "Fleknoil",
    "id": 527,
    "generation": 5
  },
  {
    "name": "Flemmli",
    "id": 255,
    "generation": 3
  },
  {
    "name": "Fletiamo",
    "id": 528,
    "generation": 5
  },
  {
    "name": "Floette",
    "id": 670,
    "generation": 6
  },
  {
    "name": "Floink",
    "id": 498,
    "generation": 5
  },
  {
    "name": "Florges",
    "id": 671,
    "generation": 6
  },
  {
    "name": "Fluffeluff",
    "id": 174,
    "generation": 2
  },
  {
    "name": "Flunkifer",
    "id": 303,
    "generation": 3
  },
  {
    "name": "Flunschlik",
    "id": 618,
    "generation": 5
  },
  {
    "name": "Flurmel",
    "id": 293,
    "generation": 3
  },
  {
    "name": "Folikon",
    "id": 541,
    "generation": 5
  },
  {
    "name": "Folipurba",
    "id": 470,
    "generation": 4
  },
  {
    "name": "Formeo",
    "id": 351,
    "generation": 3
  },
  {
    "name": "Forstellka",
    "id": 205,
    "generation": 2
  },
  {
    "name": "Frigometri",
    "id": 615,
    "generation": 5
  },
  {
    "name": "Frizelbliz",
    "id": 309,
    "generation": 3
  },
  {
    "name": "Frosdedje",
    "id": 478,
    "generation": 4
  },
  {
    "name": "Froxy",
    "id": 656,
    "generation": 6
  },
  {
    "name": "Fukano",
    "id": 58,
    "generation": 1
  },
  {
    "name": "Furnifraß",
    "id": 631,
    "generation": 5
  },
  {
    "name": "Fynx",
    "id": 653,
    "generation": 6
  },
  {
    "name": "Galagladi",
    "id": 475,
    "generation": 4
  },
  {
    "name": "Galapaflos",
    "id": 564,
    "generation": 5
  },
  {
    "name": "Gallopa",
    "id": 78,
    "generation": 1
  },
  {
    "name": "Ganovil",
    "id": 551,
    "generation": 5
  },
  {
    "name": "Garados",
    "id": 130,
    "generation": 1
  },
  {
    "name": "Gastrodon",
    "id": 423,
    "generation": 4
  },
  {
    "name": "Geckarbor",
    "id": 252,
    "generation": 3
  },
  {
    "name": "Gehweiher",
    "id": 283,
    "generation": 3
  },
  {
    "name": "Gelatini",
    "id": 582,
    "generation": 5
  },
  {
    "name": "Gelatroppo",
    "id": 583,
    "generation": 5
  },
  {
    "name": "Gelatwino",
    "id": 584,
    "generation": 5
  },
  {
    "name": "Genesect",
    "id": 649,
    "generation": 5
  },
  {
    "name": "Gengar",
    "id": 94,
    "generation": 1
  },
  {
    "name": "Georok",
    "id": 75,
    "generation": 1
  },
  {
    "name": "Geowaz",
    "id": 76,
    "generation": 1
  },
  {
    "name": "Geradaks",
    "id": 264,
    "generation": 3
  },
  {
    "name": "Geronimatz",
    "id": 627,
    "generation": 5
  },
  {
    "name": "Gewaldro",
    "id": 254,
    "generation": 3
  },
  {
    "name": "Giflor",
    "id": 45,
    "generation": 1
  },
  {
    "name": "Girafarig",
    "id": 203,
    "generation": 2
  },
  {
    "name": "Giratina",
    "id": 487,
    "generation": 4
  },
  {
    "name": "Gladiantri",
    "id": 624,
    "generation": 5
  },
  {
    "name": "Glaziola",
    "id": 471,
    "generation": 4
  },
  {
    "name": "Glibunkel",
    "id": 453,
    "generation": 4
  },
  {
    "name": "Glumanda",
    "id": 4,
    "generation": 1
  },
  {
    "name": "Glurak",
    "id": 6,
    "generation": 1
  },
  {
    "name": "Glutexo",
    "id": 5,
    "generation": 1
  },
  {
    "name": "Golbat",
    "id": 42,
    "generation": 1
  },
  {
    "name": "Golbit",
    "id": 622,
    "generation": 5
  },
  {
    "name": "Goldini",
    "id": 118,
    "generation": 1
  },
  {
    "name": "Golgantes",
    "id": 623,
    "generation": 5
  },
  {
    "name": "Golking",
    "id": 119,
    "generation": 1
  },
  {
    "name": "Gramokles",
    "id": 679,
    "generation": 6
  },
  {
    "name": "Granbull",
    "id": 210,
    "generation": 2
  },
  {
    "name": "Grebbit",
    "id": 660,
    "generation": 6
  },
  {
    "name": "Griffel",
    "id": 190,
    "generation": 2
  },
  {
    "name": "Grillchita",
    "id": 514,
    "generation": 5
  },
  {
    "name": "Grillmak",
    "id": 513,
    "generation": 5
  },
  {
    "name": "Groink",
    "id": 326,
    "generation": 3
  },
  {
    "name": "Groudon",
    "id": 383,
    "generation": 3
  },
  {
    "name": "Grypheldis",
    "id": 630,
    "generation": 5
  },
  {
    "name": "Guardevoir",
    "id": 282,
    "generation": 3
  },
  {
    "name": "Habitak",
    "id": 21,
    "generation": 1
  },
  {
    "name": "Hariyama",
    "id": 297,
    "generation": 3
  },
  {
    "name": "Haspiror",
    "id": 427,
    "generation": 4
  },
  {
    "name": "Heatran",
    "id": 485,
    "generation": 4
  },
  {
    "name": "Heiteira",
    "id": 242,
    "generation": 2
  },
  {
    "name": "Hippopotas",
    "id": 449,
    "generation": 4
  },
  {
    "name": "Hippoterus",
    "id": 450,
    "generation": 4
  },
  {
    "name": "Ho-Oh",
    "id": 250,
    "generation": 2
  },
  {
    "name": "Honweisel",
    "id": 416,
    "generation": 4
  },
  {
    "name": "Hoopa",
    "id": 720,
    "generation": 6
  },
  {
    "name": "Hoothoot",
    "id": 163,
    "generation": 2
  },
  {
    "name": "Hoppspross",
    "id": 187,
    "generation": 2
  },
  {
    "name": "Hornliu",
    "id": 13,
    "generation": 1
  },
  {
    "name": "Hubelupf",
    "id": 188,
    "generation": 2
  },
  {
    "name": "Hundemon",
    "id": 229,
    "generation": 2
  },
  {
    "name": "Hunduster",
    "id": 228,
    "generation": 2
  },
  {
    "name": "Hutsassa",
    "id": 591,
    "generation": 5
  },
  {
    "name": "Hydragil",
    "id": 617,
    "generation": 5
  },
  {
    "name": "Hydropi",
    "id": 258,
    "generation": 3
  },
  {
    "name": "Hypno",
    "id": 97,
    "generation": 1
  },
  {
    "name": "Hypnomorba",
    "id": 575,
    "generation": 5
  },
  {
    "name": "Ibitak",
    "id": 22,
    "generation": 1
  },
  {
    "name": "Icognito",
    "id": 201,
    "generation": 2
  },
  {
    "name": "Igamaro",
    "id": 650,
    "generation": 6
  },
  {
    "name": "Igastarnish",
    "id": 651,
    "generation": 6
  },
  {
    "name": "Igelavar",
    "id": 156,
    "generation": 2
  },
  {
    "name": "Ignivor",
    "id": 636,
    "generation": 5
  },
  {
    "name": "Iksbat",
    "id": 169,
    "generation": 2
  },
  {
    "name": "Illumise",
    "id": 314,
    "generation": 3
  },
  {
    "name": "Impergator",
    "id": 160,
    "generation": 2
  },
  {
    "name": "Impoleon",
    "id": 395,
    "generation": 4
  },
  {
    "name": "Irokex",
    "id": 560,
    "generation": 5
  },
  {
    "name": "Irrbis",
    "id": 710,
    "generation": 6
  },
  {
    "name": "Iscalar",
    "id": 686,
    "generation": 6
  },
  {
    "name": "Isso",
    "id": 360,
    "generation": 3
  },
  {
    "name": "Jirachi",
    "id": 385,
    "generation": 3
  },
  {
    "name": "Jiutesto",
    "id": 538,
    "generation": 5
  },
  {
    "name": "Jugong",
    "id": 87,
    "generation": 1
  },
  {
    "name": "Jungglut",
    "id": 256,
    "generation": 3
  },
  {
    "name": "Jurob",
    "id": 86,
    "generation": 1
  },
  {
    "name": "Kabuto",
    "id": 140,
    "generation": 1
  },
  {
    "name": "Kabutops",
    "id": 141,
    "generation": 1
  },
  {
    "name": "Kadabra",
    "id": 64,
    "generation": 1
  },
  {
    "name": "Kangama",
    "id": 115,
    "generation": 1
  },
  {
    "name": "Kanivanha",
    "id": 318,
    "generation": 3
  },
  {
    "name": "Kapilz",
    "id": 286,
    "generation": 3
  },
  {
    "name": "Kapoera",
    "id": 237,
    "generation": 2
  },
  {
    "name": "Kappalores",
    "id": 272,
    "generation": 3
  },
  {
    "name": "Kapuno",
    "id": 633,
    "generation": 5
  },
  {
    "name": "Karadonis",
    "id": 539,
    "generation": 5
  },
  {
    "name": "Karippas",
    "id": 565,
    "generation": 5
  },
  {
    "name": "Karnimani",
    "id": 158,
    "generation": 2
  },
  {
    "name": "Karpador",
    "id": 129,
    "generation": 1
  },
  {
    "name": "Kastadur",
    "id": 597,
    "generation": 5
  },
  {
    "name": "Kaumalat",
    "id": 443,
    "generation": 4
  },
  {
    "name": "Kecleon",
    "id": 352,
    "generation": 3
  },
  {
    "name": "Keifel",
    "id": 221,
    "generation": 2
  },
  {
    "name": "Keldeo",
    "id": 647,
    "generation": 5
  },
  {
    "name": "Kicklee",
    "id": 106,
    "generation": 1
  },
  {
    "name": "Kiesling",
    "id": 524,
    "generation": 5
  },
  {
    "name": "Kikugi",
    "id": 420,
    "generation": 4
  },
  {
    "name": "Kindwurm",
    "id": 371,
    "generation": 3
  },
  {
    "name": "Kingler",
    "id": 99,
    "generation": 1
  },
  {
    "name": "Kinoso",
    "id": 421,
    "generation": 4
  },
  {
    "name": "Kirlia",
    "id": 281,
    "generation": 3
  },
  {
    "name": "Kleinstein",
    "id": 74,
    "generation": 1
  },
  {
    "name": "Kleoparda",
    "id": 510,
    "generation": 5
  },
  {
    "name": "Klikdiklak",
    "id": 601,
    "generation": 5
  },
  {
    "name": "Klikk",
    "id": 599,
    "generation": 5
  },
  {
    "name": "Kliklak",
    "id": 600,
    "generation": 5
  },
  {
    "name": "Klingplim",
    "id": 433,
    "generation": 4
  },
  {
    "name": "Knacklion",
    "id": 328,
    "generation": 3
  },
  {
    "name": "Knakrack",
    "id": 445,
    "generation": 4
  },
  {
    "name": "Knarksel",
    "id": 444,
    "generation": 4
  },
  {
    "name": "Knilz",
    "id": 285,
    "generation": 3
  },
  {
    "name": "Knofensa",
    "id": 69,
    "generation": 1
  },
  {
    "name": "Knogga",
    "id": 105,
    "generation": 1
  },
  {
    "name": "Knospi",
    "id": 406,
    "generation": 4
  },
  {
    "name": "Knuddeluff",
    "id": 40,
    "generation": 1
  },
  {
    "name": "Kobalium",
    "id": 638,
    "generation": 5
  },
  {
    "name": "Koknodon",
    "id": 408,
    "generation": 4
  },
  {
    "name": "Kokowei",
    "id": 103,
    "generation": 1
  },
  {
    "name": "Kokuna",
    "id": 14,
    "generation": 1
  },
  {
    "name": "Krabby",
    "id": 98,
    "generation": 1
  },
  {
    "name": "Krakeelo",
    "id": 294,
    "generation": 3
  },
  {
    "name": "Kramshef",
    "id": 430,
    "generation": 4
  },
  {
    "name": "Kramurx",
    "id": 198,
    "generation": 2
  },
  {
    "name": "Krawumms",
    "id": 295,
    "generation": 3
  },
  {
    "name": "Krebscorps",
    "id": 341,
    "generation": 3
  },
  {
    "name": "Krebutack",
    "id": 342,
    "generation": 3
  },
  {
    "name": "Kronjuwild",
    "id": 586,
    "generation": 5
  },
  {
    "name": "Kryppuk",
    "id": 442,
    "generation": 4
  },
  {
    "name": "Kukmarda",
    "id": 505,
    "generation": 5
  },
  {
    "name": "Kussilla",
    "id": 238,
    "generation": 2
  },
  {
    "name": "Kyogre",
    "id": 382,
    "generation": 3
  },
  {
    "name": "Kyurem",
    "id": 646,
    "generation": 5
  },
  {
    "name": "Lahmus",
    "id": 80,
    "generation": 1
  },
  {
    "name": "Lampi",
    "id": 170,
    "generation": 2
  },
  {
    "name": "Lanturn",
    "id": 171,
    "generation": 2
  },
  {
    "name": "Lapras",
    "id": 131,
    "generation": 1
  },
  {
    "name": "Larvitar",
    "id": 246,
    "generation": 2
  },
  {
    "name": "Laschoking",
    "id": 199,
    "generation": 2
  },
  {
    "name": "Laternecto",
    "id": 608,
    "generation": 5
  },
  {
    "name": "Latias",
    "id": 380,
    "generation": 3
  },
  {
    "name": "Latios",
    "id": 381,
    "generation": 3
  },
  {
    "name": "Laukaps",
    "id": 588,
    "generation": 5
  },
  {
    "name": "Lavados",
    "id": 146,
    "generation": 1
  },
  {
    "name": "Ledian",
    "id": 166,
    "generation": 2
  },
  {
    "name": "Ledyba",
    "id": 165,
    "generation": 2
  },
  {
    "name": "Lektrobal",
    "id": 101,
    "generation": 1
  },
  {
    "name": "Lepumentas",
    "id": 344,
    "generation": 3
  },
  {
    "name": "Letarking",
    "id": 289,
    "generation": 3
  },
  {
    "name": "Leufeo",
    "id": 667,
    "generation": 6
  },
  {
    "name": "Libelldra",
    "id": 330,
    "generation": 3
  },
  {
    "name": "Lichtel",
    "id": 607,
    "generation": 5
  },
  {
    "name": "Liebiskus",
    "id": 370,
    "generation": 3
  },
  {
    "name": "Liliep",
    "id": 345,
    "generation": 3
  },
  {
    "name": "Lilminip",
    "id": 548,
    "generation": 5
  },
  {
    "name": "Lin-Fu",
    "id": 619,
    "generation": 5
  },
  {
    "name": "Lithomith",
    "id": 557,
    "generation": 5
  },
  {
    "name": "Lohgock",
    "id": 257,
    "generation": 3
  },
  {
    "name": "Lombrero",
    "id": 271,
    "generation": 3
  },
  {
    "name": "Lorblatt",
    "id": 153,
    "generation": 2
  },
  {
    "name": "Loturzel",
    "id": 270,
    "generation": 3
  },
  {
    "name": "Lucario",
    "id": 448,
    "generation": 4
  },
  {
    "name": "Lugia",
    "id": 249,
    "generation": 2
  },
  {
    "name": "Lumineon",
    "id": 457,
    "generation": 4
  },
  {
    "name": "Lunastein",
    "id": 337,
    "generation": 3
  },
  {
    "name": "Luxio",
    "id": 404,
    "generation": 4
  },
  {
    "name": "Luxtra",
    "id": 405,
    "generation": 4
  },
  {
    "name": "Machollo",
    "id": 66,
    "generation": 1
  },
  {
    "name": "Machomei",
    "id": 68,
    "generation": 1
  },
  {
    "name": "Magbrant",
    "id": 467,
    "generation": 4
  },
  {
    "name": "Magby",
    "id": 240,
    "generation": 2
  },
  {
    "name": "Magcargo",
    "id": 219,
    "generation": 2
  },
  {
    "name": "Magmar",
    "id": 126,
    "generation": 1
  },
  {
    "name": "Magnayen",
    "id": 262,
    "generation": 3
  },
  {
    "name": "Magnetilo",
    "id": 81,
    "generation": 1
  },
  {
    "name": "Magneton",
    "id": 82,
    "generation": 1
  },
  {
    "name": "Magnezone",
    "id": 462,
    "generation": 4
  },
  {
    "name": "Mähikel",
    "id": 672,
    "generation": 6
  },
  {
    "name": "Makabaja",
    "id": 562,
    "generation": 5
  },
  {
    "name": "Makuhita",
    "id": 296,
    "generation": 3
  },
  {
    "name": "Mamolida",
    "id": 594,
    "generation": 5
  },
  {
    "name": "Mampfaxo",
    "id": 446,
    "generation": 4
  },
  {
    "name": "Mamutel",
    "id": 473,
    "generation": 4
  },
  {
    "name": "Manaphy",
    "id": 490,
    "generation": 4
  },
  {
    "name": "Mantax",
    "id": 226,
    "generation": 2
  },
  {
    "name": "Mantirps",
    "id": 458,
    "generation": 4
  },
  {
    "name": "Maracamba",
    "id": 556,
    "generation": 5
  },
  {
    "name": "Marill",
    "id": 183,
    "generation": 2
  },
  {
    "name": "Maschock",
    "id": 67,
    "generation": 1
  },
  {
    "name": "Maskeregen",
    "id": 284,
    "generation": 3
  },
  {
    "name": "Matrifol",
    "id": 542,
    "generation": 5
  },
  {
    "name": "Mauzi",
    "id": 52,
    "generation": 1
  },
  {
    "name": "Maxax",
    "id": 612,
    "generation": 5
  },
  {
    "name": "Mebrana",
    "id": 536,
    "generation": 5
  },
  {
    "name": "Meditalis",
    "id": 308,
    "generation": 3
  },
  {
    "name": "Meditie",
    "id": 307,
    "generation": 3
  },
  {
    "name": "Megalon",
    "id": 606,
    "generation": 5
  },
  {
    "name": "Meganie",
    "id": 154,
    "generation": 2
  },
  {
    "name": "Meistagrif",
    "id": 534,
    "generation": 5
  },
  {
    "name": "Meloetta",
    "id": 648,
    "generation": 5
  },
  {
    "name": "Menki",
    "id": 56,
    "generation": 1
  },
  {
    "name": "Metagross",
    "id": 376,
    "generation": 3
  },
  {
    "name": "Metang",
    "id": 375,
    "generation": 3
  },
  {
    "name": "Mew",
    "id": 151,
    "generation": 1
  },
  {
    "name": "Mewtu",
    "id": 150,
    "generation": 1
  },
  {
    "name": "Milotic",
    "id": 350,
    "generation": 3
  },
  {
    "name": "Miltank",
    "id": 241,
    "generation": 2
  },
  {
    "name": "Milza",
    "id": 610,
    "generation": 5
  },
  {
    "name": "Minun",
    "id": 312,
    "generation": 3
  },
  {
    "name": "Mitodos",
    "id": 578,
    "generation": 5
  },
  {
    "name": "Mobai",
    "id": 438,
    "generation": 4
  },
  {
    "name": "Mogelbaum",
    "id": 185,
    "generation": 2
  },
  {
    "name": "Mollimorba",
    "id": 574,
    "generation": 5
  },
  {
    "name": "Monargoras",
    "id": 697,
    "generation": 6
  },
  {
    "name": "Monozyto",
    "id": 577,
    "generation": 5
  },
  {
    "name": "Moorabbel",
    "id": 259,
    "generation": 3
  },
  {
    "name": "Morbitesse",
    "id": 576,
    "generation": 5
  },
  {
    "name": "Morlord",
    "id": 195,
    "generation": 2
  },
  {
    "name": "Moterpel",
    "id": 414,
    "generation": 4
  },
  {
    "name": "Muntier",
    "id": 288,
    "generation": 3
  },
  {
    "name": "Muschas",
    "id": 90,
    "generation": 1
  },
  {
    "name": "Myrapla",
    "id": 43,
    "generation": 1
  },
  {
    "name": "Nachtara",
    "id": 197,
    "generation": 2
  },
  {
    "name": "Nagelotz",
    "id": 504,
    "generation": 5
  },
  {
    "name": "Nasgnet",
    "id": 299,
    "generation": 3
  },
  {
    "name": "Natu",
    "id": 177,
    "generation": 2
  },
  {
    "name": "Navitaub",
    "id": 520,
    "generation": 5
  },
  {
    "name": "Nebulak",
    "id": 92,
    "generation": 1
  },
  {
    "name": "Nidoking",
    "id": 34,
    "generation": 1
  },
  {
    "name": "Nidoqueen",
    "id": 31,
    "generation": 1
  },
  {
    "name": "Nidoran♀",
    "id": 29,
    "generation": 1
  },
  {
    "name": "Nidoran♂",
    "id": 32,
    "generation": 1
  },
  {
    "name": "Nidorina",
    "id": 30,
    "generation": 1
  },
  {
    "name": "Nidorino",
    "id": 33,
    "generation": 1
  },
  {
    "name": "Nincada",
    "id": 290,
    "generation": 3
  },
  {
    "name": "Ninjask",
    "id": 291,
    "generation": 3
  },
  {
    "name": "Ninjatom",
    "id": 292,
    "generation": 3
  },
  {
    "name": "Nockchan",
    "id": 107,
    "generation": 1
  },
  {
    "name": "Noctuh",
    "id": 164,
    "generation": 2
  },
  {
    "name": "Noktuska",
    "id": 332,
    "generation": 3
  },
  {
    "name": "Octillery",
    "id": 224,
    "generation": 2
  },
  {
    "name": "Ohrdoch",
    "id": 531,
    "generation": 5
  },
  {
    "name": "Omot",
    "id": 49,
    "generation": 1
  },
  {
    "name": "Onix",
    "id": 95,
    "generation": 1
  },
  {
    "name": "Ottaro",
    "id": 501,
    "generation": 5
  },
  {
    "name": "Owei",
    "id": 102,
    "generation": 1
  },
  {
    "name": "Pachirisu",
    "id": 417,
    "generation": 4
  },
  {
    "name": "Palimpalim",
    "id": 358,
    "generation": 3
  },
  {
    "name": "Palkia",
    "id": 484,
    "generation": 4
  },
  {
    "name": "Pam-Pam",
    "id": 674,
    "generation": 6
  },
  {
    "name": "Pandagro",
    "id": 675,
    "generation": 6
  },
  {
    "name": "Pandir",
    "id": 327,
    "generation": 3
  },
  {
    "name": "Panekon",
    "id": 268,
    "generation": 3
  },
  {
    "name": "Panferno",
    "id": 392,
    "generation": 4
  },
  {
    "name": "Panflam",
    "id": 390,
    "generation": 4
  },
  {
    "name": "Panpyro",
    "id": 391,
    "generation": 4
  },
  {
    "name": "Pantimimi",
    "id": 439,
    "generation": 4
  },
  {
    "name": "Pantimos",
    "id": 122,
    "generation": 1
  },
  {
    "name": "Panzaeron",
    "id": 227,
    "generation": 2
  },
  {
    "name": "Papinella",
    "id": 267,
    "generation": 3
  },
  {
    "name": "Papungha",
    "id": 189,
    "generation": 2
  },
  {
    "name": "Paragoni",
    "id": 708,
    "generation": 6
  },
  {
    "name": "Paras",
    "id": 46,
    "generation": 1
  },
  {
    "name": "Parasek",
    "id": 47,
    "generation": 1
  },
  {
    "name": "Parfi",
    "id": 682,
    "generation": 6
  },
  {
    "name": "Parfinesse",
    "id": 683,
    "generation": 6
  },
  {
    "name": "Pelipper",
    "id": 279,
    "generation": 3
  },
  {
    "name": "Perlu",
    "id": 366,
    "generation": 3
  },
  {
    "name": "Petznief",
    "id": 613,
    "generation": 5
  },
  {
    "name": "Phanpy",
    "id": 231,
    "generation": 2
  },
  {
    "name": "Phione",
    "id": 489,
    "generation": 4
  },
  {
    "name": "Piccolente",
    "id": 580,
    "generation": 5
  },
  {
    "name": "Pichu",
    "id": 172,
    "generation": 2
  },
  {
    "name": "Picochilla",
    "id": 572,
    "generation": 5
  },
  {
    "name": "Piepi",
    "id": 35,
    "generation": 1
  },
  {
    "name": "Pii",
    "id": 173,
    "generation": 2
  },
  {
    "name": "Pikachu",
    "id": 25,
    "generation": 1
  },
  {
    "name": "Pinsir",
    "id": 127,
    "generation": 1
  },
  {
    "name": "Piondragi",
    "id": 452,
    "generation": 4
  },
  {
    "name": "Pionskora",
    "id": 451,
    "generation": 4
  },
  {
    "name": "Pixi",
    "id": 36,
    "generation": 1
  },
  {
    "name": "Plaudagei",
    "id": 441,
    "generation": 4
  },
  {
    "name": "Plinfa",
    "id": 393,
    "generation": 4
  },
  {
    "name": "Pliprin",
    "id": 394,
    "generation": 4
  },
  {
    "name": "Plusle",
    "id": 311,
    "generation": 3
  },
  {
    "name": "Ponita",
    "id": 77,
    "generation": 1
  },
  {
    "name": "Porenta",
    "id": 83,
    "generation": 1
  },
  {
    "name": "Porygon",
    "id": 137,
    "generation": 1
  },
  {
    "name": "Porygon-Z",
    "id": 474,
    "generation": 4
  },
  {
    "name": "Porygon2",
    "id": 233,
    "generation": 2
  },
  {
    "name": "Pottrott",
    "id": 213,
    "generation": 2
  },
  {
    "name": "Praktibalk",
    "id": 532,
    "generation": 5
  },
  {
    "name": "Psiana",
    "id": 196,
    "generation": 2
  },
  {
    "name": "Psiau",
    "id": 677,
    "generation": 6
  },
  {
    "name": "Psiaugon",
    "id": 678,
    "generation": 6
  },
  {
    "name": "Pudox",
    "id": 269,
    "generation": 3
  },
  {
    "name": "Pummeluff",
    "id": 39,
    "generation": 1
  },
  {
    "name": "Pumpdjinn",
    "id": 711,
    "generation": 6
  },
  {
    "name": "Pupitar",
    "id": 247,
    "generation": 2
  },
  {
    "name": "Puponcho",
    "id": 665,
    "generation": 6
  },
  {
    "name": "Puppance",
    "id": 343,
    "generation": 3
  },
  {
    "name": "Purmel",
    "id": 664,
    "generation": 6
  },
  {
    "name": "Pygraulon",
    "id": 605,
    "generation": 5
  },
  {
    "name": "Pyroleo",
    "id": 668,
    "generation": 6
  },
  {
    "name": "Quabbel",
    "id": 592,
    "generation": 5
  },
  {
    "name": "Quajutsu",
    "id": 658,
    "generation": 6
  },
  {
    "name": "Quappo",
    "id": 62,
    "generation": 1
  },
  {
    "name": "Quapsel",
    "id": 60,
    "generation": 1
  },
  {
    "name": "Quaputzi",
    "id": 61,
    "generation": 1
  },
  {
    "name": "Quaxo",
    "id": 186,
    "generation": 2
  },
  {
    "name": "Quiekel",
    "id": 220,
    "generation": 2
  },
  {
    "name": "Qurtel",
    "id": 324,
    "generation": 3
  },
  {
    "name": "Rabauz",
    "id": 236,
    "generation": 2
  },
  {
    "name": "Rabigator",
    "id": 553,
    "generation": 5
  },
  {
    "name": "Raichu",
    "id": 26,
    "generation": 1
  },
  {
    "name": "Raikou",
    "id": 243,
    "generation": 2
  },
  {
    "name": "Rameidon",
    "id": 409,
    "generation": 4
  },
  {
    "name": "Ramoth",
    "id": 637,
    "generation": 5
  },
  {
    "name": "Rasaff",
    "id": 57,
    "generation": 1
  },
  {
    "name": "Rattfratz",
    "id": 19,
    "generation": 1
  },
  {
    "name": "Rattikarl",
    "id": 20,
    "generation": 1
  },
  {
    "name": "Raupy",
    "id": 10,
    "generation": 1
  },
  {
    "name": "Rayquaza",
    "id": 384,
    "generation": 3
  },
  {
    "name": "Regice",
    "id": 378,
    "generation": 3
  },
  {
    "name": "Regigigas",
    "id": 486,
    "generation": 4
  },
  {
    "name": "Regirock",
    "id": 377,
    "generation": 3
  },
  {
    "name": "Registeel",
    "id": 379,
    "generation": 3
  },
  {
    "name": "Relaxo",
    "id": 143,
    "generation": 1
  },
  {
    "name": "Relicanth",
    "id": 369,
    "generation": 3
  },
  {
    "name": "Remoraid",
    "id": 223,
    "generation": 2
  },
  {
    "name": "Reptain",
    "id": 253,
    "generation": 3
  },
  {
    "name": "Reshiram",
    "id": 643,
    "generation": 5
  },
  {
    "name": "Resladero",
    "id": 701,
    "generation": 6
  },
  {
    "name": "Rettan",
    "id": 23,
    "generation": 1
  },
  {
    "name": "Rexblisar",
    "id": 460,
    "generation": 4
  },
  {
    "name": "Rihorn",
    "id": 111,
    "generation": 1
  },
  {
    "name": "Rihornior",
    "id": 464,
    "generation": 4
  },
  {
    "name": "Riolu",
    "id": 447,
    "generation": 4
  },
  {
    "name": "Rizeros",
    "id": 112,
    "generation": 1
  },
  {
    "name": "Rocara",
    "id": 703,
    "generation": 6
  },
  {
    "name": "Rokkaiman",
    "id": 552,
    "generation": 5
  },
  {
    "name": "Rollum",
    "id": 544,
    "generation": 5
  },
  {
    "name": "Roselia",
    "id": 315,
    "generation": 3
  },
  {
    "name": "Roserade",
    "id": 407,
    "generation": 4
  },
  {
    "name": "Rossana",
    "id": 124,
    "generation": 1
  },
  {
    "name": "Rotom",
    "id": 479,
    "generation": 4
  },
  {
    "name": "Rotomurf",
    "id": 529,
    "generation": 5
  },
  {
    "name": "Rutena",
    "id": 654,
    "generation": 6
  },
  {
    "name": "Sabbaione",
    "id": 685,
    "generation": 6
  },
  {
    "name": "Safcon",
    "id": 11,
    "generation": 1
  },
  {
    "name": "Saganabyss",
    "id": 368,
    "generation": 3
  },
  {
    "name": "Samurzel",
    "id": 273,
    "generation": 3
  },
  {
    "name": "Sandamer",
    "id": 28,
    "generation": 1
  },
  {
    "name": "Sandan",
    "id": 27,
    "generation": 1
  },
  {
    "name": "Sarzenia",
    "id": 71,
    "generation": 1
  },
  {
    "name": "Scampisto",
    "id": 692,
    "generation": 6
  },
  {
    "name": "Schalellos",
    "id": 422,
    "generation": 4
  },
  {
    "name": "Schallquap",
    "id": 535,
    "generation": 5
  },
  {
    "name": "Schaloko",
    "id": 266,
    "generation": 3
  },
  {
    "name": "Scherox",
    "id": 212,
    "generation": 2
  },
  {
    "name": "Schiggy",
    "id": 7,
    "generation": 1
  },
  {
    "name": "Schillok",
    "id": 8,
    "generation": 1
  },
  {
    "name": "Schilterus",
    "id": 410,
    "generation": 4
  },
  {
    "name": "Schlapor",
    "id": 428,
    "generation": 4
  },
  {
    "name": "Schlukwech",
    "id": 317,
    "generation": 3
  },
  {
    "name": "Schluppuck",
    "id": 316,
    "generation": 3
  },
  {
    "name": "Schlurp",
    "id": 108,
    "generation": 1
  },
  {
    "name": "Schlurplek",
    "id": 463,
    "generation": 4
  },
  {
    "name": "Schmerbe",
    "id": 339,
    "generation": 3
  },
  {
    "name": "Schneckmag",
    "id": 218,
    "generation": 2
  },
  {
    "name": "Schneppke",
    "id": 361,
    "generation": 3
  },
  {
    "name": "Schnuthelm",
    "id": 616,
    "generation": 5
  },
  {
    "name": "Schwalbini",
    "id": 276,
    "generation": 3
  },
  {
    "name": "Schwalboss",
    "id": 277,
    "generation": 3
  },
  {
    "name": "Scoppel",
    "id": 659,
    "generation": 6
  },
  {
    "name": "Sedimantur",
    "id": 525,
    "generation": 5
  },
  {
    "name": "Seedraking",
    "id": 230,
    "generation": 2
  },
  {
    "name": "Seejong",
    "id": 364,
    "generation": 3
  },
  {
    "name": "Seemon",
    "id": 117,
    "generation": 1
  },
  {
    "name": "Seemops",
    "id": 363,
    "generation": 3
  },
  {
    "name": "Seeper",
    "id": 116,
    "generation": 1
  },
  {
    "name": "Selfe",
    "id": 480,
    "generation": 4
  },
  {
    "name": "Sengo",
    "id": 335,
    "generation": 3
  },
  {
    "name": "Serpifeu",
    "id": 495,
    "generation": 5
  },
  {
    "name": "Serpiroyal",
    "id": 497,
    "generation": 5
  },
  {
    "name": "Sesokitz",
    "id": 585,
    "generation": 5
  },
  {
    "name": "Shardrago",
    "id": 621,
    "generation": 5
  },
  {
    "name": "Sharfax",
    "id": 611,
    "generation": 5
  },
  {
    "name": "Shaymin",
    "id": 492,
    "generation": 4
  },
  {
    "name": "Sheinux",
    "id": 403,
    "generation": 4
  },
  {
    "name": "Shnebedeck",
    "id": 459,
    "generation": 4
  },
  {
    "name": "Shnurgarst",
    "id": 432,
    "generation": 4
  },
  {
    "name": "Shuppet",
    "id": 353,
    "generation": 3
  },
  {
    "name": "Siberio",
    "id": 614,
    "generation": 5
  },
  {
    "name": "Sichlor",
    "id": 123,
    "generation": 1
  },
  {
    "name": "Simsala",
    "id": 65,
    "generation": 1
  },
  {
    "name": "Skallyk",
    "id": 629,
    "generation": 5
  },
  {
    "name": "Skaraborn",
    "id": 214,
    "generation": 2
  },
  {
    "name": "Skelabra",
    "id": 609,
    "generation": 5
  },
  {
    "name": "Skorgla",
    "id": 207,
    "generation": 2
  },
  {
    "name": "Skorgro",
    "id": 472,
    "generation": 4
  },
  {
    "name": "Skunkapuh",
    "id": 434,
    "generation": 4
  },
  {
    "name": "Skuntank",
    "id": 435,
    "generation": 4
  },
  {
    "name": "Sleima",
    "id": 88,
    "generation": 1
  },
  {
    "name": "Sleimok",
    "id": 89,
    "generation": 1
  },
  {
    "name": "Smettbo",
    "id": 12,
    "generation": 1
  },
  {
    "name": "Smogmog",
    "id": 110,
    "generation": 1
  },
  {
    "name": "Smogon",
    "id": 109,
    "generation": 1
  },
  {
    "name": "Snibunna",
    "id": 461,
    "generation": 4
  },
  {
    "name": "Sniebel",
    "id": 215,
    "generation": 2
  },
  {
    "name": "Snobilikat",
    "id": 53,
    "generation": 1
  },
  {
    "name": "Snubbull",
    "id": 209,
    "generation": 2
  },
  {
    "name": "Sodachita",
    "id": 516,
    "generation": 5
  },
  {
    "name": "Sodamak",
    "id": 515,
    "generation": 5
  },
  {
    "name": "Somniam",
    "id": 517,
    "generation": 5
  },
  {
    "name": "Somnivora",
    "id": 518,
    "generation": 5
  },
  {
    "name": "Sonnfel",
    "id": 338,
    "generation": 3
  },
  {
    "name": "Sonnflora",
    "id": 192,
    "generation": 2
  },
  {
    "name": "Sonnkern",
    "id": 191,
    "generation": 2
  },
  {
    "name": "Spoink",
    "id": 325,
    "generation": 3
  },
  {
    "name": "Stahlos",
    "id": 208,
    "generation": 2
  },
  {
    "name": "Stalobor",
    "id": 530,
    "generation": 5
  },
  {
    "name": "Staralili",
    "id": 396,
    "generation": 4
  },
  {
    "name": "Staraptor",
    "id": 398,
    "generation": 4
  },
  {
    "name": "Staravia",
    "id": 397,
    "generation": 4
  },
  {
    "name": "Starmie",
    "id": 121,
    "generation": 1
  },
  {
    "name": "Sterndu",
    "id": 120,
    "generation": 1
  },
  {
    "name": "Stolloss",
    "id": 306,
    "generation": 3
  },
  {
    "name": "Stollrak",
    "id": 305,
    "generation": 3
  },
  {
    "name": "Stollunior",
    "id": 304,
    "generation": 3
  },
  {
    "name": "Strawickl",
    "id": 540,
    "generation": 5
  },
  {
    "name": "Strepoli",
    "id": 533,
    "generation": 5
  },
  {
    "name": "Suicune",
    "id": 245,
    "generation": 2
  },
  {
    "name": "Sumpex",
    "id": 260,
    "generation": 3
  },
  {
    "name": "Swaroness",
    "id": 581,
    "generation": 5
  },
  {
    "name": "Symvolara",
    "id": 561,
    "generation": 5
  },
  {
    "name": "Tandrak",
    "id": 691,
    "generation": 6
  },
  {
    "name": "Tangela",
    "id": 114,
    "generation": 1
  },
  {
    "name": "Tangoloss",
    "id": 465,
    "generation": 4
  },
  {
    "name": "Tanhel",
    "id": 374,
    "generation": 3
  },
  {
    "name": "Tannza",
    "id": 204,
    "generation": 2
  },
  {
    "name": "Tarnpignon",
    "id": 590,
    "generation": 5
  },
  {
    "name": "Tauboga",
    "id": 17,
    "generation": 1
  },
  {
    "name": "Tauboss",
    "id": 18,
    "generation": 1
  },
  {
    "name": "Taubsi",
    "id": 16,
    "generation": 1
  },
  {
    "name": "Tauros",
    "id": 128,
    "generation": 1
  },
  {
    "name": "Teddiursa",
    "id": 216,
    "generation": 2
  },
  {
    "name": "Tengulist",
    "id": 275,
    "generation": 3
  },
  {
    "name": "Tentacha",
    "id": 72,
    "generation": 1
  },
  {
    "name": "Tentantel",
    "id": 598,
    "generation": 5
  },
  {
    "name": "Tentoxa",
    "id": 73,
    "generation": 1
  },
  {
    "name": "Terrakium",
    "id": 639,
    "generation": 5
  },
  {
    "name": "Terribark",
    "id": 507,
    "generation": 5
  },
  {
    "name": "Thanathora",
    "id": 689,
    "generation": 6
  },
  {
    "name": "Tobutz",
    "id": 482,
    "generation": 4
  },
  {
    "name": "Togekiss",
    "id": 468,
    "generation": 4
  },
  {
    "name": "Togepi",
    "id": 175,
    "generation": 2
  },
  {
    "name": "Togetic",
    "id": 176,
    "generation": 2
  },
  {
    "name": "Tohaido",
    "id": 319,
    "generation": 3
  },
  {
    "name": "Tornupto",
    "id": 157,
    "generation": 2
  },
  {
    "name": "Toxiped",
    "id": 543,
    "generation": 5
  },
  {
    "name": "Toxiquak",
    "id": 454,
    "generation": 4
  },
  {
    "name": "Tragosso",
    "id": 104,
    "generation": 1
  },
  {
    "name": "Trasla",
    "id": 280,
    "generation": 3
  },
  {
    "name": "Traumato",
    "id": 96,
    "generation": 1
  },
  {
    "name": "Traunfugil",
    "id": 200,
    "generation": 2
  },
  {
    "name": "Traunmagil",
    "id": 429,
    "generation": 4
  },
  {
    "name": "Trikephalo",
    "id": 635,
    "generation": 5
  },
  {
    "name": "Trombork",
    "id": 709,
    "generation": 6
  },
  {
    "name": "Tropius",
    "id": 357,
    "generation": 3
  },
  {
    "name": "Turtok",
    "id": 9,
    "generation": 1
  },
  {
    "name": "Tuska",
    "id": 331,
    "generation": 3
  },
  {
    "name": "Tyracroc",
    "id": 159,
    "generation": 2
  },
  {
    "name": "UHaFnir",
    "id": 715,
    "generation": 6
  },
  {
    "name": "Ultrigaria",
    "id": 70,
    "generation": 1
  },
  {
    "name": "Unratütox",
    "id": 568,
    "generation": 5
  },
  {
    "name": "Ursaring",
    "id": 217,
    "generation": 2
  },
  {
    "name": "Vegichita",
    "id": 512,
    "generation": 5
  },
  {
    "name": "Vegimak",
    "id": 511,
    "generation": 5
  },
  {
    "name": "Venuflibis",
    "id": 455,
    "generation": 4
  },
  {
    "name": "Vesprit",
    "id": 481,
    "generation": 4
  },
  {
    "name": "Vibrava",
    "id": 329,
    "generation": 3
  },
  {
    "name": "Victini",
    "id": 494,
    "generation": 5
  },
  {
    "name": "Vipitis",
    "id": 336,
    "generation": 3
  },
  {
    "name": "Viridium",
    "id": 640,
    "generation": 5
  },
  {
    "name": "Viscargot",
    "id": 705,
    "generation": 6
  },
  {
    "name": "Viscogon",
    "id": 706,
    "generation": 6
  },
  {
    "name": "Viscora",
    "id": 704,
    "generation": 6
  },
  {
    "name": "Vivillon",
    "id": 666,
    "generation": 6
  },
  {
    "name": "Volbeat",
    "id": 313,
    "generation": 3
  },
  {
    "name": "Volcanion",
    "id": 721,
    "generation": 6
  },
  {
    "name": "Voltenso",
    "id": 310,
    "generation": 3
  },
  {
    "name": "Voltilamm",
    "id": 179,
    "generation": 2
  },
  {
    "name": "Voltobal",
    "id": 100,
    "generation": 1
  },
  {
    "name": "Voltolos",
    "id": 642,
    "generation": 5
  },
  {
    "name": "Voltula",
    "id": 596,
    "generation": 5
  },
  {
    "name": "Voluminas",
    "id": 476,
    "generation": 4
  },
  {
    "name": "Vulnona",
    "id": 38,
    "generation": 1
  },
  {
    "name": "Vulpix",
    "id": 37,
    "generation": 1
  },
  {
    "name": "Waaty",
    "id": 180,
    "generation": 2
  },
  {
    "name": "Wablu",
    "id": 333,
    "generation": 3
  },
  {
    "name": "Wadribie",
    "id": 415,
    "generation": 4
  },
  {
    "name": "Wailmer",
    "id": 320,
    "generation": 3
  },
  {
    "name": "Wailord",
    "id": 321,
    "generation": 3
  },
  {
    "name": "Walraisa",
    "id": 365,
    "generation": 3
  },
  {
    "name": "Washakwil",
    "id": 628,
    "generation": 5
  },
  {
    "name": "Wattzapf",
    "id": 595,
    "generation": 5
  },
  {
    "name": "Waumboll",
    "id": 546,
    "generation": 5
  },
  {
    "name": "Waumpel",
    "id": 265,
    "generation": 3
  },
  {
    "name": "Webarak",
    "id": 167,
    "generation": 2
  },
  {
    "name": "Welsar",
    "id": 340,
    "generation": 3
  },
  {
    "name": "Wie-Shu",
    "id": 620,
    "generation": 5
  },
  {
    "name": "Wielie",
    "id": 346,
    "generation": 3
  },
  {
    "name": "Wiesenior",
    "id": 162,
    "generation": 2
  },
  {
    "name": "Wiesor",
    "id": 161,
    "generation": 2
  },
  {
    "name": "Wingull",
    "id": 278,
    "generation": 3
  },
  {
    "name": "Woingenau",
    "id": 202,
    "generation": 2
  },
  {
    "name": "Wonneira",
    "id": 440,
    "generation": 4
  },
  {
    "name": "Wummer",
    "id": 693,
    "generation": 6
  },
  {
    "name": "Xatu",
    "id": 178,
    "generation": 2
  },
  {
    "name": "Xerneas",
    "id": 716,
    "generation": 6
  },
  {
    "name": "Yanma",
    "id": 193,
    "generation": 2
  },
  {
    "name": "Yanmega",
    "id": 469,
    "generation": 4
  },
  {
    "name": "Yorkleff",
    "id": 506,
    "generation": 5
  },
  {
    "name": "Yveltal",
    "id": 717,
    "generation": 6
  },
  {
    "name": "Zapdos",
    "id": 145,
    "generation": 1
  },
  {
    "name": "Zapplalek",
    "id": 603,
    "generation": 5
  },
  {
    "name": "Zapplarang",
    "id": 604,
    "generation": 5
  },
  {
    "name": "Zapplardin",
    "id": 602,
    "generation": 5
  },
  {
    "name": "Zebritz",
    "id": 523,
    "generation": 5
  },
  {
    "name": "Zekrom",
    "id": 644,
    "generation": 5
  },
  {
    "name": "Zigzachs",
    "id": 263,
    "generation": 3
  },
  {
    "name": "Zirpeise",
    "id": 402,
    "generation": 4
  },
  {
    "name": "Zirpurze",
    "id": 401,
    "generation": 4
  },
  {
    "name": "Zobiris",
    "id": 302,
    "generation": 3
  },
  {
    "name": "Zoroark",
    "id": 571,
    "generation": 5
  },
  {
    "name": "Zorua",
    "id": 570,
    "generation": 5
  },
  {
    "name": "Zubat",
    "id": 41,
    "generation": 1
  },
  {
    "name": "Zurrokex",
    "id": 559,
    "generation": 5
  },
  {
    "name": "Zwirrfinst",
    "id": 477,
    "generation": 4
  },
  {
    "name": "Zwirrklop",
    "id": 356,
    "generation": 3
  },
  {
    "name": "Zwirrlicht",
    "id": 355,
    "generation": 3
  },
  {
    "name": "Zwottronin",
    "id": 502,
    "generation": 5
  },
  {
    "name": "Zygarde",
    "id": 718,
    "generation": 6
  },
  {
    "name": "Zytomega",
    "id": 579,
    "generation": 5
  }
];
