// Generated by scripts/generate-pokemon-de.mjs
export const ENGLISH_POKEMON_NAMES: { name: string; id: number; generation: number }[] = [
  {
    "name": "Abomasnow",
    "id": 460,
    "generation": 4
  },
  {
    "name": "Abra",
    "id": 63,
    "generation": 1
  },
  {
    "name": "Absol",
    "id": 359,
    "generation": 3
  },
  {
    "name": "Accelgor",
    "id": 617,
    "generation": 5
  },
  {
    "name": "Aegislash",
    "id": 681,
    "generation": 6
  },
  {
    "name": "Aerodactyl",
    "id": 142,
    "generation": 1
  },
  {
    "name": "Aggron",
    "id": 306,
    "generation": 3
  },
  {
    "name": "Aipom",
    "id": 190,
    "generation": 2
  },
  {
    "name": "Alakazam",
    "id": 65,
    "generation": 1
  },
  {
    "name": "Alomomola",
    "id": 594,
    "generation": 5
  },
  {
    "name": "Altaria",
    "id": 334,
    "generation": 3
  },
  {
    "name": "Amaura",
    "id": 698,
    "generation": 6
  },
  {
    "name": "Ambipom",
    "id": 424,
    "generation": 4
  },
  {
    "name": "Amoonguss",
    "id": 591,
    "generation": 5
  },
  {
    "name": "Ampharos",
    "id": 181,
    "generation": 2
  },
  {
    "name": "Anorith",
    "id": 347,
    "generation": 3
  },
  {
    "name": "Arbok",
    "id": 24,
    "generation": 1
  },
  {
    "name": "Arcanine",
    "id": 59,
    "generation": 1
  },
  {
    "name": "Arceus",
    "id": 493,
    "generation": 4
  },
  {
    "name": "Archen",
    "id": 566,
    "generation": 5
  },
  {
    "name": "Archeops",
    "id": 567,
    "generation": 5
  },
  {
    "name": "Ariados",
    "id": 168,
    "generation": 2
  },
  {
    "name": "Armaldo",
    "id": 348,
    "generation": 3
  },
  {
    "name": "Aromatisse",
    "id": 683,
    "generation": 6
  },
  {
    "name": "Aron",
    "id": 304,
    "generation": 3
  },
  {
    "name": "Articuno",
    "id": 144,
    "generation": 1
  },
  {
    "name": "Audino",
    "id": 531,
    "generation": 5
  },
  {
    "name": "Aurorus",
    "id": 699,
    "generation": 6
  },
  {
    "name": "Avalugg",
    "id": 713,
    "generation": 6
  },
  {
    "name": "Axew",
    "id": 610,
    "generation": 5
  },
  {
    "name": "Azelf",
    "id": 482,
    "generation": 4
  },
  {
    "name": "Azumarill",
    "id": 184,
    "generation": 2
  },
  {
    "name": "Azurill",
    "id": 298,
    "generation": 3
  },
  {
    "name": "Bagon",
    "id": 371,
    "generation": 3
  },
  {
    "name": "Baltoy",
    "id": 343,
    "generation": 3
  },
  {
    "name": "Banette",
    "id": 354,
    "generation": 3
  },
  {
    "name": "Barbaracle",
    "id": 689,
    "generation": 6
  },
  {
    "name": "Barboach",
    "id": 339,
    "generation": 3
  },
  {
    "name": "Basculin",
    "id": 550,
    "generation": 5
  },
  {
    "name": "Bastiodon",
    "id": 411,
    "generation": 4
  },
  {
    "name": "Bayleef",
    "id": 153,
    "generation": 2
  },
  {
    "name": "Beartic",
    "id": 614,
    "generation": 5
  },
  {
    "name": "Beautifly",
    "id": 267,
    "generation": 3
  },
  {
    "name": "Beedrill",
    "id": 15,
    "generation": 1
  },
  {
    "name": "Beheeyem",
    "id": 606,
    "generation": 5
  },
  {
    "name": "Beldum",
    "id": 374,
    "generation": 3
  },
  {
    "name": "Bellossom",
    "id": 182,
    "generation": 2
  },
  {
    "name": "Bellsprout",
    "id": 69,
    "generation": 1
  },
  {
    "name": "Bergmite",
    "id": 712,
    "generation": 6
  },
  {
    "name": "Bibarel",
    "id": 400,
    "generation": 4
  },
  {
    "name": "Bidoof",
    "id": 399,
    "generation": 4
  },
  {
    "name": "Binacle",
    "id": 688,
    "generation": 6
  },
  {
    "name": "Bisharp",
    "id": 625,
    "generation": 5
  },
  {
    "name": "Blastoise",
    "id": 9,
    "generation": 1
  },
  {
    "name": "Blaziken",
    "id": 257,
    "generation": 3
  },
  {
    "name": "Blissey",
    "id": 242,
    "generation": 2
  },
  {
    "name": "Blitzle",
    "id": 522,
    "generation": 5
  },
  {
    "name": "Boldore",
    "id": 525,
    "generation": 5
  },
  {
    "name": "Bonsly",
    "id": 438,
    "generation": 4
  },
  {
    "name": "Bouffalant",
    "id": 626,
    "generation": 5
  },
  {
    "name": "Braixen",
    "id": 654,
    "generation": 6
  },
  {
    "name": "Braviary",
    "id": 628,
    "generation": 5
  },
  {
    "name": "Breloom",
    "id": 286,
    "generation": 3
  },
  {
    "name": "Bronzong",
    "id": 437,
    "generation": 4
  },
  {
    "name": "Bronzor",
    "id": 436,
    "generation": 4
  },
  {
    "name": "Budew",
    "id": 406,
    "generation": 4
  },
  {
    "name": "Buizel",
    "id": 418,
    "generation": 4
  },
  {
    "name": "Bulbasaur",
    "id": 1,
    "generation": 1
  },
  {
    "name": "Buneary",
    "id": 427,
    "generation": 4
  },
  {
    "name": "Bunnelby",
    "id": 659,
    "generation": 6
  },
  {
    "name": "Burmy",
    "id": 412,
    "generation": 4
  },
  {
    "name": "Butterfree",
    "id": 12,
    "generation": 1
  },
  {
    "name": "Cacnea",
    "id": 331,
    "generation": 3
  },
  {
    "name": "Cacturne",
    "id": 332,
    "generation": 3
  },
  {
    "name": "Camerupt",
    "id": 323,
    "generation": 3
  },
  {
    "name": "Carbink",
    "id": 703,
    "generation": 6
  },
  {
    "name": "Carnivine",
    "id": 455,
    "generation": 4
  },
  {
    "name": "Carracosta",
    "id": 565,
    "generation": 5
  },
  {
    "name": "Carvanha",
    "id": 318,
    "generation": 3
  },
  {
    "name": "Cascoon",
    "id": 268,
    "generation": 3
  },
  {
    "name": "Castform",
    "id": 351,
    "generation": 3
  },
  {
    "name": "Caterpie",
    "id": 10,
    "generation": 1
  },
  {
    "name": "Celebi",
    "id": 251,
    "generation": 2
  },
  {
    "name": "Chandelure",
    "id": 609,
    "generation": 5
  },
  {
    "name": "Chansey",
    "id": 113,
    "generation": 1
  },
  {
    "name": "Charizard",
    "id": 6,
    "generation": 1
  },
  {
    "name": "Charmander",
    "id": 4,
    "generation": 1
  },
  {
    "name": "Charmeleon",
    "id": 5,
    "generation": 1
  },
  {
    "name": "Chatot",
    "id": 441,
    "generation": 4
  },
  {
    "name": "Cherrim",
    "id": 421,
    "generation": 4
  },
  {
    "name": "Cherubi",
    "id": 420,
    "generation": 4
  },
  {
    "name": "Chesnaught",
    "id": 652,
    "generation": 6
  },
  {
    "name": "Chespin",
    "id": 650,
    "generation": 6
  },
  {
    "name": "Chikorita",
    "id": 152,
    "generation": 2
  },
  {
    "name": "Chimchar",
    "id": 390,
    "generation": 4
  },
  {
    "name": "Chimecho",
    "id": 358,
    "generation": 3
  },
  {
    "name": "Chinchou",
    "id": 170,
    "generation": 2
  },
  {
    "name": "Chingling",
    "id": 433,
    "generation": 4
  },
  {
    "name": "Cinccino",
    "id": 573,
    "generation": 5
  },
  {
    "name": "Clamperl",
    "id": 366,
    "generation": 3
  },
  {
    "name": "Clauncher",
    "id": 692,
    "generation": 6
  },
  {
    "name": "Clawitzer",
    "id": 693,
    "generation": 6
  },
  {
    "name": "Claydol",
    "id": 344,
    "generation": 3
  },
  {
    "name": "Clefable",
    "id": 36,
    "generation": 1
  },
  {
    "name": "Clefairy",
    "id": 35,
    "generation": 1
  },
  {
    "name": "Cleffa",
    "id": 173,
    "generation": 2
  },
  {
    "name": "Cloyster",
    "id": 91,
    "generation": 1
  },
  {
    "name": "Cobalion",
    "id": 638,
    "generation": 5
  },
  {
    "name": "Cofagrigus",
    "id": 563,
    "generation": 5
  },
  {
    "name": "Combee",
    "id": 415,
    "generation": 4
  },
  {
    "name": "Combusken",
    "id": 256,
    "generation": 3
  },
  {
    "name": "Conkeldurr",
    "id": 534,
    "generation": 5
  },
  {
    "name": "Corphish",
    "id": 341,
    "generation": 3
  },
  {
    "name": "Corsola",
    "id": 222,
    "generation": 2
  },
  {
    "name": "Cottonee",
    "id": 546,
    "generation": 5
  },
  {
    "name": "Cradily",
    "id": 346,
    "generation": 3
  },
  {
    "name": "Cranidos",
    "id": 408,
    "generation": 4
  },
  {
    "name": "Crawdaunt",
    "id": 342,
    "generation": 3
  },
  {
    "name": "Cresselia",
    "id": 488,
    "generation": 4
  },
  {
    "name": "Croagunk",
    "id": 453,
    "generation": 4
  },
  {
    "name": "Crobat",
    "id": 169,
    "generation": 2
  },
  {
    "name": "Croconaw",
    "id": 159,
    "generation": 2
  },
  {
    "name": "Crustle",
    "id": 558,
    "generation": 5
  },
  {
    "name": "Cryogonal",
    "id": 615,
    "generation": 5
  },
  {
    "name": "Cubchoo",
    "id": 613,
    "generation": 5
  },
  {
    "name": "Cubone",
    "id": 104,
    "generation": 1
  },
  {
    "name": "Cyndaquil",
    "id": 155,
    "generation": 2
  },
  {
    "name": "Darkrai",
    "id": 491,
    "generation": 4
  },
  {
    "name": "Darmanitan",
    "id": 555,
    "generation": 5
  },
  {
    "name": "Darumaka",
    "id": 554,
    "generation": 5
  },
  {
    "name": "Dedenne",
    "id": 702,
    "generation": 6
  },
  {
    "name": "Deerling",
    "id": 585,
    "generation": 5
  },
  {
    "name": "Deino",
    "id": 633,
    "generation": 5
  },
  {
    "name": "Delcatty",
    "id": 301,
    "generation": 3
  },
  {
    "name": "Delibird",
    "id": 225,
    "generation": 2
  },
  {
    "name": "Delphox",
    "id": 655,
    "generation": 6
  },
  {
    "name": "Deoxys",
    "id": 386,
    "generation": 3
  },
  {
    "name": "Dewgong",
    "id": 87,
    "generation": 1
  },
  {
    "name": "Dewott",
    "id": 502,
    "generation": 5
  },
  {
    "name": "Dialga",
    "id": 483,
    "generation": 4
  },
  {
    "name": "Diancie",
    "id": 719,
    "generation": 6
  },
  {
    "name": "Diggersby",
    "id": 660,
    "generation": 6
  },
  {
    "name": "Diglett",
    "id": 50,
    "generation": 1
  },
  {
    "name": "Ditto",
    "id": 132,
    "generation": 1
  },
  {
    "name": "Dodrio",
    "id": 85,
    "generation": 1
  },
  {
    "name": "Doduo",
    "id": 84,
    "generation": 1
  },
  {
    "name": "Donphan",
    "id": 232,
    "generation": 2
  },
  {
    "name": "Doublade",
    "id": 680,
    "generation": 6
  },
  {
    "name": "Dragalge",
    "id": 691,
    "generation": 6
  },
  {
    "name": "Dragonair",
    "id": 148,
    "generation": 1
  },
  {
    "name": "Dragonite",
    "id": 149,
    "generation": 1
  },
  {
    "name": "Drapion",
    "id": 452,
    "generation": 4
  },
  {
    "name": "Dratini",
    "id": 147,
    "generation": 1
  },
  {
    "name": "Drifblim",
    "id": 426,
    "generation": 4
  },
  {
    "name": "Drifloon",
    "id": 425,
    "generation": 4
  },
  {
    "name": "Drilbur",
    "id": 529,
    "generation": 5
  },
  {
    "name": "Drowzee",
    "id": 96,
    "generation": 1
  },
  {
    "name": "Druddigon",
    "id": 621,
    "generation": 5
  },
  {
    "name": "Ducklett",
    "id": 580,
    "generation": 5
  },
  {
    "name": "Dugtrio",
    "id": 51,
    "generation": 1
  },
  {
    "name": "Dunsparce",
    "id": 206,
    "generation": 2
  },
  {
    "name": "Duosion",
    "id": 578,
    "generation": 5
  },
  {
    "name": "Durant",
    "id": 632,
    "generation": 5
  },
  {
    "name": "Dusclops",
    "id": 356,
    "generation": 3
  },
  {
    "name": "Dusknoir",
    "id": 477,
    "generation": 4
  },
  {
    "name": "Duskull",
    "id": 355,
    "generation": 3
  },
  {
    "name": "Dustox",
    "id": 269,
    "generation": 3
  },
  {
    "name": "Dwebble",
    "id": 557,
    "generation": 5
  },
  {
    "name": "Eelektrik",
    "id": 603,
    "generation": 5
  },
  {
    "name": "Eelektross",
    "id": 604,
    "generation": 5
  },
  {
    "name": "Eevee",
    "id": 133,
    "generation": 1
  },
  {
    "name": "Ekans",
    "id": 23,
    "generation": 1
  },
  {
    "name": "Electabuzz",
    "id": 125,
    "generation": 1
  },
  {
    "name": "Electivire",
    "id": 466,
    "generation": 4
  },
  {
    "name": "Electrike",
    "id": 309,
    "generation": 3
  },
  {
    "name": "Electrode",
    "id": 101,
    "generation": 1
  },
  {
    "name": "Elekid",
    "id": 239,
    "generation": 2
  },
  {
    "name": "Elgyem",
    "id": 605,
    "generation": 5
  },
  {
    "name": "Emboar",
    "id": 500,
    "generation": 5
  },
  {
    "name": "Emolga",
    "id": 587,
    "generation": 5
  },
  {
    "name": "Empoleon",
    "id": 395,
    "generation": 4
  },
  {
    "name": "Entei",
    "id": 244,
    "generation": 2
  },
  {
    "name": "Escavalier",
    "id": 589,
    "generation": 5
  },
  {
    "name": "Espeon",
    "id": 196,
    "generation": 2
  },
  {
    "name": "Espurr",
    "id": 677,
    "generation": 6
  },
  {
    "name": "Excadrill",
    "id": 530,
    "generation": 5
  },
  {
    "name": "Exeggcute",
    "id": 102,
    "generation": 1
  },
  {
    "name": "Exeggutor",
    "id": 103,
    "generation": 1
  },
  {
    "name": "Exploud",
    "id": 295,
    "generation": 3
  },
  {
    "name": "Farfetch’d",
    "id": 83,
    "generation": 1
  },
  {
    "name": "Fearow",
    "id": 22,
    "generation": 1
  },
  {
    "name": "Feebas",
    "id": 349,
    "generation": 3
  },
  {
    "name": "Fennekin",
    "id": 653,
    "generation": 6
  },
  {
    "name": "Feraligatr",
    "id": 160,
    "generation": 2
  },
  {
    "name": "Ferroseed",
    "id": 597,
    "generation": 5
  },
  {
    "name": "Ferrothorn",
    "id": 598,
    "generation": 5
  },
  {
    "name": "Finneon",
    "id": 456,
    "generation": 4
  },
  {
    "name": "Flaaffy",
    "id": 180,
    "generation": 2
  },
  {
    "name": "Flabébé",
    "id": 669,
    "generation": 6
  },
  {
    "name": "Flareon",
    "id": 136,
    "generation": 1
  },
  {
    "name": "Fletchinder",
    "id": 662,
    "generation": 6
  },
  {
    "name": "Fletchling",
    "id": 661,
    "generation": 6
  },
  {
    "name": "Floatzel",
    "id": 419,
    "generation": 4
  },
  {
    "name": "Floette",
    "id": 670,
    "generation": 6
  },
  {
    "name": "Florges",
    "id": 671,
    "generation": 6
  },
  {
    "name": "Flygon",
    "id": 330,
    "generation": 3
  },
  {
    "name": "Foongus",
    "id": 590,
    "generation": 5
  },
  {
    "name": "Forretress",
    "id": 205,
    "generation": 2
  },
  {
    "name": "Fraxure",
    "id": 611,
    "generation": 5
  },
  {
    "name": "Frillish",
    "id": 592,
    "generation": 5
  },
  {
    "name": "Froakie",
    "id": 656,
    "generation": 6
  },
  {
    "name": "Frogadier",
    "id": 657,
    "generation": 6
  },
  {
    "name": "Froslass",
    "id": 478,
    "generation": 4
  },
  {
    "name": "Furfrou",
    "id": 676,
    "generation": 6
  },
  {
    "name": "Furret",
    "id": 162,
    "generation": 2
  },
  {
    "name": "Gabite",
    "id": 444,
    "generation": 4
  },
  {
    "name": "Gallade",
    "id": 475,
    "generation": 4
  },
  {
    "name": "Galvantula",
    "id": 596,
    "generation": 5
  },
  {
    "name": "Garbodor",
    "id": 569,
    "generation": 5
  },
  {
    "name": "Garchomp",
    "id": 445,
    "generation": 4
  },
  {
    "name": "Gardevoir",
    "id": 282,
    "generation": 3
  },
  {
    "name": "Gastly",
    "id": 92,
    "generation": 1
  },
  {
    "name": "Gastrodon",
    "id": 423,
    "generation": 4
  },
  {
    "name": "Genesect",
    "id": 649,
    "generation": 5
  },
  {
    "name": "Gengar",
    "id": 94,
    "generation": 1
  },
  {
    "name": "Geodude",
    "id": 74,
    "generation": 1
  },
  {
    "name": "Gible",
    "id": 443,
    "generation": 4
  },
  {
    "name": "Gigalith",
    "id": 526,
    "generation": 5
  },
  {
    "name": "Girafarig",
    "id": 203,
    "generation": 2
  },
  {
    "name": "Giratina",
    "id": 487,
    "generation": 4
  },
  {
    "name": "Glaceon",
    "id": 471,
    "generation": 4
  },
  {
    "name": "Glalie",
    "id": 362,
    "generation": 3
  },
  {
    "name": "Glameow",
    "id": 431,
    "generation": 4
  },
  {
    "name": "Gligar",
    "id": 207,
    "generation": 2
  },
  {
    "name": "Gliscor",
    "id": 472,
    "generation": 4
  },
  {
    "name": "Gloom",
    "id": 44,
    "generation": 1
  },
  {
    "name": "Gogoat",
    "id": 673,
    "generation": 6
  },
  {
    "name": "Golbat",
    "id": 42,
    "generation": 1
  },
  {
    "name": "Goldeen",
    "id": 118,
    "generation": 1
  },
  {
    "name": "Golduck",
    "id": 55,
    "generation": 1
  },
  {
    "name": "Golem",
    "id": 76,
    "generation": 1
  },
  {
    "name": "Golett",
    "id": 622,
    "generation": 5
  },
  {
    "name": "Golurk",
    "id": 623,
    "generation": 5
  },
  {
    "name": "Goodra",
    "id": 706,
    "generation": 6
  },
  {
    "name": "Goomy",
    "id": 704,
    "generation": 6
  },
  {
    "name": "Gorebyss",
    "id": 368,
    "generation": 3
  },
  {
    "name": "Gothita",
    "id": 574,
    "generation": 5
  },
  {
    "name": "Gothitelle",
    "id": 576,
    "generation": 5
  },
  {
    "name": "Gothorita",
    "id": 575,
    "generation": 5
  },
  {
    "name": "Gourgeist",
    "id": 711,
    "generation": 6
  },
  {
    "name": "Granbull",
    "id": 210,
    "generation": 2
  },
  {
    "name": "Graveler",
    "id": 75,
    "generation": 1
  },
  {
    "name": "Greninja",
    "id": 658,
    "generation": 6
  },
  {
    "name": "Grimer",
    "id": 88,
    "generation": 1
  },
  {
    "name": "Grotle",
    "id": 388,
    "generation": 4
  },
  {
    "name": "Groudon",
    "id": 383,
    "generation": 3
  },
  {
    "name": "Grovyle",
    "id": 253,
    "generation": 3
  },
  {
    "name": "Growlithe",
    "id": 58,
    "generation": 1
  },
  {
    "name": "Grumpig",
    "id": 326,
    "generation": 3
  },
  {
    "name": "Gulpin",
    "id": 316,
    "generation": 3
  },
  {
    "name": "Gurdurr",
    "id": 533,
    "generation": 5
  },
  {
    "name": "Gyarados",
    "id": 130,
    "generation": 1
  },
  {
    "name": "Happiny",
    "id": 440,
    "generation": 4
  },
  {
    "name": "Hariyama",
    "id": 297,
    "generation": 3
  },
  {
    "name": "Haunter",
    "id": 93,
    "generation": 1
  },
  {
    "name": "Hawlucha",
    "id": 701,
    "generation": 6
  },
  {
    "name": "Haxorus",
    "id": 612,
    "generation": 5
  },
  {
    "name": "Heatmor",
    "id": 631,
    "generation": 5
  },
  {
    "name": "Heatran",
    "id": 485,
    "generation": 4
  },
  {
    "name": "Heliolisk",
    "id": 695,
    "generation": 6
  },
  {
    "name": "Helioptile",
    "id": 694,
    "generation": 6
  },
  {
    "name": "Heracross",
    "id": 214,
    "generation": 2
  },
  {
    "name": "Herdier",
    "id": 507,
    "generation": 5
  },
  {
    "name": "Hippopotas",
    "id": 449,
    "generation": 4
  },
  {
    "name": "Hippowdon",
    "id": 450,
    "generation": 4
  },
  {
    "name": "Hitmonchan",
    "id": 107,
    "generation": 1
  },
  {
    "name": "Hitmonlee",
    "id": 106,
    "generation": 1
  },
  {
    "name": "Hitmontop",
    "id": 237,
    "generation": 2
  },
  {
    "name": "Ho-Oh",
    "id": 250,
    "generation": 2
  },
  {
    "name": "Honchkrow",
    "id": 430,
    "generation": 4
  },
  {
    "name": "Honedge",
    "id": 679,
    "generation": 6
  },
  {
    "name": "Hoopa",
    "id": 720,
    "generation": 6
  },
  {
    "name": "Hoothoot",
    "id": 163,
    "generation": 2
  },
  {
    "name": "Hoppip",
    "id": 187,
    "generation": 2
  },
  {
    "name": "Horsea",
    "id": 116,
    "generation": 1
  },
  {
    "name": "Houndoom",
    "id": 229,
    "generation": 2
  },
  {
    "name": "Houndour",
    "id": 228,
    "generation": 2
  },
  {
    "name": "Huntail",
    "id": 367,
    "generation": 3
  },
  {
    "name": "Hydreigon",
    "id": 635,
    "generation": 5
  },
  {
    "name": "Hypno",
    "id": 97,
    "generation": 1
  },
  {
    "name": "Igglybuff",
    "id": 174,
    "generation": 2
  },
  {
    "name": "Illumise",
    "id": 314,
    "generation": 3
  },
  {
    "name": "Infernape",
    "id": 392,
    "generation": 4
  },
  {
    "name": "Inkay",
    "id": 686,
    "generation": 6
  },
  {
    "name": "Ivysaur",
    "id": 2,
    "generation": 1
  },
  {
    "name": "Jellicent",
    "id": 593,
    "generation": 5
  },
  {
    "name": "Jigglypuff",
    "id": 39,
    "generation": 1
  },
  {
    "name": "Jirachi",
    "id": 385,
    "generation": 3
  },
  {
    "name": "Jolteon",
    "id": 135,
    "generation": 1
  },
  {
    "name": "Joltik",
    "id": 595,
    "generation": 5
  },
  {
    "name": "Jumpluff",
    "id": 189,
    "generation": 2
  },
  {
    "name": "Jynx",
    "id": 124,
    "generation": 1
  },
  {
    "name": "Kabuto",
    "id": 140,
    "generation": 1
  },
  {
    "name": "Kabutops",
    "id": 141,
    "generation": 1
  },
  {
    "name": "Kadabra",
    "id": 64,
    "generation": 1
  },
  {
    "name": "Kakuna",
    "id": 14,
    "generation": 1
  },
  {
    "name": "Kangaskhan",
    "id": 115,
    "generation": 1
  },
  {
    "name": "Karrablast",
    "id": 588,
    "generation": 5
  },
  {
    "name": "Kecleon",
    "id": 352,
    "generation": 3
  },
  {
    "name": "Keldeo",
    "id": 647,
    "generation": 5
  },
  {
    "name": "Kingdra",
    "id": 230,
    "generation": 2
  },
  {
    "name": "Kingler",
    "id": 99,
    "generation": 1
  },
  {
    "name": "Kirlia",
    "id": 281,
    "generation": 3
  },
  {
    "name": "Klang",
    "id": 600,
    "generation": 5
  },
  {
    "name": "Klefki",
    "id": 707,
    "generation": 6
  },
  {
    "name": "Klink",
    "id": 599,
    "generation": 5
  },
  {
    "name": "Klinklang",
    "id": 601,
    "generation": 5
  },
  {
    "name": "Koffing",
    "id": 109,
    "generation": 1
  },
  {
    "name": "Krabby",
    "id": 98,
    "generation": 1
  },
  {
    "name": "Kricketot",
    "id": 401,
    "generation": 4
  },
  {
    "name": "Kricketune",
    "id": 402,
    "generation": 4
  },
  {
    "name": "Krokorok",
    "id": 552,
    "generation": 5
  },
  {
    "name": "Krookodile",
    "id": 553,
    "generation": 5
  },
  {
    "name": "Kyogre",
    "id": 382,
    "generation": 3
  },
  {
    "name": "Kyurem",
    "id": 646,
    "generation": 5
  },
  {
    "name": "Lairon",
    "id": 305,
    "generation": 3
  },
  {
    "name": "Lampent",
    "id": 608,
    "generation": 5
  },
  {
    "name": "Landorus",
    "id": 645,
    "generation": 5
  },
  {
    "name": "Lanturn",
    "id": 171,
    "generation": 2
  },
  {
    "name": "Lapras",
    "id": 131,
    "generation": 1
  },
  {
    "name": "Larvesta",
    "id": 636,
    "generation": 5
  },
  {
    "name": "Larvitar",
    "id": 246,
    "generation": 2
  },
  {
    "name": "Latias",
    "id": 380,
    "generation": 3
  },
  {
    "name": "Latios",
    "id": 381,
    "generation": 3
  },
  {
    "name": "Leafeon",
    "id": 470,
    "generation": 4
  },
  {
    "name": "Leavanny",
    "id": 542,
    "generation": 5
  },
  {
    "name": "Ledian",
    "id": 166,
    "generation": 2
  },
  {
    "name": "Ledyba",
    "id": 165,
    "generation": 2
  },
  {
    "name": "Lickilicky",
    "id": 463,
    "generation": 4
  },
  {
    "name": "Lickitung",
    "id": 108,
    "generation": 1
  },
  {
    "name": "Liepard",
    "id": 510,
    "generation": 5
  },
  {
    "name": "Lileep",
    "id": 345,
    "generation": 3
  },
  {
    "name": "Lilligant",
    "id": 549,
    "generation": 5
  },
  {
    "name": "Lillipup",
    "id": 506,
    "generation": 5
  },
  {
    "name": "Linoone",
    "id": 264,
    "generation": 3
  },
  {
    "name": "Litleo",
    "id": 667,
    "generation": 6
  },
  {
    "name": "Litwick",
    "id": 607,
    "generation": 5
  },
  {
    "name": "Lombre",
    "id": 271,
    "generation": 3
  },
  {
    "name": "Lopunny",
    "id": 428,
    "generation": 4
  },
  {
    "name": "Lotad",
    "id": 270,
    "generation": 3
  },
  {
    "name": "Loudred",
    "id": 294,
    "generation": 3
  },
  {
    "name": "Lucario",
    "id": 448,
    "generation": 4
  },
  {
    "name": "Ludicolo",
    "id": 272,
    "generation": 3
  },
  {
    "name": "Lugia",
    "id": 249,
    "generation": 2
  },
  {
    "name": "Lumineon",
    "id": 457,
    "generation": 4
  },
  {
    "name": "Lunatone",
    "id": 337,
    "generation": 3
  },
  {
    "name": "Luvdisc",
    "id": 370,
    "generation": 3
  },
  {
    "name": "Luxio",
    "id": 404,
    "generation": 4
  },
  {
    "name": "Luxray",
    "id": 405,
    "generation": 4
  },
  {
    "name": "Machamp",
    "id": 68,
    "generation": 1
  },
  {
    "name": "Machoke",
    "id": 67,
    "generation": 1
  },
  {
    "name": "Machop",
    "id": 66,
    "generation": 1
  },
  {
    "name": "Magby",
    "id": 240,
    "generation": 2
  },
  {
    "name": "Magcargo",
    "id": 219,
    "generation": 2
  },
  {
    "name": "Magikarp",
    "id": 129,
    "generation": 1
  },
  {
    "name": "Magmar",
    "id": 126,
    "generation": 1
  },
  {
    "name": "Magmortar",
    "id": 467,
    "generation": 4
  },
  {
    "name": "Magnemite",
    "id": 81,
    "generation": 1
  },
  {
    "name": "Magneton",
    "id": 82,
    "generation": 1
  },
  {
    "name": "Magnezone",
    "id": 462,
    "generation": 4
  },
  {
    "name": "Makuhita",
    "id": 296,
    "generation": 3
  },
  {
    "name": "Malamar",
    "id": 687,
    "generation": 6
  },
  {
    "name": "Mamoswine",
    "id": 473,
    "generation": 4
  },
  {
    "name": "Manaphy",
    "id": 490,
    "generation": 4
  },
  {
    "name": "Mandibuzz",
    "id": 630,
    "generation": 5
  },
  {
    "name": "Manectric",
    "id": 310,
    "generation": 3
  },
  {
    "name": "Mankey",
    "id": 56,
    "generation": 1
  },
  {
    "name": "Mantine",
    "id": 226,
    "generation": 2
  },
  {
    "name": "Mantyke",
    "id": 458,
    "generation": 4
  },
  {
    "name": "Maractus",
    "id": 556,
    "generation": 5
  },
  {
    "name": "Mareep",
    "id": 179,
    "generation": 2
  },
  {
    "name": "Marill",
    "id": 183,
    "generation": 2
  },
  {
    "name": "Marowak",
    "id": 105,
    "generation": 1
  },
  {
    "name": "Marshtomp",
    "id": 259,
    "generation": 3
  },
  {
    "name": "Masquerain",
    "id": 284,
    "generation": 3
  },
  {
    "name": "Mawile",
    "id": 303,
    "generation": 3
  },
  {
    "name": "Medicham",
    "id": 308,
    "generation": 3
  },
  {
    "name": "Meditite",
    "id": 307,
    "generation": 3
  },
  {
    "name": "Meganium",
    "id": 154,
    "generation": 2
  },
  {
    "name": "Meloetta",
    "id": 648,
    "generation": 5
  },
  {
    "name": "Meowstic",
    "id": 678,
    "generation": 6
  },
  {
    "name": "Meowth",
    "id": 52,
    "generation": 1
  },
  {
    "name": "Mesprit",
    "id": 481,
    "generation": 4
  },
  {
    "name": "Metagross",
    "id": 376,
    "generation": 3
  },
  {
    "name": "Metang",
    "id": 375,
    "generation": 3
  },
  {
    "name": "Metapod",
    "id": 11,
    "generation": 1
  },
  {
    "name": "Mew",
    "id": 151,
    "generation": 1
  },
  {
    "name": "Mewtwo",
    "id": 150,
    "generation": 1
  },
  {
    "name": "Mienfoo",
    "id": 619,
    "generation": 5
  },
  {
    "name": "Mienshao",
    "id": 620,
    "generation": 5
  },
  {
    "name": "Mightyena",
    "id": 262,
    "generation": 3
  },
  {
    "name": "Milotic",
    "id": 350,
    "generation": 3
  },
  {
    "name": "Miltank",
    "id": 241,
    "generation": 2
  },
  {
    "name": "Mime Jr.",
    "id": 439,
    "generation": 4
  },
  {
    "name": "Minccino",
    "id": 572,
    "generation": 5
  },
  {
    "name": "Minun",
    "id": 312,
    "generation": 3
  },
  {
    "name": "Misdreavus",
    "id": 200,
    "generation": 2
  },
  {
    "name": "Mismagius",
    "id": 429,
    "generation": 4
  },
  {
    "name": "Moltres",
    "id": 146,
    "generation": 1
  },
  {
    "name": "Monferno",
    "id": 391,
    "generation": 4
  },
  {
    "name": "Mothim",
    "id": 414,
    "generation": 4
  },
  {
    "name": "Mr. Mime",
    "id": 122,
    "generation": 1
  },
  {
    "name": "Mudkip",
    "id": 258,
    "generation": 3
  },
  {
    "name": "Muk",
    "id": 89,
    "generation": 1
  },
  {
    "name": "Munchlax",
    "id": 446,
    "generation": 4
  },
  {
    "name": "Munna",
    "id": 517,
    "generation": 5
  },
  {
    "name": "Murkrow",
    "id": 198,
    "generation": 2
  },
  {
    "name": "Musharna",
    "id": 518,
    "generation": 5
  },
  {
    "name": "Natu",
    "id": 177,
    "generation": 2
  },
  {
    "name": "Nidoking",
    "id": 34,
    "generation": 1
  },
  {
    "name": "Nidoqueen",
    "id": 31,
    "generation": 1
  },
  {
    "name": "Nidoran♀",
    "id": 29,
    "generation": 1
  },
  {
    "name": "Nidoran♂",
    "id": 32,
    "generation": 1
  },
  {
    "name": "Nidorina",
    "id": 30,
    "generation": 1
  },
  {
    "name": "Nidorino",
    "id": 33,
    "generation": 1
  },
  {
    "name": "Nincada",
    "id": 290,
    "generation": 3
  },
  {
    "name": "Ninetales",
    "id": 38,
    "generation": 1
  },
  {
    "name": "Ninjask",
    "id": 291,
    "generation": 3
  },
  {
    "name": "Noctowl",
    "id": 164,
    "generation": 2
  },
  {
    "name": "Noibat",
    "id": 714,
    "generation": 6
  },
  {
    "name": "Noivern",
    "id": 715,
    "generation": 6
  },
  {
    "name": "Nosepass",
    "id": 299,
    "generation": 3
  },
  {
    "name": "Numel",
    "id": 322,
    "generation": 3
  },
  {
    "name": "Nuzleaf",
    "id": 274,
    "generation": 3
  },
  {
    "name": "Octillery",
    "id": 224,
    "generation": 2
  },
  {
    "name": "Oddish",
    "id": 43,
    "generation": 1
  },
  {
    "name": "Omanyte",
    "id": 138,
    "generation": 1
  },
  {
    "name": "Omastar",
    "id": 139,
    "generation": 1
  },
  {
    "name": "Onix",
    "id": 95,
    "generation": 1
  },
  {
    "name": "Oshawott",
    "id": 501,
    "generation": 5
  },
  {
    "name": "Pachirisu",
    "id": 417,
    "generation": 4
  },
  {
    "name": "Palkia",
    "id": 484,
    "generation": 4
  },
  {
    "name": "Palpitoad",
    "id": 536,
    "generation": 5
  },
  {
    "name": "Pancham",
    "id": 674,
    "generation": 6
  },
  {
    "name": "Pangoro",
    "id": 675,
    "generation": 6
  },
  {
    "name": "Panpour",
    "id": 515,
    "generation": 5
  },
  {
    "name": "Pansear",
    "id": 513,
    "generation": 5
  },
  {
    "name": "Paras",
    "id": 46,
    "generation": 1
  },
  {
    "name": "Parasect",
    "id": 47,
    "generation": 1
  },
  {
    "name": "Patrat",
    "id": 504,
    "generation": 5
  },
  {
    "name": "Pawniard",
    "id": 624,
    "generation": 5
  },
  {
    "name": "Pelipper",
    "id": 279,
    "generation": 3
  },
  {
    "name": "Persian",
    "id": 53,
    "generation": 1
  },
  {
    "name": "Petilil",
    "id": 548,
    "generation": 5
  },
  {
    "name": "Phanpy",
    "id": 231,
    "generation": 2
  },
  {
    "name": "Phantump",
    "id": 708,
    "generation": 6
  },
  {
    "name": "Phione",
    "id": 489,
    "generation": 4
  },
  {
    "name": "Pichu",
    "id": 172,
    "generation": 2
  },
  {
    "name": "Pidgeot",
    "id": 18,
    "generation": 1
  },
  {
    "name": "Pidgeotto",
    "id": 17,
    "generation": 1
  },
  {
    "name": "Pidgey",
    "id": 16,
    "generation": 1
  },
  {
    "name": "Pidove",
    "id": 519,
    "generation": 5
  },
  {
    "name": "Pignite",
    "id": 499,
    "generation": 5
  },
  {
    "name": "Pikachu",
    "id": 25,
    "generation": 1
  },
  {
    "name": "Piloswine",
    "id": 221,
    "generation": 2
  },
  {
    "name": "Pineco",
    "id": 204,
    "generation": 2
  },
  {
    "name": "Pinsir",
    "id": 127,
    "generation": 1
  },
  {
    "name": "Piplup",
    "id": 393,
    "generation": 4
  },
  {
    "name": "Plusle",
    "id": 311,
    "generation": 3
  },
  {
    "name": "Politoed",
    "id": 186,
    "generation": 2
  },
  {
    "name": "Poliwag",
    "id": 60,
    "generation": 1
  },
  {
    "name": "Poliwhirl",
    "id": 61,
    "generation": 1
  },
  {
    "name": "Poliwrath",
    "id": 62,
    "generation": 1
  },
  {
    "name": "Ponyta",
    "id": 77,
    "generation": 1
  },
  {
    "name": "Poochyena",
    "id": 261,
    "generation": 3
  },
  {
    "name": "Porygon",
    "id": 137,
    "generation": 1
  },
  {
    "name": "Porygon-Z",
    "id": 474,
    "generation": 4
  },
  {
    "name": "Porygon2",
    "id": 233,
    "generation": 2
  },
  {
    "name": "Primeape",
    "id": 57,
    "generation": 1
  },
  {
    "name": "Prinplup",
    "id": 394,
    "generation": 4
  },
  {
    "name": "Probopass",
    "id": 476,
    "generation": 4
  },
  {
    "name": "Psyduck",
    "id": 54,
    "generation": 1
  },
  {
    "name": "Pumpkaboo",
    "id": 710,
    "generation": 6
  },
  {
    "name": "Pupitar",
    "id": 247,
    "generation": 2
  },
  {
    "name": "Purrloin",
    "id": 509,
    "generation": 5
  },
  {
    "name": "Purugly",
    "id": 432,
    "generation": 4
  },
  {
    "name": "Pyroar",
    "id": 668,
    "generation": 6
  },
  {
    "name": "Quagsire",
    "id": 195,
    "generation": 2
  },
  {
    "name": "Quilava",
    "id": 156,
    "generation": 2
  },
  {
    "name": "Quilladin",
    "id": 651,
    "generation": 6
  },
  {
    "name": "Qwilfish",
    "id": 211,
    "generation": 2
  },
  {
    "name": "Raichu",
    "id": 26,
    "generation": 1
  },
  {
    "name": "Raikou",
    "id": 243,
    "generation": 2
  },
  {
    "name": "Ralts",
    "id": 280,
    "generation": 3
  },
  {
    "name": "Rampardos",
    "id": 409,
    "generation": 4
  },
  {
    "name": "Rapidash",
    "id": 78,
    "generation": 1
  },
  {
    "name": "Raticate",
    "id": 20,
    "generation": 1
  },
  {
    "name": "Rattata",
    "id": 19,
    "generation": 1
  },
  {
    "name": "Rayquaza",
    "id": 384,
    "generation": 3
  },
  {
    "name": "Regice",
    "id": 378,
    "generation": 3
  },
  {
    "name": "Regigigas",
    "id": 486,
    "generation": 4
  },
  {
    "name": "Regirock",
    "id": 377,
    "generation": 3
  },
  {
    "name": "Registeel",
    "id": 379,
    "generation": 3
  },
  {
    "name": "Relicanth",
    "id": 369,
    "generation": 3
  },
  {
    "name": "Remoraid",
    "id": 223,
    "generation": 2
  },
  {
    "name": "Reshiram",
    "id": 643,
    "generation": 5
  },
  {
    "name": "Reuniclus",
    "id": 579,
    "generation": 5
  },
  {
    "name": "Rhydon",
    "id": 112,
    "generation": 1
  },
  {
    "name": "Rhyhorn",
    "id": 111,
    "generation": 1
  },
  {
    "name": "Rhyperior",
    "id": 464,
    "generation": 4
  },
  {
    "name": "Riolu",
    "id": 447,
    "generation": 4
  },
  {
    "name": "Roggenrola",
    "id": 524,
    "generation": 5
  },
  {
    "name": "Roselia",
    "id": 315,
    "generation": 3
  },
  {
    "name": "Roserade",
    "id": 407,
    "generation": 4
  },
  {
    "name": "Rotom",
    "id": 479,
    "generation": 4
  },
  {
    "name": "Rufflet",
    "id": 627,
    "generation": 5
  },
  {
    "name": "Sableye",
    "id": 302,
    "generation": 3
  },
  {
    "name": "Salamence",
    "id": 373,
    "generation": 3
  },
  {
    "name": "Samurott",
    "id": 503,
    "generation": 5
  },
  {
    "name": "Sandile",
    "id": 551,
    "generation": 5
  },
  {
    "name": "Sandshrew",
    "id": 27,
    "generation": 1
  },
  {
    "name": "Sandslash",
    "id": 28,
    "generation": 1
  },
  {
    "name": "Sawk",
    "id": 539,
    "generation": 5
  },
  {
    "name": "Sawsbuck",
    "id": 586,
    "generation": 5
  },
  {
    "name": "Scatterbug",
    "id": 664,
    "generation": 6
  },
  {
    "name": "Sceptile",
    "id": 254,
    "generation": 3
  },
  {
    "name": "Scizor",
    "id": 212,
    "generation": 2
  },
  {
    "name": "Scolipede",
    "id": 545,
    "generation": 5
  },
  {
    "name": "Scrafty",
    "id": 560,
    "generation": 5
  },
  {
    "name": "Scraggy",
    "id": 559,
    "generation": 5
  },
  {
    "name": "Scyther",
    "id": 123,
    "generation": 1
  },
  {
    "name": "Seadra",
    "id": 117,
    "generation": 1
  },
  {
    "name": "Seaking",
    "id": 119,
    "generation": 1
  },
  {
    "name": "Sealeo",
    "id": 364,
    "generation": 3
  },
  {
    "name": "Seedot",
    "id": 273,
    "generation": 3
  },
  {
    "name": "Seel",
    "id": 86,
    "generation": 1
  },
  {
    "name": "Seismitoad",
    "id": 537,
    "generation": 5
  },
  {
    "name": "Sentret",
    "id": 161,
    "generation": 2
  },
  {
    "name": "Serperior",
    "id": 497,
    "generation": 5
  },
  {
    "name": "Servine",
    "id": 496,
    "generation": 5
  },
  {
    "name": "Seviper",
    "id": 336,
    "generation": 3
  },
  {
    "name": "Sewaddle",
    "id": 540,
    "generation": 5
  },
  {
    "name": "Sharpedo",
    "id": 319,
    "generation": 3
  },
  {
    "name": "Shaymin",
    "id": 492,
    "generation": 4
  },
  {
    "name": "Shedinja",
    "id": 292,
    "generation": 3
  },
  {
    "name": "Shelgon",
    "id": 372,
    "generation": 3
  },
  {
    "name": "Shellder",
    "id": 90,
    "generation": 1
  },
  {
    "name": "Shellos",
    "id": 422,
    "generation": 4
  },
  {
    "name": "Shelmet",
    "id": 616,
    "generation": 5
  },
  {
    "name": "Shieldon",
    "id": 410,
    "generation": 4
  },
  {
    "name": "Shiftry",
    "id": 275,
    "generation": 3
  },
  {
    "name": "Shinx",
    "id": 403,
    "generation": 4
  },
  {
    "name": "Shroomish",
    "id": 285,
    "generation": 3
  },
  {
    "name": "Shuckle",
    "id": 213,
    "generation": 2
  },
  {
    "name": "Shuppet",
    "id": 353,
    "generation": 3
  },
  {
    "name": "Sigilyph",
    "id": 561,
    "generation": 5
  },
  {
    "name": "Silcoon",
    "id": 266,
    "generation": 3
  },
  {
    "name": "Simipour",
    "id": 516,
    "generation": 5
  },
  {
    "name": "Simisage",
    "id": 512,
    "generation": 5
  },
  {
    "name": "Simisear",
    "id": 514,
    "generation": 5
  },
  {
    "name": "Skarmory",
    "id": 227,
    "generation": 2
  },
  {
    "name": "Skiddo",
    "id": 672,
    "generation": 6
  },
  {
    "name": "Skiploom",
    "id": 188,
    "generation": 2
  },
  {
    "name": "Skitty",
    "id": 300,
    "generation": 3
  },
  {
    "name": "Skorupi",
    "id": 451,
    "generation": 4
  },
  {
    "name": "Skrelp",
    "id": 690,
    "generation": 6
  },
  {
    "name": "Skuntank",
    "id": 435,
    "generation": 4
  },
  {
    "name": "Slaking",
    "id": 289,
    "generation": 3
  },
  {
    "name": "Slakoth",
    "id": 287,
    "generation": 3
  },
  {
    "name": "Sliggoo",
    "id": 705,
    "generation": 6
  },
  {
    "name": "Slowbro",
    "id": 80,
    "generation": 1
  },
  {
    "name": "Slowking",
    "id": 199,
    "generation": 2
  },
  {
    "name": "Slowpoke",
    "id": 79,
    "generation": 1
  },
  {
    "name": "Slugma",
    "id": 218,
    "generation": 2
  },
  {
    "name": "Slurpuff",
    "id": 685,
    "generation": 6
  },
  {
    "name": "Smeargle",
    "id": 235,
    "generation": 2
  },
  {
    "name": "Smoochum",
    "id": 238,
    "generation": 2
  },
  {
    "name": "Sneasel",
    "id": 215,
    "generation": 2
  },
  {
    "name": "Snivy",
    "id": 495,
    "generation": 5
  },
  {
    "name": "Snorlax",
    "id": 143,
    "generation": 1
  },
  {
    "name": "Snorunt",
    "id": 361,
    "generation": 3
  },
  {
    "name": "Snover",
    "id": 459,
    "generation": 4
  },
  {
    "name": "Snubbull",
    "id": 209,
    "generation": 2
  },
  {
    "name": "Solosis",
    "id": 577,
    "generation": 5
  },
  {
    "name": "Solrock",
    "id": 338,
    "generation": 3
  },
  {
    "name": "Spearow",
    "id": 21,
    "generation": 1
  },
  {
    "name": "Spewpa",
    "id": 665,
    "generation": 6
  },
  {
    "name": "Spheal",
    "id": 363,
    "generation": 3
  },
  {
    "name": "Spinarak",
    "id": 167,
    "generation": 2
  },
  {
    "name": "Spinda",
    "id": 327,
    "generation": 3
  },
  {
    "name": "Spiritomb",
    "id": 442,
    "generation": 4
  },
  {
    "name": "Spoink",
    "id": 325,
    "generation": 3
  },
  {
    "name": "Spritzee",
    "id": 682,
    "generation": 6
  },
  {
    "name": "Squirtle",
    "id": 7,
    "generation": 1
  },
  {
    "name": "Stantler",
    "id": 234,
    "generation": 2
  },
  {
    "name": "Staraptor",
    "id": 398,
    "generation": 4
  },
  {
    "name": "Staravia",
    "id": 397,
    "generation": 4
  },
  {
    "name": "Starly",
    "id": 396,
    "generation": 4
  },
  {
    "name": "Starmie",
    "id": 121,
    "generation": 1
  },
  {
    "name": "Staryu",
    "id": 120,
    "generation": 1
  },
  {
    "name": "Steelix",
    "id": 208,
    "generation": 2
  },
  {
    "name": "Stoutland",
    "id": 508,
    "generation": 5
  },
  {
    "name": "Stunfisk",
    "id": 618,
    "generation": 5
  },
  {
    "name": "Stunky",
    "id": 434,
    "generation": 4
  },
  {
    "name": "Sudowoodo",
    "id": 185,
    "generation": 2
  },
  {
    "name": "Suicune",
    "id": 245,
    "generation": 2
  },
  {
    "name": "Sunflora",
    "id": 192,
    "generation": 2
  },
  {
    "name": "Sunkern",
    "id": 191,
    "generation": 2
  },
  {
    "name": "Surskit",
    "id": 283,
    "generation": 3
  },
  {
    "name": "Swablu",
    "id": 333,
    "generation": 3
  },
  {
    "name": "Swadloon",
    "id": 541,
    "generation": 5
  },
  {
    "name": "Swalot",
    "id": 317,
    "generation": 3
  },
  {
    "name": "Swampert",
    "id": 260,
    "generation": 3
  },
  {
    "name": "Swanna",
    "id": 581,
    "generation": 5
  },
  {
    "name": "Swellow",
    "id": 277,
    "generation": 3
  },
  {
    "name": "Swinub",
    "id": 220,
    "generation": 2
  },
  {
    "name": "Swirlix",
    "id": 684,
    "generation": 6
  },
  {
    "name": "Swoobat",
    "id": 528,
    "generation": 5
  },
  {
    "name": "Sylveon",
    "id": 700,
    "generation": 6
  },
  {
    "name": "Taillow",
    "id": 276,
    "generation": 3
  },
  {
    "name": "Talonflame",
    "id": 663,
    "generation": 6
  },
  {
    "name": "Tangela",
    "id": 114,
    "generation": 1
  },
  {
    "name": "Tangrowth",
    "id": 465,
    "generation": 4
  },
  {
    "name": "Tauros",
    "id": 128,
    "generation": 1
  },
  {
    "name": "Teddiursa",
    "id": 216,
    "generation": 2
  },
  {
    "name": "Tentacool",
    "id": 72,
    "generation": 1
  },
  {
    "name": "Tentacruel",
    "id": 73,
    "generation": 1
  },
  {
    "name": "Tepig",
    "id": 498,
    "generation": 5
  },
  {
    "name": "Terrakion",
    "id": 639,
    "generation": 5
  },
  {
    "name": "Throh",
    "id": 538,
    "generation": 5
  },
  {
    "name": "Thundurus",
    "id": 642,
    "generation": 5
  },
  {
    "name": "Timburr",
    "id": 532,
    "generation": 5
  },
  {
    "name": "Tirtouga",
    "id": 564,
    "generation": 5
  },
  {
    "name": "Togekiss",
    "id": 468,
    "generation": 4
  },
  {
    "name": "Togepi",
    "id": 175,
    "generation": 2
  },
  {
    "name": "Togetic",
    "id": 176,
    "generation": 2
  },
  {
    "name": "Torchic",
    "id": 255,
    "generation": 3
  },
  {
    "name": "Torkoal",
    "id": 324,
    "generation": 3
  },
  {
    "name": "Tornadus",
    "id": 641,
    "generation": 5
  },
  {
    "name": "Torterra",
    "id": 389,
    "generation": 4
  },
  {
    "name": "Totodile",
    "id": 158,
    "generation": 2
  },
  {
    "name": "Toxicroak",
    "id": 454,
    "generation": 4
  },
  {
    "name": "Tranquill",
    "id": 520,
    "generation": 5
  },
  {
    "name": "Trapinch",
    "id": 328,
    "generation": 3
  },
  {
    "name": "Treecko",
    "id": 252,
    "generation": 3
  },
  {
    "name": "Trevenant",
    "id": 709,
    "generation": 6
  },
  {
    "name": "Tropius",
    "id": 357,
    "generation": 3
  },
  {
    "name": "Trubbish",
    "id": 568,
    "generation": 5
  },
  {
    "name": "Turtwig",
    "id": 387,
    "generation": 4
  },
  {
    "name": "Tympole",
    "id": 535,
    "generation": 5
  },
  {
    "name": "Tynamo",
    "id": 602,
    "generation": 5
  },
  {
    "name": "Typhlosion",
    "id": 157,
    "generation": 2
  },
  {
    "name": "Tyranitar",
    "id": 248,
    "generation": 2
  },
  {
    "name": "Tyrantrum",
    "id": 697,
    "generation": 6
  },
  {
    "name": "Tyrogue",
    "id": 236,
    "generation": 2
  },
  {
    "name": "Tyrunt",
    "id": 696,
    "generation": 6
  },
  {
    "name": "Umbreon",
    "id": 197,
    "generation": 2
  },
  {
    "name": "Unfezant",
    "id": 521,
    "generation": 5
  },
  {
    "name": "Unown",
    "id": 201,
    "generation": 2
  },
  {
    "name": "Ursaring",
    "id": 217,
    "generation": 2
  },
  {
    "name": "Uxie",
    "id": 480,
    "generation": 4
  },
  {
    "name": "Vanillish",
    "id": 583,
    "generation": 5
  },
  {
    "name": "Vanillite",
    "id": 582,
    "generation": 5
  },
  {
    "name": "Vanilluxe",
    "id": 584,
    "generation": 5
  },
  {
    "name": "Vaporeon",
    "id": 134,
    "generation": 1
  },
  {
    "name": "Venipede",
    "id": 543,
    "generation": 5
  },
  {
    "name": "Venomoth",
    "id": 49,
    "generation": 1
  },
  {
    "name": "Venonat",
    "id": 48,
    "generation": 1
  },
  {
    "name": "Venusaur",
    "id": 3,
    "generation": 1
  },
  {
    "name": "Vespiquen",
    "id": 416,
    "generation": 4
  },
  {
    "name": "Vibrava",
    "id": 329,
    "generation": 3
  },
  {
    "name": "Victini",
    "id": 494,
    "generation": 5
  },
  {
    "name": "Victreebel",
    "id": 71,
    "generation": 1
  },
  {
    "name": "Vigoroth",
    "id": 288,
    "generation": 3
  },
  {
    "name": "Vileplume",
    "id": 45,
    "generation": 1
  },
  {
    "name": "Virizion",
    "id": 640,
    "generation": 5
  },
  {
    "name": "Vivillon",
    "id": 666,
    "generation": 6
  },
  {
    "name": "Volbeat",
    "id": 313,
    "generation": 3
  },
  {
    "name": "Volcanion",
    "id": 721,
    "generation": 6
  },
  {
    "name": "Volcarona",
    "id": 637,
    "generation": 5
  },
  {
    "name": "Voltorb",
    "id": 100,
    "generation": 1
  },
  {
    "name": "Vullaby",
    "id": 629,
    "generation": 5
  },
  {
    "name": "Vulpix",
    "id": 37,
    "generation": 1
  },
  {
    "name": "Wailmer",
    "id": 320,
    "generation": 3
  },
  {
    "name": "Wailord",
    "id": 321,
    "generation": 3
  },
  {
    "name": "Walrein",
    "id": 365,
    "generation": 3
  },
  {
    "name": "Wartortle",
    "id": 8,
    "generation": 1
  },
  {
    "name": "Watchog",
    "id": 505,
    "generation": 5
  },
  {
    "name": "Weavile",
    "id": 461,
    "generation": 4
  },
  {
    "name": "Weedle",
    "id": 13,
    "generation": 1
  },
  {
    "name": "Weepinbell",
    "id": 70,
    "generation": 1
  },
  {
    "name": "Weezing",
    "id": 110,
    "generation": 1
  },
  {
    "name": "Whimsicott",
    "id": 547,
    "generation": 5
  },
  {
    "name": "Whirlipede",
    "id": 544,
    "generation": 5
  },
  {
    "name": "Whiscash",
    "id": 340,
    "generation": 3
  },
  {
    "name": "Whismur",
    "id": 293,
    "generation": 3
  },
  {
    "name": "Wigglytuff",
    "id": 40,
    "generation": 1
  },
  {
    "name": "Wingull",
    "id": 278,
    "generation": 3
  },
  {
    "name": "Wobbuffet",
    "id": 202,
    "generation": 2
  },
  {
    "name": "Woobat",
    "id": 527,
    "generation": 5
  },
  {
    "name": "Wooper",
    "id": 194,
    "generation": 2
  },
  {
    "name": "Wormadam",
    "id": 413,
    "generation": 4
  },
  {
    "name": "Wurmple",
    "id": 265,
    "generation": 3
  },
  {
    "name": "Wynaut",
    "id": 360,
    "generation": 3
  },
  {
    "name": "Xatu",
    "id": 178,
    "generation": 2
  },
  {
    "name": "Xerneas",
    "id": 716,
    "generation": 6
  },
  {
    "name": "Yamask",
    "id": 562,
    "generation": 5
  },
  {
    "name": "Yanma",
    "id": 193,
    "generation": 2
  },
  {
    "name": "Yanmega",
    "id": 469,
    "generation": 4
  },
  {
    "name": "Yveltal",
    "id": 717,
    "generation": 6
  },
  {
    "name": "Zangoose",
    "id": 335,
    "generation": 3
  },
  {
    "name": "Zapdos",
    "id": 145,
    "generation": 1
  },
  {
    "name": "Zebstrika",
    "id": 523,
    "generation": 5
  },
  {
    "name": "Zekrom",
    "id": 644,
    "generation": 5
  },
  {
    "name": "Zigzagoon",
    "id": 263,
    "generation": 3
  },
  {
    "name": "Zoroark",
    "id": 571,
    "generation": 5
  },
  {
    "name": "Zorua",
    "id": 570,
    "generation": 5
  },
  {
    "name": "Zubat",
    "id": 41,
    "generation": 1
  },
  {
    "name": "Zweilous",
    "id": 634,
    "generation": 5
  },
  {
    "name": "Zygarde",
    "id": 718,
    "generation": 6
  }
];
