// Generated by scripts/generate-pokemon-de.mjs
export const EVOLUTIONS_DE: Record<number, { id: number; methods: string[] }[]> = {
  "1": [
    {
      "id": 2,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "2": [
    {
      "id": 3,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "4": [
    {
      "id": 5,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "5": [
    {
      "id": 6,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "7": [
    {
      "id": 8,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "8": [
    {
      "id": 9,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "10": [
    {
      "id": 11,
      "methods": [
        "Level-Up - Level 7"
      ]
    }
  ],
  "11": [
    {
      "id": 12,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "13": [
    {
      "id": 14,
      "methods": [
        "Level-Up - Level 7"
      ]
    }
  ],
  "14": [
    {
      "id": 15,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "16": [
    {
      "id": 17,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "17": [
    {
      "id": 18,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "19": [
    {
      "id": 20,
      "methods": [
        "Level-Up - Level 20",
        "Level-Up - Level 20, Tageszeit: Nacht"
      ]
    }
  ],
  "21": [
    {
      "id": 22,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "23": [
    {
      "id": 24,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "25": [
    {
      "id": 26,
      "methods": [
        "Item: Donnerstein"
      ]
    }
  ],
  "27": [
    {
      "id": 28,
      "methods": [
        "Item: Eisstein",
        "Level-Up - Level 22"
      ]
    }
  ],
  "29": [
    {
      "id": 30,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "30": [
    {
      "id": 31,
      "methods": [
        "Item: Mondstein"
      ]
    }
  ],
  "32": [
    {
      "id": 33,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "33": [
    {
      "id": 34,
      "methods": [
        "Item: Mondstein"
      ]
    }
  ],
  "35": [
    {
      "id": 36,
      "methods": [
        "Item: Mondstein"
      ]
    }
  ],
  "37": [
    {
      "id": 38,
      "methods": [
        "Item: Eisstein",
        "Item: Feuerstein"
      ]
    }
  ],
  "39": [
    {
      "id": 40,
      "methods": [
        "Item: Mondstein"
      ]
    }
  ],
  "41": [
    {
      "id": 42,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "42": [
    {
      "id": 169,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "43": [
    {
      "id": 44,
      "methods": [
        "Level-Up - Level 21"
      ]
    }
  ],
  "44": [
    {
      "id": 45,
      "methods": [
        "Item: Blattstein"
      ]
    },
    {
      "id": 182,
      "methods": [
        "Item: Sonnenstein"
      ]
    }
  ],
  "46": [
    {
      "id": 47,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "48": [
    {
      "id": 49,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "50": [
    {
      "id": 51,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "52": [
    {
      "id": 53,
      "methods": [
        "Level-Up - Freundschaft ≥ 160",
        "Level-Up - Level 28"
      ]
    }
  ],
  "54": [
    {
      "id": 55,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "56": [
    {
      "id": 57,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "57": [],
  "58": [
    {
      "id": 59,
      "methods": [
        "Item: Feuerstein"
      ]
    }
  ],
  "60": [
    {
      "id": 61,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "61": [
    {
      "id": 62,
      "methods": [
        "Item: Wasserstein"
      ]
    },
    {
      "id": 186,
      "methods": [
        "Tausch - Trägt King-Stein"
      ]
    }
  ],
  "63": [
    {
      "id": 64,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "64": [
    {
      "id": 65,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "66": [
    {
      "id": 67,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "67": [
    {
      "id": 68,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "69": [
    {
      "id": 70,
      "methods": [
        "Level-Up - Level 21"
      ]
    }
  ],
  "70": [
    {
      "id": 71,
      "methods": [
        "Item: Blattstein"
      ]
    }
  ],
  "72": [
    {
      "id": 73,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "74": [
    {
      "id": 75,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "75": [
    {
      "id": 76,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "77": [
    {
      "id": 78,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "79": [
    {
      "id": 80,
      "methods": [
        "Item: Galarnuss-Reif",
        "Level-Up - Level 37"
      ]
    },
    {
      "id": 199,
      "methods": [
        "Item: Galarnuss-Kranz",
        "Tausch - Trägt King-Stein"
      ]
    }
  ],
  "81": [
    {
      "id": 82,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "82": [
    {
      "id": 462,
      "methods": [
        "Item: Donnerstein",
        "Level-Up",
        "Level-Up - Ort: Elektrolithhöhle",
        "Level-Up - Ort: Kraterberg",
        "Level-Up - Ort: Route 13"
      ]
    }
  ],
  "83": [],
  "84": [
    {
      "id": 85,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "86": [
    {
      "id": 87,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "88": [
    {
      "id": 89,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "90": [
    {
      "id": 91,
      "methods": [
        "Item: Wasserstein"
      ]
    }
  ],
  "92": [
    {
      "id": 93,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "93": [
    {
      "id": 94,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "95": [
    {
      "id": 208,
      "methods": [
        "Tausch - Trägt Metallmantel"
      ]
    }
  ],
  "96": [
    {
      "id": 97,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "98": [
    {
      "id": 99,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "100": [
    {
      "id": 101,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "102": [
    {
      "id": 103,
      "methods": [
        "Item: Blattstein"
      ]
    }
  ],
  "104": [
    {
      "id": 105,
      "methods": [
        "Level-Up - Level 28",
        "Level-Up - Level 28, Tageszeit: Nacht"
      ]
    }
  ],
  "108": [
    {
      "id": 463,
      "methods": [
        "Level-Up - Kennt Walzer"
      ]
    }
  ],
  "109": [
    {
      "id": 110,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "111": [
    {
      "id": 112,
      "methods": [
        "Level-Up - Level 42"
      ]
    }
  ],
  "112": [
    {
      "id": 464,
      "methods": [
        "Tausch - Trägt Schützer"
      ]
    }
  ],
  "113": [
    {
      "id": 242,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "114": [
    {
      "id": 465,
      "methods": [
        "Level-Up - Kennt Antik-Kraft"
      ]
    }
  ],
  "116": [
    {
      "id": 117,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "117": [
    {
      "id": 230,
      "methods": [
        "Tausch - Trägt Drachenhaut"
      ]
    }
  ],
  "118": [
    {
      "id": 119,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "120": [
    {
      "id": 121,
      "methods": [
        "Item: Wasserstein"
      ]
    }
  ],
  "122": [],
  "123": [
    {
      "id": 212,
      "methods": [
        "Tausch - Trägt Metallmantel"
      ]
    }
  ],
  "125": [
    {
      "id": 466,
      "methods": [
        "Tausch - Trägt Stromisierer"
      ]
    }
  ],
  "126": [
    {
      "id": 467,
      "methods": [
        "Tausch - Trägt Magmaisierer"
      ]
    }
  ],
  "129": [
    {
      "id": 130,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "133": [
    {
      "id": 134,
      "methods": [
        "Item: Wasserstein"
      ]
    },
    {
      "id": 135,
      "methods": [
        "Item: Donnerstein"
      ]
    },
    {
      "id": 136,
      "methods": [
        "Item: Feuerstein"
      ]
    },
    {
      "id": 196,
      "methods": [
        "Level-Up - Freundschaft ≥ 160, Tageszeit: Tag"
      ]
    },
    {
      "id": 197,
      "methods": [
        "Level-Up - Freundschaft ≥ 160, Tageszeit: Nacht"
      ]
    },
    {
      "id": 470,
      "methods": [
        "Item: Blattstein",
        "Level-Up - Ort: Ewigenwald",
        "Level-Up - Ort: Ewigwald",
        "Level-Up - Ort: Route 20"
      ]
    },
    {
      "id": 471,
      "methods": [
        "Item: Eisstein",
        "Level-Up - Ort: Frosthöhle",
        "Level-Up - Ort: Route 217",
        "Level-Up - Ort: Wendelberg"
      ]
    },
    {
      "id": 700,
      "methods": [
        "Level-Up - Freundschaft ≥ 160, Kennt Attacke vom Typ Fee",
        "Level-Up - Zutrauen ≥ 2, Kennt Attacke vom Typ Fee"
      ]
    }
  ],
  "137": [
    {
      "id": 233,
      "methods": [
        "Tausch - Trägt Up-Grade"
      ]
    }
  ],
  "138": [
    {
      "id": 139,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "140": [
    {
      "id": 141,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "147": [
    {
      "id": 148,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "148": [
    {
      "id": 149,
      "methods": [
        "Level-Up - Level 55"
      ]
    }
  ],
  "152": [
    {
      "id": 153,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "153": [
    {
      "id": 154,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "155": [
    {
      "id": 156,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "156": [
    {
      "id": 157,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "158": [
    {
      "id": 159,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "159": [
    {
      "id": 160,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "161": [
    {
      "id": 162,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "163": [
    {
      "id": 164,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "165": [
    {
      "id": 166,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "167": [
    {
      "id": 168,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "170": [
    {
      "id": 171,
      "methods": [
        "Level-Up - Level 27"
      ]
    }
  ],
  "172": [
    {
      "id": 25,
      "methods": [
        "Level-Up - Freundschaft ≥ 220"
      ]
    }
  ],
  "173": [
    {
      "id": 35,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "174": [
    {
      "id": 39,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "175": [
    {
      "id": 176,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "176": [
    {
      "id": 468,
      "methods": [
        "Item: Leuchtstein"
      ]
    }
  ],
  "177": [
    {
      "id": 178,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "179": [
    {
      "id": 180,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "180": [
    {
      "id": 181,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "183": [
    {
      "id": 184,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "187": [
    {
      "id": 188,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "188": [
    {
      "id": 189,
      "methods": [
        "Level-Up - Level 27"
      ]
    }
  ],
  "190": [
    {
      "id": 424,
      "methods": [
        "Level-Up - Kennt Doppelschlag"
      ]
    }
  ],
  "191": [
    {
      "id": 192,
      "methods": [
        "Item: Sonnenstein"
      ]
    }
  ],
  "193": [
    {
      "id": 469,
      "methods": [
        "Level-Up - Kennt Antik-Kraft"
      ]
    }
  ],
  "194": [
    {
      "id": 195,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "198": [
    {
      "id": 430,
      "methods": [
        "Item: Finsterstein"
      ]
    }
  ],
  "200": [
    {
      "id": 429,
      "methods": [
        "Item: Finsterstein"
      ]
    }
  ],
  "203": [],
  "204": [
    {
      "id": 205,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "206": [],
  "207": [
    {
      "id": 472,
      "methods": [
        "Level-Up - Tageszeit: Nacht, Trägt Scharfzahn"
      ]
    }
  ],
  "209": [
    {
      "id": 210,
      "methods": [
        "Level-Up - Level 23"
      ]
    }
  ],
  "211": [],
  "215": [
    {
      "id": 461,
      "methods": [
        "Level-Up - Tageszeit: Nacht, Trägt Scharfklaue"
      ]
    }
  ],
  "216": [
    {
      "id": 217,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "217": [],
  "218": [
    {
      "id": 219,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "220": [
    {
      "id": 221,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "221": [
    {
      "id": 473,
      "methods": [
        "Level-Up - Kennt Antik-Kraft"
      ]
    }
  ],
  "222": [],
  "223": [
    {
      "id": 224,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "228": [
    {
      "id": 229,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "231": [
    {
      "id": 232,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "233": [
    {
      "id": 474,
      "methods": [
        "Tausch - Trägt Dubiosdisc"
      ]
    }
  ],
  "234": [],
  "236": [
    {
      "id": 106,
      "methods": [
        "Level-Up - Level 20, Angriff > Verteidigung"
      ]
    },
    {
      "id": 107,
      "methods": [
        "Level-Up - Level 20, Angriff < Verteidigung"
      ]
    },
    {
      "id": 237,
      "methods": [
        "Level-Up - Level 20, Angriff = Verteidigung"
      ]
    }
  ],
  "238": [
    {
      "id": 124,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "239": [
    {
      "id": 125,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "240": [
    {
      "id": 126,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "246": [
    {
      "id": 247,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "247": [
    {
      "id": 248,
      "methods": [
        "Level-Up - Level 55"
      ]
    }
  ],
  "252": [
    {
      "id": 253,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "253": [
    {
      "id": 254,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "255": [
    {
      "id": 256,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "256": [
    {
      "id": 257,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "258": [
    {
      "id": 259,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "259": [
    {
      "id": 260,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "261": [
    {
      "id": 262,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "263": [
    {
      "id": 264,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "264": [],
  "265": [
    {
      "id": 266,
      "methods": [
        "Level-Up - Level 7"
      ]
    },
    {
      "id": 268,
      "methods": [
        "Level-Up - Level 7"
      ]
    }
  ],
  "266": [
    {
      "id": 267,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "268": [
    {
      "id": 269,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "270": [
    {
      "id": 271,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "271": [
    {
      "id": 272,
      "methods": [
        "Item: Wasserstein"
      ]
    }
  ],
  "273": [
    {
      "id": 274,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "274": [
    {
      "id": 275,
      "methods": [
        "Item: Blattstein"
      ]
    }
  ],
  "276": [
    {
      "id": 277,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "278": [
    {
      "id": 279,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "280": [
    {
      "id": 281,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "281": [
    {
      "id": 282,
      "methods": [
        "Level-Up - Level 30"
      ]
    },
    {
      "id": 475,
      "methods": [
        "Item: Funkelstein - Nur männlich"
      ]
    }
  ],
  "283": [
    {
      "id": 284,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "285": [
    {
      "id": 286,
      "methods": [
        "Level-Up - Level 23"
      ]
    }
  ],
  "287": [
    {
      "id": 288,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "288": [
    {
      "id": 289,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "290": [
    {
      "id": 291,
      "methods": [
        "Level-Up - Level 20"
      ]
    },
    {
      "id": 292,
      "methods": [
        "Spezial: Ninjatom"
      ]
    }
  ],
  "293": [
    {
      "id": 294,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "294": [
    {
      "id": 295,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "296": [
    {
      "id": 297,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "298": [
    {
      "id": 183,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "299": [
    {
      "id": 476,
      "methods": [
        "Level-Up",
        "Level-Up - Ort: Elektrolithhöhle",
        "Level-Up - Ort: Kraterberg",
        "Level-Up - Ort: Route 13"
      ]
    }
  ],
  "300": [
    {
      "id": 301,
      "methods": [
        "Item: Mondstein"
      ]
    }
  ],
  "304": [
    {
      "id": 305,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "305": [
    {
      "id": 306,
      "methods": [
        "Level-Up - Level 42"
      ]
    }
  ],
  "307": [
    {
      "id": 308,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "309": [
    {
      "id": 310,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "315": [
    {
      "id": 407,
      "methods": [
        "Item: Leuchtstein"
      ]
    }
  ],
  "316": [
    {
      "id": 317,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "318": [
    {
      "id": 319,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "320": [
    {
      "id": 321,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "322": [
    {
      "id": 323,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "325": [
    {
      "id": 326,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "328": [
    {
      "id": 329,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "329": [
    {
      "id": 330,
      "methods": [
        "Level-Up - Level 45"
      ]
    }
  ],
  "331": [
    {
      "id": 332,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "333": [
    {
      "id": 334,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "339": [
    {
      "id": 340,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "341": [
    {
      "id": 342,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "343": [
    {
      "id": 344,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "345": [
    {
      "id": 346,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "347": [
    {
      "id": 348,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "349": [
    {
      "id": 350,
      "methods": [
        "Level-Up - Schönheit ≥ 170",
        "Level-Up - Schönheit ≥ 171",
        "Tausch - Trägt Schönschuppe"
      ]
    }
  ],
  "353": [
    {
      "id": 354,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "355": [
    {
      "id": 356,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "356": [
    {
      "id": 477,
      "methods": [
        "Tausch - Trägt Düsterumhang"
      ]
    }
  ],
  "360": [
    {
      "id": 202,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "361": [
    {
      "id": 362,
      "methods": [
        "Level-Up - Level 42"
      ]
    },
    {
      "id": 478,
      "methods": [
        "Item: Funkelstein - Nur weiblich"
      ]
    }
  ],
  "363": [
    {
      "id": 364,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "364": [
    {
      "id": 365,
      "methods": [
        "Level-Up - Level 44"
      ]
    }
  ],
  "366": [
    {
      "id": 367,
      "methods": [
        "Tausch - Trägt Abysszahn"
      ]
    },
    {
      "id": 368,
      "methods": [
        "Tausch - Trägt Abyssplatte"
      ]
    }
  ],
  "371": [
    {
      "id": 372,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "372": [
    {
      "id": 373,
      "methods": [
        "Level-Up - Level 50"
      ]
    }
  ],
  "374": [
    {
      "id": 375,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "375": [
    {
      "id": 376,
      "methods": [
        "Level-Up - Level 45"
      ]
    }
  ],
  "387": [
    {
      "id": 388,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "388": [
    {
      "id": 389,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "390": [
    {
      "id": 391,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "391": [
    {
      "id": 392,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "393": [
    {
      "id": 394,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "394": [
    {
      "id": 395,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "396": [
    {
      "id": 397,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "397": [
    {
      "id": 398,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "399": [
    {
      "id": 400,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "401": [
    {
      "id": 402,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "403": [
    {
      "id": 404,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "404": [
    {
      "id": 405,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "406": [
    {
      "id": 315,
      "methods": [
        "Level-Up - Freundschaft ≥ 160, Tageszeit: Tag"
      ]
    }
  ],
  "408": [
    {
      "id": 409,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "410": [
    {
      "id": 411,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "412": [
    {
      "id": 413,
      "methods": [
        "Level-Up - Level 20, Nur weiblich"
      ]
    },
    {
      "id": 414,
      "methods": [
        "Level-Up - Level 20, Nur männlich"
      ]
    }
  ],
  "415": [
    {
      "id": 416,
      "methods": [
        "Level-Up - Level 21, Nur weiblich"
      ]
    }
  ],
  "418": [
    {
      "id": 419,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "420": [
    {
      "id": 421,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "422": [
    {
      "id": 423,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "425": [
    {
      "id": 426,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "427": [
    {
      "id": 428,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "431": [
    {
      "id": 432,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "433": [
    {
      "id": 358,
      "methods": [
        "Level-Up - Freundschaft ≥ 220, Tageszeit: Nacht"
      ]
    }
  ],
  "434": [
    {
      "id": 435,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "436": [
    {
      "id": 437,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "438": [
    {
      "id": 185,
      "methods": [
        "Level-Up - Kennt Mimikry"
      ]
    }
  ],
  "439": [
    {
      "id": 122,
      "methods": [
        "Level-Up - Kennt Mimikry"
      ]
    }
  ],
  "440": [
    {
      "id": 113,
      "methods": [
        "Level-Up - Tageszeit: Tag, Trägt Ovaler Stein"
      ]
    }
  ],
  "443": [
    {
      "id": 444,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "444": [
    {
      "id": 445,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ],
  "446": [
    {
      "id": 143,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "447": [
    {
      "id": 448,
      "methods": [
        "Level-Up - Freundschaft ≥ 160, Tageszeit: Tag"
      ]
    }
  ],
  "449": [
    {
      "id": 450,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "451": [
    {
      "id": 452,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "453": [
    {
      "id": 454,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "456": [
    {
      "id": 457,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "458": [
    {
      "id": 226,
      "methods": [
        "Level-Up - Team: Remoraid"
      ]
    }
  ],
  "459": [
    {
      "id": 460,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "495": [
    {
      "id": 496,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "496": [
    {
      "id": 497,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "498": [
    {
      "id": 499,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "499": [
    {
      "id": 500,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "501": [
    {
      "id": 502,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "502": [
    {
      "id": 503,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "504": [
    {
      "id": 505,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "506": [
    {
      "id": 507,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "507": [
    {
      "id": 508,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "509": [
    {
      "id": 510,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "511": [],
  "513": [
    {
      "id": 514,
      "methods": [
        "Item: Feuerstein"
      ]
    }
  ],
  "515": [
    {
      "id": 516,
      "methods": [
        "Item: Wasserstein"
      ]
    }
  ],
  "517": [
    {
      "id": 518,
      "methods": [
        "Item: Mondstein"
      ]
    }
  ],
  "519": [
    {
      "id": 520,
      "methods": [
        "Level-Up - Level 21"
      ]
    }
  ],
  "520": [
    {
      "id": 521,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "522": [
    {
      "id": 523,
      "methods": [
        "Level-Up - Level 27"
      ]
    }
  ],
  "524": [
    {
      "id": 525,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "525": [
    {
      "id": 526,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "527": [
    {
      "id": 528,
      "methods": [
        "Level-Up - Freundschaft ≥ 160"
      ]
    }
  ],
  "529": [
    {
      "id": 530,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "532": [
    {
      "id": 533,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "533": [
    {
      "id": 534,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "535": [
    {
      "id": 536,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "536": [
    {
      "id": 537,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "540": [
    {
      "id": 541,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "541": [
    {
      "id": 542,
      "methods": [
        "Level-Up - Freundschaft ≥ 220"
      ]
    }
  ],
  "543": [
    {
      "id": 544,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "544": [
    {
      "id": 545,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "546": [
    {
      "id": 547,
      "methods": [
        "Item: Sonnenstein"
      ]
    }
  ],
  "548": [
    {
      "id": 549,
      "methods": [
        "Item: Sonnenstein"
      ]
    }
  ],
  "550": [],
  "551": [
    {
      "id": 552,
      "methods": [
        "Level-Up - Level 29"
      ]
    }
  ],
  "552": [
    {
      "id": 553,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "554": [
    {
      "id": 555,
      "methods": [
        "Item: Eisstein",
        "Level-Up - Level 35"
      ]
    }
  ],
  "557": [
    {
      "id": 558,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "559": [
    {
      "id": 560,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "562": [
    {
      "id": 563,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "564": [
    {
      "id": 565,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "566": [
    {
      "id": 567,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "568": [
    {
      "id": 569,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "570": [
    {
      "id": 571,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "572": [
    {
      "id": 573,
      "methods": [
        "Item: Leuchtstein"
      ]
    }
  ],
  "574": [
    {
      "id": 575,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "575": [
    {
      "id": 576,
      "methods": [
        "Level-Up - Level 41"
      ]
    }
  ],
  "577": [
    {
      "id": 578,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "578": [
    {
      "id": 579,
      "methods": [
        "Level-Up - Level 41"
      ]
    }
  ],
  "580": [
    {
      "id": 581,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "582": [
    {
      "id": 583,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "583": [
    {
      "id": 584,
      "methods": [
        "Level-Up - Level 47"
      ]
    }
  ],
  "585": [
    {
      "id": 586,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "588": [
    {
      "id": 589,
      "methods": [
        "Tausch mit Schnuthelm"
      ]
    }
  ],
  "590": [
    {
      "id": 591,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "592": [
    {
      "id": 593,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "595": [
    {
      "id": 596,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "597": [
    {
      "id": 598,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "599": [
    {
      "id": 600,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "600": [
    {
      "id": 601,
      "methods": [
        "Level-Up - Level 49"
      ]
    }
  ],
  "602": [
    {
      "id": 603,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "603": [
    {
      "id": 604,
      "methods": [
        "Item: Donnerstein"
      ]
    }
  ],
  "605": [
    {
      "id": 606,
      "methods": [
        "Level-Up - Level 42"
      ]
    }
  ],
  "607": [
    {
      "id": 608,
      "methods": [
        "Level-Up - Level 41"
      ]
    }
  ],
  "608": [
    {
      "id": 609,
      "methods": [
        "Item: Finsterstein"
      ]
    }
  ],
  "610": [
    {
      "id": 611,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "611": [
    {
      "id": 612,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ],
  "613": [
    {
      "id": 614,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "616": [
    {
      "id": 617,
      "methods": [
        "Tausch mit Laukaps"
      ]
    }
  ],
  "619": [
    {
      "id": 620,
      "methods": [
        "Level-Up - Level 50"
      ]
    }
  ],
  "622": [
    {
      "id": 623,
      "methods": [
        "Level-Up - Level 43"
      ]
    }
  ],
  "624": [
    {
      "id": 625,
      "methods": [
        "Level-Up - Level 52"
      ]
    }
  ],
  "625": [],
  "627": [
    {
      "id": 628,
      "methods": [
        "Level-Up - Level 54"
      ]
    }
  ],
  "629": [
    {
      "id": 630,
      "methods": [
        "Level-Up - Level 54"
      ]
    }
  ],
  "633": [
    {
      "id": 634,
      "methods": [
        "Level-Up - Level 50"
      ]
    }
  ],
  "634": [
    {
      "id": 635,
      "methods": [
        "Level-Up - Level 64"
      ]
    }
  ],
  "636": [
    {
      "id": 637,
      "methods": [
        "Level-Up - Level 59"
      ]
    }
  ],
  "650": [
    {
      "id": 651,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "651": [
    {
      "id": 652,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "653": [
    {
      "id": 654,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "654": [
    {
      "id": 655,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "656": [
    {
      "id": 657,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "657": [
    {
      "id": 658,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "659": [
    {
      "id": 660,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "661": [
    {
      "id": 662,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "662": [
    {
      "id": 663,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "664": [
    {
      "id": 665,
      "methods": [
        "Level-Up - Level 9"
      ]
    }
  ],
  "665": [
    {
      "id": 666,
      "methods": [
        "Level-Up - Level 12"
      ]
    }
  ],
  "667": [
    {
      "id": 668,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "669": [
    {
      "id": 670,
      "methods": [
        "Level-Up - Level 19"
      ]
    }
  ],
  "670": [
    {
      "id": 671,
      "methods": [
        "Item: Leuchtstein"
      ]
    }
  ],
  "672": [
    {
      "id": 673,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "674": [
    {
      "id": 675,
      "methods": [
        "Level-Up - Level 32, Pokémon von Typ Unlicht im Team"
      ]
    }
  ],
  "677": [
    {
      "id": 678,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "679": [
    {
      "id": 680,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "680": [
    {
      "id": 681,
      "methods": [
        "Item: Finsterstein"
      ]
    }
  ],
  "682": [
    {
      "id": 683,
      "methods": [
        "Tausch - Trägt Duftbeutel"
      ]
    }
  ],
  "684": [
    {
      "id": 685,
      "methods": [
        "Tausch - Trägt Sahnehäubchen"
      ]
    }
  ],
  "686": [
    {
      "id": 687,
      "methods": [
        "Level-Up - Level 30, Konsole umdrehen"
      ]
    }
  ],
  "688": [
    {
      "id": 689,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "690": [
    {
      "id": 691,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ],
  "692": [
    {
      "id": 693,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "694": [
    {
      "id": 695,
      "methods": [
        "Item: Sonnenstein"
      ]
    }
  ],
  "696": [
    {
      "id": 697,
      "methods": [
        "Level-Up - Level 39, Tageszeit: Tag"
      ]
    }
  ],
  "698": [
    {
      "id": 699,
      "methods": [
        "Level-Up - Level 39, Tageszeit: Nacht"
      ]
    }
  ],
  "704": [
    {
      "id": 705,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "705": [
    {
      "id": 706,
      "methods": [
        "Level-Up - Level 50, Regen in der Oberwelt"
      ]
    }
  ],
  "708": [
    {
      "id": 709,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "710": [
    {
      "id": 711,
      "methods": [
        "Tausch"
      ]
    }
  ],
  "712": [
    {
      "id": 713,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "714": [
    {
      "id": 715,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ]
};

export const EVOLUTIONS_EN: Record<number, { id: number; methods: string[] }[]> = {
  "1": [
    {
      "id": 2,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "2": [
    {
      "id": 3,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "4": [
    {
      "id": 5,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "5": [
    {
      "id": 6,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "7": [
    {
      "id": 8,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "8": [
    {
      "id": 9,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "10": [
    {
      "id": 11,
      "methods": [
        "Level-Up - Level 7"
      ]
    }
  ],
  "11": [
    {
      "id": 12,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "13": [
    {
      "id": 14,
      "methods": [
        "Level-Up - Level 7"
      ]
    }
  ],
  "14": [
    {
      "id": 15,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "16": [
    {
      "id": 17,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "17": [
    {
      "id": 18,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "19": [
    {
      "id": 20,
      "methods": [
        "Level-Up - Level 20",
        "Level-Up - Level 20, Time of day: Night"
      ]
    }
  ],
  "21": [
    {
      "id": 22,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "23": [
    {
      "id": 24,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "25": [
    {
      "id": 26,
      "methods": [
        "Item: Thunder Stone"
      ]
    }
  ],
  "27": [
    {
      "id": 28,
      "methods": [
        "Item: Ice Stone",
        "Level-Up - Level 22"
      ]
    }
  ],
  "29": [
    {
      "id": 30,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "30": [
    {
      "id": 31,
      "methods": [
        "Item: Moon Stone"
      ]
    }
  ],
  "32": [
    {
      "id": 33,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "33": [
    {
      "id": 34,
      "methods": [
        "Item: Moon Stone"
      ]
    }
  ],
  "35": [
    {
      "id": 36,
      "methods": [
        "Item: Moon Stone"
      ]
    }
  ],
  "37": [
    {
      "id": 38,
      "methods": [
        "Item: Fire Stone",
        "Item: Ice Stone"
      ]
    }
  ],
  "39": [
    {
      "id": 40,
      "methods": [
        "Item: Moon Stone"
      ]
    }
  ],
  "41": [
    {
      "id": 42,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "42": [
    {
      "id": 169,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "43": [
    {
      "id": 44,
      "methods": [
        "Level-Up - Level 21"
      ]
    }
  ],
  "44": [
    {
      "id": 45,
      "methods": [
        "Item: Leaf Stone"
      ]
    },
    {
      "id": 182,
      "methods": [
        "Item: Sun Stone"
      ]
    }
  ],
  "46": [
    {
      "id": 47,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "48": [
    {
      "id": 49,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "50": [
    {
      "id": 51,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "52": [
    {
      "id": 53,
      "methods": [
        "Level-Up - Friendship ≥ 160",
        "Level-Up - Level 28"
      ]
    }
  ],
  "54": [
    {
      "id": 55,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "56": [
    {
      "id": 57,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "57": [],
  "58": [
    {
      "id": 59,
      "methods": [
        "Item: Fire Stone"
      ]
    }
  ],
  "60": [
    {
      "id": 61,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "61": [
    {
      "id": 62,
      "methods": [
        "Item: Water Stone"
      ]
    },
    {
      "id": 186,
      "methods": [
        "Trade - Holds King’s Rock"
      ]
    }
  ],
  "63": [
    {
      "id": 64,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "64": [
    {
      "id": 65,
      "methods": [
        "Trade"
      ]
    }
  ],
  "66": [
    {
      "id": 67,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "67": [
    {
      "id": 68,
      "methods": [
        "Trade"
      ]
    }
  ],
  "69": [
    {
      "id": 70,
      "methods": [
        "Level-Up - Level 21"
      ]
    }
  ],
  "70": [
    {
      "id": 71,
      "methods": [
        "Item: Leaf Stone"
      ]
    }
  ],
  "72": [
    {
      "id": 73,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "74": [
    {
      "id": 75,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "75": [
    {
      "id": 76,
      "methods": [
        "Trade"
      ]
    }
  ],
  "77": [
    {
      "id": 78,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "79": [
    {
      "id": 80,
      "methods": [
        "Item: Galarica Cuff",
        "Level-Up - Level 37"
      ]
    },
    {
      "id": 199,
      "methods": [
        "Item: Galarica Wreath",
        "Trade - Holds King’s Rock"
      ]
    }
  ],
  "81": [
    {
      "id": 82,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "82": [
    {
      "id": 462,
      "methods": [
        "Item: Thunder Stone",
        "Level-Up",
        "Level-Up - Location: Chargestone Cave",
        "Level-Up - Location: Mt. Coronet",
        "Level-Up - Location: Route 13"
      ]
    }
  ],
  "83": [],
  "84": [
    {
      "id": 85,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "86": [
    {
      "id": 87,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "88": [
    {
      "id": 89,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "90": [
    {
      "id": 91,
      "methods": [
        "Item: Water Stone"
      ]
    }
  ],
  "92": [
    {
      "id": 93,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "93": [
    {
      "id": 94,
      "methods": [
        "Trade"
      ]
    }
  ],
  "95": [
    {
      "id": 208,
      "methods": [
        "Trade - Holds Metal Coat"
      ]
    }
  ],
  "96": [
    {
      "id": 97,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "98": [
    {
      "id": 99,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "100": [
    {
      "id": 101,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "102": [
    {
      "id": 103,
      "methods": [
        "Item: Leaf Stone"
      ]
    }
  ],
  "104": [
    {
      "id": 105,
      "methods": [
        "Level-Up - Level 28",
        "Level-Up - Level 28, Time of day: Night"
      ]
    }
  ],
  "108": [
    {
      "id": 463,
      "methods": [
        "Level-Up - Knows Rollout"
      ]
    }
  ],
  "109": [
    {
      "id": 110,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "111": [
    {
      "id": 112,
      "methods": [
        "Level-Up - Level 42"
      ]
    }
  ],
  "112": [
    {
      "id": 464,
      "methods": [
        "Trade - Holds Protector"
      ]
    }
  ],
  "113": [
    {
      "id": 242,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "114": [
    {
      "id": 465,
      "methods": [
        "Level-Up - Knows Ancient Power"
      ]
    }
  ],
  "116": [
    {
      "id": 117,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "117": [
    {
      "id": 230,
      "methods": [
        "Trade - Holds Dragon Scale"
      ]
    }
  ],
  "118": [
    {
      "id": 119,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "120": [
    {
      "id": 121,
      "methods": [
        "Item: Water Stone"
      ]
    }
  ],
  "122": [],
  "123": [
    {
      "id": 212,
      "methods": [
        "Trade - Holds Metal Coat"
      ]
    }
  ],
  "125": [
    {
      "id": 466,
      "methods": [
        "Trade - Holds Electirizer"
      ]
    }
  ],
  "126": [
    {
      "id": 467,
      "methods": [
        "Trade - Holds Magmarizer"
      ]
    }
  ],
  "129": [
    {
      "id": 130,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "133": [
    {
      "id": 134,
      "methods": [
        "Item: Water Stone"
      ]
    },
    {
      "id": 135,
      "methods": [
        "Item: Thunder Stone"
      ]
    },
    {
      "id": 136,
      "methods": [
        "Item: Fire Stone"
      ]
    },
    {
      "id": 196,
      "methods": [
        "Level-Up - Friendship ≥ 160, Time of day: Day"
      ]
    },
    {
      "id": 197,
      "methods": [
        "Level-Up - Friendship ≥ 160, Time of day: Night"
      ]
    },
    {
      "id": 470,
      "methods": [
        "Item: Leaf Stone",
        "Level-Up - Location: Eterna Forest",
        "Level-Up - Location: Pinwheel Forest",
        "Level-Up - Location: Route 20"
      ]
    },
    {
      "id": 471,
      "methods": [
        "Item: Ice Stone",
        "Level-Up - Location: Frost Cavern",
        "Level-Up - Location: Route 217",
        "Level-Up - Location: Twist Mountain"
      ]
    },
    {
      "id": 700,
      "methods": [
        "Level-Up - Affection ≥ 2, Knows move of type Fairy",
        "Level-Up - Friendship ≥ 160, Knows move of type Fairy"
      ]
    }
  ],
  "137": [
    {
      "id": 233,
      "methods": [
        "Trade - Holds Upgrade"
      ]
    }
  ],
  "138": [
    {
      "id": 139,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "140": [
    {
      "id": 141,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "147": [
    {
      "id": 148,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "148": [
    {
      "id": 149,
      "methods": [
        "Level-Up - Level 55"
      ]
    }
  ],
  "152": [
    {
      "id": 153,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "153": [
    {
      "id": 154,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "155": [
    {
      "id": 156,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "156": [
    {
      "id": 157,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "158": [
    {
      "id": 159,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "159": [
    {
      "id": 160,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "161": [
    {
      "id": 162,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "163": [
    {
      "id": 164,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "165": [
    {
      "id": 166,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "167": [
    {
      "id": 168,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "170": [
    {
      "id": 171,
      "methods": [
        "Level-Up - Level 27"
      ]
    }
  ],
  "172": [
    {
      "id": 25,
      "methods": [
        "Level-Up - Friendship ≥ 220"
      ]
    }
  ],
  "173": [
    {
      "id": 35,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "174": [
    {
      "id": 39,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "175": [
    {
      "id": 176,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "176": [
    {
      "id": 468,
      "methods": [
        "Item: Shiny Stone"
      ]
    }
  ],
  "177": [
    {
      "id": 178,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "179": [
    {
      "id": 180,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "180": [
    {
      "id": 181,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "183": [
    {
      "id": 184,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "187": [
    {
      "id": 188,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "188": [
    {
      "id": 189,
      "methods": [
        "Level-Up - Level 27"
      ]
    }
  ],
  "190": [
    {
      "id": 424,
      "methods": [
        "Level-Up - Knows Double Hit"
      ]
    }
  ],
  "191": [
    {
      "id": 192,
      "methods": [
        "Item: Sun Stone"
      ]
    }
  ],
  "193": [
    {
      "id": 469,
      "methods": [
        "Level-Up - Knows Ancient Power"
      ]
    }
  ],
  "194": [
    {
      "id": 195,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "198": [
    {
      "id": 430,
      "methods": [
        "Item: Dusk Stone"
      ]
    }
  ],
  "200": [
    {
      "id": 429,
      "methods": [
        "Item: Dusk Stone"
      ]
    }
  ],
  "203": [],
  "204": [
    {
      "id": 205,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "206": [],
  "207": [
    {
      "id": 472,
      "methods": [
        "Level-Up - Time of day: Night, Holds Razor Fang"
      ]
    }
  ],
  "209": [
    {
      "id": 210,
      "methods": [
        "Level-Up - Level 23"
      ]
    }
  ],
  "211": [],
  "215": [
    {
      "id": 461,
      "methods": [
        "Level-Up - Time of day: Night, Holds Razor Claw"
      ]
    }
  ],
  "216": [
    {
      "id": 217,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "217": [],
  "218": [
    {
      "id": 219,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "220": [
    {
      "id": 221,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "221": [
    {
      "id": 473,
      "methods": [
        "Level-Up - Knows Ancient Power"
      ]
    }
  ],
  "222": [],
  "223": [
    {
      "id": 224,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "228": [
    {
      "id": 229,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "231": [
    {
      "id": 232,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "233": [
    {
      "id": 474,
      "methods": [
        "Trade - Holds Dubious Disc"
      ]
    }
  ],
  "234": [],
  "236": [
    {
      "id": 106,
      "methods": [
        "Level-Up - Level 20, Attack > Defense"
      ]
    },
    {
      "id": 107,
      "methods": [
        "Level-Up - Level 20, Attack < Defense"
      ]
    },
    {
      "id": 237,
      "methods": [
        "Level-Up - Level 20, Attack = Defense"
      ]
    }
  ],
  "238": [
    {
      "id": 124,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "239": [
    {
      "id": 125,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "240": [
    {
      "id": 126,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "246": [
    {
      "id": 247,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "247": [
    {
      "id": 248,
      "methods": [
        "Level-Up - Level 55"
      ]
    }
  ],
  "252": [
    {
      "id": 253,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "253": [
    {
      "id": 254,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "255": [
    {
      "id": 256,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "256": [
    {
      "id": 257,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "258": [
    {
      "id": 259,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "259": [
    {
      "id": 260,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "261": [
    {
      "id": 262,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "263": [
    {
      "id": 264,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "264": [],
  "265": [
    {
      "id": 266,
      "methods": [
        "Level-Up - Level 7"
      ]
    },
    {
      "id": 268,
      "methods": [
        "Level-Up - Level 7"
      ]
    }
  ],
  "266": [
    {
      "id": 267,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "268": [
    {
      "id": 269,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "270": [
    {
      "id": 271,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "271": [
    {
      "id": 272,
      "methods": [
        "Item: Water Stone"
      ]
    }
  ],
  "273": [
    {
      "id": 274,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "274": [
    {
      "id": 275,
      "methods": [
        "Item: Leaf Stone"
      ]
    }
  ],
  "276": [
    {
      "id": 277,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "278": [
    {
      "id": 279,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "280": [
    {
      "id": 281,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "281": [
    {
      "id": 282,
      "methods": [
        "Level-Up - Level 30"
      ]
    },
    {
      "id": 475,
      "methods": [
        "Item: Dawn Stone - Only male"
      ]
    }
  ],
  "283": [
    {
      "id": 284,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "285": [
    {
      "id": 286,
      "methods": [
        "Level-Up - Level 23"
      ]
    }
  ],
  "287": [
    {
      "id": 288,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "288": [
    {
      "id": 289,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "290": [
    {
      "id": 291,
      "methods": [
        "Level-Up - Level 20"
      ]
    },
    {
      "id": 292,
      "methods": [
        "Special: Shedinja"
      ]
    }
  ],
  "293": [
    {
      "id": 294,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "294": [
    {
      "id": 295,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "296": [
    {
      "id": 297,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "298": [
    {
      "id": 183,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "299": [
    {
      "id": 476,
      "methods": [
        "Level-Up",
        "Level-Up - Location: Chargestone Cave",
        "Level-Up - Location: Mt. Coronet",
        "Level-Up - Location: Route 13"
      ]
    }
  ],
  "300": [
    {
      "id": 301,
      "methods": [
        "Item: Moon Stone"
      ]
    }
  ],
  "304": [
    {
      "id": 305,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "305": [
    {
      "id": 306,
      "methods": [
        "Level-Up - Level 42"
      ]
    }
  ],
  "307": [
    {
      "id": 308,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "309": [
    {
      "id": 310,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "315": [
    {
      "id": 407,
      "methods": [
        "Item: Shiny Stone"
      ]
    }
  ],
  "316": [
    {
      "id": 317,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "318": [
    {
      "id": 319,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "320": [
    {
      "id": 321,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "322": [
    {
      "id": 323,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "325": [
    {
      "id": 326,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "328": [
    {
      "id": 329,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "329": [
    {
      "id": 330,
      "methods": [
        "Level-Up - Level 45"
      ]
    }
  ],
  "331": [
    {
      "id": 332,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "333": [
    {
      "id": 334,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "339": [
    {
      "id": 340,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "341": [
    {
      "id": 342,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "343": [
    {
      "id": 344,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "345": [
    {
      "id": 346,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "347": [
    {
      "id": 348,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "349": [
    {
      "id": 350,
      "methods": [
        "Level-Up - Beauty ≥ 170",
        "Level-Up - Beauty ≥ 171",
        "Trade - Holds Prism Scale"
      ]
    }
  ],
  "353": [
    {
      "id": 354,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "355": [
    {
      "id": 356,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "356": [
    {
      "id": 477,
      "methods": [
        "Trade - Holds Reaper Cloth"
      ]
    }
  ],
  "360": [
    {
      "id": 202,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "361": [
    {
      "id": 362,
      "methods": [
        "Level-Up - Level 42"
      ]
    },
    {
      "id": 478,
      "methods": [
        "Item: Dawn Stone - Only female"
      ]
    }
  ],
  "363": [
    {
      "id": 364,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "364": [
    {
      "id": 365,
      "methods": [
        "Level-Up - Level 44"
      ]
    }
  ],
  "366": [
    {
      "id": 367,
      "methods": [
        "Trade - Holds Deep Sea Tooth"
      ]
    },
    {
      "id": 368,
      "methods": [
        "Trade - Holds Deep Sea Scale"
      ]
    }
  ],
  "371": [
    {
      "id": 372,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "372": [
    {
      "id": 373,
      "methods": [
        "Level-Up - Level 50"
      ]
    }
  ],
  "374": [
    {
      "id": 375,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "375": [
    {
      "id": 376,
      "methods": [
        "Level-Up - Level 45"
      ]
    }
  ],
  "387": [
    {
      "id": 388,
      "methods": [
        "Level-Up - Level 18"
      ]
    }
  ],
  "388": [
    {
      "id": 389,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "390": [
    {
      "id": 391,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "391": [
    {
      "id": 392,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "393": [
    {
      "id": 394,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "394": [
    {
      "id": 395,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "396": [
    {
      "id": 397,
      "methods": [
        "Level-Up - Level 14"
      ]
    }
  ],
  "397": [
    {
      "id": 398,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "399": [
    {
      "id": 400,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "401": [
    {
      "id": 402,
      "methods": [
        "Level-Up - Level 10"
      ]
    }
  ],
  "403": [
    {
      "id": 404,
      "methods": [
        "Level-Up - Level 15"
      ]
    }
  ],
  "404": [
    {
      "id": 405,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "406": [
    {
      "id": 315,
      "methods": [
        "Level-Up - Friendship ≥ 160, Time of day: Day"
      ]
    }
  ],
  "408": [
    {
      "id": 409,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "410": [
    {
      "id": 411,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "412": [
    {
      "id": 413,
      "methods": [
        "Level-Up - Level 20, Only female"
      ]
    },
    {
      "id": 414,
      "methods": [
        "Level-Up - Level 20, Only male"
      ]
    }
  ],
  "415": [
    {
      "id": 416,
      "methods": [
        "Level-Up - Level 21, Only female"
      ]
    }
  ],
  "418": [
    {
      "id": 419,
      "methods": [
        "Level-Up - Level 26"
      ]
    }
  ],
  "420": [
    {
      "id": 421,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "422": [
    {
      "id": 423,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "425": [
    {
      "id": 426,
      "methods": [
        "Level-Up - Level 28"
      ]
    }
  ],
  "427": [
    {
      "id": 428,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "431": [
    {
      "id": 432,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "433": [
    {
      "id": 358,
      "methods": [
        "Level-Up - Friendship ≥ 220, Time of day: Night"
      ]
    }
  ],
  "434": [
    {
      "id": 435,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "436": [
    {
      "id": 437,
      "methods": [
        "Level-Up - Level 33"
      ]
    }
  ],
  "438": [
    {
      "id": 185,
      "methods": [
        "Level-Up - Knows Mimic"
      ]
    }
  ],
  "439": [
    {
      "id": 122,
      "methods": [
        "Level-Up - Knows Mimic"
      ]
    }
  ],
  "440": [
    {
      "id": 113,
      "methods": [
        "Level-Up - Time of day: Day, Holds Oval Stone"
      ]
    }
  ],
  "443": [
    {
      "id": 444,
      "methods": [
        "Level-Up - Level 24"
      ]
    }
  ],
  "444": [
    {
      "id": 445,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ],
  "446": [
    {
      "id": 143,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "447": [
    {
      "id": 448,
      "methods": [
        "Level-Up - Friendship ≥ 160, Time of day: Day"
      ]
    }
  ],
  "449": [
    {
      "id": 450,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "451": [
    {
      "id": 452,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "453": [
    {
      "id": 454,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "456": [
    {
      "id": 457,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "458": [
    {
      "id": 226,
      "methods": [
        "Level-Up - Party: Remoraid"
      ]
    }
  ],
  "459": [
    {
      "id": 460,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "495": [
    {
      "id": 496,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "496": [
    {
      "id": 497,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "498": [
    {
      "id": 499,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "499": [
    {
      "id": 500,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "501": [
    {
      "id": 502,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "502": [
    {
      "id": 503,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "504": [
    {
      "id": 505,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "506": [
    {
      "id": 507,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "507": [
    {
      "id": 508,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "509": [
    {
      "id": 510,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "511": [],
  "513": [
    {
      "id": 514,
      "methods": [
        "Item: Fire Stone"
      ]
    }
  ],
  "515": [
    {
      "id": 516,
      "methods": [
        "Item: Water Stone"
      ]
    }
  ],
  "517": [
    {
      "id": 518,
      "methods": [
        "Item: Moon Stone"
      ]
    }
  ],
  "519": [
    {
      "id": 520,
      "methods": [
        "Level-Up - Level 21"
      ]
    }
  ],
  "520": [
    {
      "id": 521,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "522": [
    {
      "id": 523,
      "methods": [
        "Level-Up - Level 27"
      ]
    }
  ],
  "524": [
    {
      "id": 525,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "525": [
    {
      "id": 526,
      "methods": [
        "Trade"
      ]
    }
  ],
  "527": [
    {
      "id": 528,
      "methods": [
        "Level-Up - Friendship ≥ 160"
      ]
    }
  ],
  "529": [
    {
      "id": 530,
      "methods": [
        "Level-Up - Level 31"
      ]
    }
  ],
  "532": [
    {
      "id": 533,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "533": [
    {
      "id": 534,
      "methods": [
        "Trade"
      ]
    }
  ],
  "535": [
    {
      "id": 536,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "536": [
    {
      "id": 537,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "540": [
    {
      "id": 541,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "541": [
    {
      "id": 542,
      "methods": [
        "Level-Up - Friendship ≥ 220"
      ]
    }
  ],
  "543": [
    {
      "id": 544,
      "methods": [
        "Level-Up - Level 22"
      ]
    }
  ],
  "544": [
    {
      "id": 545,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "546": [
    {
      "id": 547,
      "methods": [
        "Item: Sun Stone"
      ]
    }
  ],
  "548": [
    {
      "id": 549,
      "methods": [
        "Item: Sun Stone"
      ]
    }
  ],
  "550": [],
  "551": [
    {
      "id": 552,
      "methods": [
        "Level-Up - Level 29"
      ]
    }
  ],
  "552": [
    {
      "id": 553,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "554": [
    {
      "id": 555,
      "methods": [
        "Item: Ice Stone",
        "Level-Up - Level 35"
      ]
    }
  ],
  "557": [
    {
      "id": 558,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "559": [
    {
      "id": 560,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "562": [
    {
      "id": 563,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "564": [
    {
      "id": 565,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "566": [
    {
      "id": 567,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "568": [
    {
      "id": 569,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "570": [
    {
      "id": 571,
      "methods": [
        "Level-Up - Level 30"
      ]
    }
  ],
  "572": [
    {
      "id": 573,
      "methods": [
        "Item: Shiny Stone"
      ]
    }
  ],
  "574": [
    {
      "id": 575,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "575": [
    {
      "id": 576,
      "methods": [
        "Level-Up - Level 41"
      ]
    }
  ],
  "577": [
    {
      "id": 578,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "578": [
    {
      "id": 579,
      "methods": [
        "Level-Up - Level 41"
      ]
    }
  ],
  "580": [
    {
      "id": 581,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "582": [
    {
      "id": 583,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "583": [
    {
      "id": 584,
      "methods": [
        "Level-Up - Level 47"
      ]
    }
  ],
  "585": [
    {
      "id": 586,
      "methods": [
        "Level-Up - Level 34"
      ]
    }
  ],
  "588": [
    {
      "id": 589,
      "methods": [
        "Trade with Shelmet"
      ]
    }
  ],
  "590": [
    {
      "id": 591,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "592": [
    {
      "id": 593,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "595": [
    {
      "id": 596,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "597": [
    {
      "id": 598,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "599": [
    {
      "id": 600,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "600": [
    {
      "id": 601,
      "methods": [
        "Level-Up - Level 49"
      ]
    }
  ],
  "602": [
    {
      "id": 603,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "603": [
    {
      "id": 604,
      "methods": [
        "Item: Thunder Stone"
      ]
    }
  ],
  "605": [
    {
      "id": 606,
      "methods": [
        "Level-Up - Level 42"
      ]
    }
  ],
  "607": [
    {
      "id": 608,
      "methods": [
        "Level-Up - Level 41"
      ]
    }
  ],
  "608": [
    {
      "id": 609,
      "methods": [
        "Item: Dusk Stone"
      ]
    }
  ],
  "610": [
    {
      "id": 611,
      "methods": [
        "Level-Up - Level 38"
      ]
    }
  ],
  "611": [
    {
      "id": 612,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ],
  "613": [
    {
      "id": 614,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "616": [
    {
      "id": 617,
      "methods": [
        "Trade with Karrablast"
      ]
    }
  ],
  "619": [
    {
      "id": 620,
      "methods": [
        "Level-Up - Level 50"
      ]
    }
  ],
  "622": [
    {
      "id": 623,
      "methods": [
        "Level-Up - Level 43"
      ]
    }
  ],
  "624": [
    {
      "id": 625,
      "methods": [
        "Level-Up - Level 52"
      ]
    }
  ],
  "625": [],
  "627": [
    {
      "id": 628,
      "methods": [
        "Level-Up - Level 54"
      ]
    }
  ],
  "629": [
    {
      "id": 630,
      "methods": [
        "Level-Up - Level 54"
      ]
    }
  ],
  "633": [
    {
      "id": 634,
      "methods": [
        "Level-Up - Level 50"
      ]
    }
  ],
  "634": [
    {
      "id": 635,
      "methods": [
        "Level-Up - Level 64"
      ]
    }
  ],
  "636": [
    {
      "id": 637,
      "methods": [
        "Level-Up - Level 59"
      ]
    }
  ],
  "650": [
    {
      "id": 651,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "651": [
    {
      "id": 652,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "653": [
    {
      "id": 654,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "654": [
    {
      "id": 655,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "656": [
    {
      "id": 657,
      "methods": [
        "Level-Up - Level 16"
      ]
    }
  ],
  "657": [
    {
      "id": 658,
      "methods": [
        "Level-Up - Level 36"
      ]
    }
  ],
  "659": [
    {
      "id": 660,
      "methods": [
        "Level-Up - Level 20"
      ]
    }
  ],
  "661": [
    {
      "id": 662,
      "methods": [
        "Level-Up - Level 17"
      ]
    }
  ],
  "662": [
    {
      "id": 663,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "664": [
    {
      "id": 665,
      "methods": [
        "Level-Up - Level 9"
      ]
    }
  ],
  "665": [
    {
      "id": 666,
      "methods": [
        "Level-Up - Level 12"
      ]
    }
  ],
  "667": [
    {
      "id": 668,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "669": [
    {
      "id": 670,
      "methods": [
        "Level-Up - Level 19"
      ]
    }
  ],
  "670": [
    {
      "id": 671,
      "methods": [
        "Item: Shiny Stone"
      ]
    }
  ],
  "672": [
    {
      "id": 673,
      "methods": [
        "Level-Up - Level 32"
      ]
    }
  ],
  "674": [
    {
      "id": 675,
      "methods": [
        "Level-Up - Level 32, Pokémon of type Dark in party"
      ]
    }
  ],
  "677": [
    {
      "id": 678,
      "methods": [
        "Level-Up - Level 25"
      ]
    }
  ],
  "679": [
    {
      "id": 680,
      "methods": [
        "Level-Up - Level 35"
      ]
    }
  ],
  "680": [
    {
      "id": 681,
      "methods": [
        "Item: Dusk Stone"
      ]
    }
  ],
  "682": [
    {
      "id": 683,
      "methods": [
        "Trade - Holds Sachet"
      ]
    }
  ],
  "684": [
    {
      "id": 685,
      "methods": [
        "Trade - Holds Whipped Dream"
      ]
    }
  ],
  "686": [
    {
      "id": 687,
      "methods": [
        "Level-Up - Level 30, Turn console upside down"
      ]
    }
  ],
  "688": [
    {
      "id": 689,
      "methods": [
        "Level-Up - Level 39"
      ]
    }
  ],
  "690": [
    {
      "id": 691,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ],
  "692": [
    {
      "id": 693,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "694": [
    {
      "id": 695,
      "methods": [
        "Item: Sun Stone"
      ]
    }
  ],
  "696": [
    {
      "id": 697,
      "methods": [
        "Level-Up - Level 39, Time of day: Day"
      ]
    }
  ],
  "698": [
    {
      "id": 699,
      "methods": [
        "Level-Up - Level 39, Time of day: Night"
      ]
    }
  ],
  "704": [
    {
      "id": 705,
      "methods": [
        "Level-Up - Level 40"
      ]
    }
  ],
  "705": [
    {
      "id": 706,
      "methods": [
        "Level-Up - Level 50, Overworld rain"
      ]
    }
  ],
  "708": [
    {
      "id": 709,
      "methods": [
        "Trade"
      ]
    }
  ],
  "710": [
    {
      "id": 711,
      "methods": [
        "Trade"
      ]
    }
  ],
  "712": [
    {
      "id": 713,
      "methods": [
        "Level-Up - Level 37"
      ]
    }
  ],
  "714": [
    {
      "id": 715,
      "methods": [
        "Level-Up - Level 48"
      ]
    }
  ]
};
