name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: janlieder.de
          username: projects
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            cd /var/www/pokemon-soullink-tracker/
            git pull

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
            nvm use 22

            npm ci
            npm run build